let closeActivePicker=null;

const node=(tag,cls,text)=>{const element=document.createElement(tag);if(cls)element.className=cls;if(text!=null)element.textContent=text;return element;};
const normalized=(rows)=>Array.isArray(rows)?rows.map((row)=>({value:String(row?.value??""),title:String(row?.title||row?.value||""),detail:String(row?.detail||""),badge:String(row?.badge||""),action:row?.action===true})):[];

function copyTheme(anchor,menu){
  const style=getComputedStyle(anchor);
  for(const name of ["--z3-bg","--z3-panel","--z3-surface","--z3-line","--z3-line-strong","--z3-text","--z3-muted","--z3-accent","--z3-radius"]) {
    const value=style.getPropertyValue(name);if(value)menu.style.setProperty(name,value);
  }
}

export function createChoicePicker({choices=[],value="",onChange=null,disabled=false,ariaLabel="Choose an option"}={}){
  let rows=normalized(choices),selected=String(value),menu=null,cleanupOpen=()=>{};
  const root=node("div","z3h3-choice-picker"),trigger=node("button","z3h3-choice-trigger"),copy=node("span","z3h3-choice-copy"),title=node("b"),detail=node("small"),badge=node("em"),chevron=node("i",null,"⌄");
  trigger.type="button";trigger.setAttribute("aria-haspopup","listbox");trigger.setAttribute("aria-expanded","false");trigger.setAttribute("aria-label",ariaLabel);copy.append(title,detail);trigger.append(copy,badge,chevron);root.append(trigger);

  const current=()=>rows.find((row)=>row.value===selected)||rows[0]||{value:"",title:"—",detail:"",badge:""};
  const paint=()=>{const choice=current();selected=choice.value;title.textContent=choice.title;detail.textContent=choice.detail;detail.hidden=!choice.detail;badge.textContent=choice.badge;badge.hidden=!choice.badge;trigger.disabled=!!disabled;};
  const close=({focus=false}={})=>{if(!menu)return;cleanupOpen();cleanupOpen=()=>{};menu.remove();menu=null;trigger.setAttribute("aria-expanded","false");if(closeActivePicker===close)closeActivePicker=null;if(focus)trigger.focus({preventScroll:true});};
  const position=()=>{if(!menu)return;const rect=trigger.getBoundingClientRect(),gap=6,width=Math.min(Math.max(280,rect.width),innerWidth-16),spaceBelow=innerHeight-rect.bottom-12,spaceAbove=rect.top-18,estimated=Math.min(360,menu.scrollHeight),below=spaceBelow>=estimated||spaceBelow>=spaceAbove,maxHeight=Math.max(96,Math.min(360,below?spaceBelow:spaceAbove));menu.style.width=`${width}px`;menu.style.left=`${Math.max(8,Math.min(rect.left,innerWidth-width-8))}px`;menu.style.top=below?`${rect.bottom+gap}px`:`${Math.max(8,rect.top-gap-Math.min(estimated,maxHeight))}px`;menu.style.maxHeight=`${maxHeight}px`;};
  const open=()=>{if(disabled||menu)return;if(closeActivePicker)closeActivePicker();closeActivePicker=close;menu=node("div","z3h3-choice-menu");menu.setAttribute("role","listbox");menu.setAttribute("aria-label",ariaLabel);copyTheme(root,menu);const protect=(event)=>event.stopPropagation();for(const name of ["pointerdown","pointerup","mousedown","mouseup","click","dblclick","wheel"])menu.addEventListener(name,protect,false);for(const choice of rows){const option=node("button",`z3h3-choice-option${choice.value===selected?" active":""}`),optionCopy=node("span"),optionTitle=node("b",null,choice.title),optionDetail=node("small",null,choice.detail),optionBadge=node("em",null,choice.badge||(choice.value===selected?"Selected":""));option.type="button";option.setAttribute("role","option");option.setAttribute("aria-selected",String(!choice.action&&choice.value===selected));optionCopy.append(optionTitle);if(choice.detail)optionCopy.append(optionDetail);option.append(optionCopy,optionBadge);option.addEventListener("click",(event)=>{event.preventDefault();event.stopPropagation();if(choice.action){close({focus:true});onChange?.(choice.value,choice);return;}const changed=selected!==choice.value;selected=choice.value;paint();close({focus:true});if(changed)onChange?.(selected,choice);});menu.append(option);}document.body.append(menu);trigger.setAttribute("aria-expanded","true");position();const outside=(event)=>{if(!menu?.contains(event.target)&&!root.contains(event.target))close();},key=(event)=>{if(event.key==="Escape"){event.preventDefault();close({focus:true});}else if(event.key==="ArrowDown"||event.key==="ArrowUp"){const options=[...menu.querySelectorAll("button")],at=Math.max(0,options.indexOf(document.activeElement)),next=event.key==="ArrowDown"?Math.min(options.length-1,at+1):Math.max(0,at-1);event.preventDefault();options[next]?.focus();}},move=()=>position();document.addEventListener("pointerdown",outside,true);document.addEventListener("keydown",key,true);window.addEventListener("resize",move);window.addEventListener("scroll",move,true);cleanupOpen=()=>{document.removeEventListener("pointerdown",outside,true);document.removeEventListener("keydown",key,true);window.removeEventListener("resize",move);window.removeEventListener("scroll",move,true);};queueMicrotask(()=>menu?.querySelector('[aria-selected="true"]')?.focus({preventScroll:true}));};
  for(const name of ["pointerdown","pointerup","mousedown","mouseup","dblclick"])trigger.addEventListener(name,(event)=>event.stopPropagation());trigger.addEventListener("click",(event)=>{event.preventDefault();event.stopPropagation();menu?close():open();});trigger.addEventListener("keydown",(event)=>{event.stopPropagation();if((event.key==="ArrowDown"||event.key==="Enter"||event.key===" ")&&!menu){event.preventDefault();open();}});paint();
  return {root,get value(){return selected;},setValue(next){selected=String(next);paint();},setChoices(next,valueNow=selected){rows=normalized(next);selected=String(valueNow);paint();},setDisabled(next){disabled=!!next;paint();if(disabled)close();},cleanup(){close();}};
}
