import * as H from "./z3_h3_api.js";
import * as S from "./z3_h3_state.js";
import { createSubjectAvatar, subjectDisplayName, openCastStudio } from "./h3_cast_studio.js";
import { timingSummary, openTimingInspector } from "./h3_timing_inspector.js";
import { categoryMeta } from "./h3_prompt_categories.js";
import { subscribeCreatorBody } from "./h3_workspace_runtime.js";
import { renderStoryboardTimeline } from "./h3_storyboard_timeline.js";
import { effectiveAssetsForShot, referencedSubjectsForShot, inferShotMode, referenceCounts, validateCreatorShots } from "./h3_shot_snapshot.js";
import { openReferenceWorkspace } from "./h3_reference_workspace.js";
import { renderCanonicalShotInspector } from "./h3_shot_inspector.js";
import { persistCreatorBackup } from "./h3_persistence_guard.js";

let activeDock=null;
const STORY_PREF_KEY="z3.minimaxCreator.storyboardPrefs.v2";
function loadStoryPrefs(){try{const raw=JSON.parse(localStorage.getItem(STORY_PREF_KEY)||"{}");return raw&&typeof raw==="object"&&!Array.isArray(raw)?raw:{};}catch{return {};}}
function saveStoryPrefs(state,root=null){
  try{
    const value={zoom:Number(state.zoom)||74,snap:state.snap||"seconds",inspector:state.inspector!==false,trackVisibility:{...(state.trackVisibility||{})},scrollLeft:Number(state.scrollLeft)||0,scrollTop:Number(state.scrollTop)||0};
    if(root?.isConnected&&!state.maximized&&!state.minimized){const r=root.getBoundingClientRect();value.layout={left:r.left,top:r.top,width:r.width,height:r.height};}
    localStorage.setItem(STORY_PREF_KEY,JSON.stringify(value));
  }catch{}
}
const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!=null)node.textContent=text;return node;};
const input=(type,value="")=>{const node=document.createElement("input");node.type=type;if(type==="checkbox")node.checked=!!value;else node.value=value??"";return node;};
const textarea=(value="",rows=3)=>{const node=document.createElement("textarea");node.value=value??"";node.rows=rows;return node;};
const select=(options,value)=>{const node=document.createElement("select");for(const raw of options||[]){const [v,label]=Array.isArray(raw)?raw:[raw,raw],opt=document.createElement("option");opt.value=v;opt.textContent=label;if(String(v)===String(value))opt.selected=true;node.append(opt);}return node;};
const field=(label,control,hint="")=>{const wrap=el("label","z3h3-director-field"),copy=el("div");copy.append(el("b",null,label));if(hint)copy.append(el("small",null,hint));wrap.append(copy,control);return wrap;};
const button=(text,fn,cls="z3h3-director-btn",title="")=>{
  const node=el("button",cls,text);node.type="button";if(title)node.title=title;let pointerHandled=false;
  const invoke=async(event)=>{event?.preventDefault?.();event?.stopPropagation?.();try{await fn?.(event);}catch(error){console.error("MiniMax Director action failed",error);node.dataset.error="1";node.title=error?.message||String(error);setTimeout(()=>delete node.dataset.error,1500);}};
  node.addEventListener("pointerdown",event=>event.stopPropagation());
  node.addEventListener("pointerup",async event=>{if(event.button!==0)return;pointerHandled=true;await invoke(event);setTimeout(()=>{pointerHandled=false;},0);});
  node.addEventListener("click",async event=>{if(pointerHandled||event.detail>0){event.preventDefault();event.stopPropagation();return;}await invoke(event);});
  return node;
};
const activate=(node,fn)=>{
  if(!node)return node;let pointerHandled=false;
  const invoke=async(event)=>{event?.preventDefault?.();event?.stopPropagation?.();try{await fn?.(event);}catch(error){console.error("MiniMax Director interactive surface failed",error);node.dataset.error="1";node.title=error?.message||String(error);setTimeout(()=>delete node.dataset.error,1500);}};
  node.addEventListener("pointerdown",event=>event.stopPropagation());
  node.addEventListener("pointerup",async event=>{if(event.button!==0)return;pointerHandled=true;await invoke(event);setTimeout(()=>{pointerHandled=false;},0);});
  node.addEventListener("click",async event=>{if(pointerHandled||event.detail>0){event.preventDefault();event.stopPropagation();return;}await invoke(event);});
  return node;
};
const wireDetails=(details)=>{
  const summary=details?.querySelector?.(":scope > summary");if(!summary)return details;let pointerHandled=false;
  summary.addEventListener("pointerdown",event=>event.stopPropagation());
  summary.addEventListener("pointerup",event=>{if(event.button!==0)return;event.preventDefault();event.stopPropagation();pointerHandled=true;details.open=!details.open;setTimeout(()=>{pointerHandled=false;},0);});
  summary.addEventListener("click",event=>{if(pointerHandled||event.detail>0){event.preventDefault();event.stopPropagation();}});
  return details;
};
const escRe=value=>String(value??"").replace(/[.*+?^${}()|[\]\\]/g,"\\$&");
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
const clean=value=>String(value??"").replace(/\s+/g," ").trim();
const fmt=n=>`${Math.max(0,Number(n)||0).toFixed(Number(n)%1?2:1)}s`;
const MODE_COLORS={T2VA:"#8e99aa",I2VA:"#6d9fd1",L2VA:"#9186cb",FL2VA:"#d69b62",REF2VA:"#66b7aa",CLIP:"#6f7784"};
const CAMERA_MOVES=["holds steady","pushes in","pulls out","pans left","pans right","trucks left","trucks right","tilts up","tilts down","orbits clockwise","orbits counterclockwise","cranes up","cranes down"];
const FRAMINGS=["wide shot","medium-wide shot","medium shot","medium close-up","close-up","extreme close-up","over-the-shoulder shot","low-angle shot","high-angle shot"];
const SPEEDS=["slow","medium","fast"];
const AMPLITUDES=["small","medium","large"];
const BEAT_TYPES=[["action","Action"],["dialogue","Dialogue"],["voiceover","Voiceover"],["sound","Sound cue"],["transition","Transition"],["lora_on","LoRA on"],["lora_off","LoRA off"]];
const EDIT_WORKFLOWS=[
  ["none","No edit workflow"],
  ["insertion","Insertion"],
  ["replacement","Replacement"],
  ["targeted_edit","Targeted edit"],
  ["relighting","Relighting"],
  ["performance_transfer","Performance transfer"],
  ["continuation","Continuation"],
];

export function directorFor(segment){
  if(!segment||segment.kind==="clip")return null;
  const current=segment.director&&typeof segment.director==="object"&&!Array.isArray(segment.director)?segment.director:{};
  current.mode_intent=["auto","T2VA","I2VA","L2VA","FL2VA","REF2VA"].includes(current.mode_intent)?current.mode_intent:"auto";
  current.beats=Array.isArray(current.beats)?current.beats:[];
  current.camera_points=Array.isArray(current.camera_points)?current.camera_points:[];
  current.camera_settings=current.camera_settings&&typeof current.camera_settings==="object"&&!Array.isArray(current.camera_settings)?current.camera_settings:{stabilization:"auto",lens:"",depth:"",focus:"",custom:""};
  current.edit=current.edit&&typeof current.edit==="object"&&!Array.isArray(current.edit)?current.edit:{type:"none",target:"",change:"",protect_identity:true,protect_camera:true,protect_audio:true,protect_background:true};
  if(!EDIT_WORKFLOWS.some(([v])=>v===current.edit.type))current.edit.type="none";
  segment.director=current;return current;
}
function environmentBank(body){
  body.data.director_environments=Array.isArray(body.data.director_environments)?body.data.director_environments:[];
  return body.data.director_environments;
}
function activeEnvironment(body,director){return environmentBank(body).find(env=>env?.id===director?.environment_id)||null;}
function mention(source,handle){return new RegExp(`@${escRe(handle)}(?![A-Za-z0-9_-])`).test(String(source||""));}
function activeText(body,index){const global=String(body.data.prompt||""),seg=body.data.segments?.[index];return `${global}\n${String(seg?.prompt||"")}\n${String(seg?.director_prompt||"")}`;}
function subjectsForShot(body,index){return referencedSubjectsForShot(body,index);}
function assetsForShot(body,index){return effectiveAssetsForShot(body,index);}
function inferMode(body,index){return inferShotMode(body,index);}
function modeDetail(mode){return ({T2VA:"text only",I2VA:"first image",L2VA:"required last image",FL2VA:"first + last images",REF2VA:"full multimodal references",CLIP:"supplied footage"})[mode]||mode;}
function speakerId(body,handle){const index=(body.data.subjects||[]).findIndex(subject=>subject?.handle===handle);return index>=0?`S${index+1}`:"S1";}
function framePosition(point){const h=point.x<.34?"left":point.x>.66?"right":"center",v=point.y<.34?"upper":point.y>.66?"lower":"center";return h==="center"&&v==="center"?"center of frame":`${v==="center"?"":v+"-"}${h} of frame`;}
export function buildDirectorPrompt(body,index){
  const seg=body.data.segments?.[index],director=directorFor(seg);if(!seg||!director)return "";
  const lines=[];
  const environment=activeEnvironment(body,director);
  if(environment?.handles?.length){const handles=environment.handles.map(handle=>`@${String(handle).replace(/^@/,"")}`).join(", ");lines.push(`Environment continuity: ${environment.name||"the saved environment"} is guided by ${handles}. Preserve the same spatial layout, architecture, major furniture, material identity, and lighting anchors across this shot unless the prompt explicitly changes them.`);}
  const mediaTiming=director.timeline?.media&&typeof director.timeline.media==="object"?director.timeline.media:{};
  for(const [handleRaw,placement] of Object.entries(mediaTiming)){
    const handle=String(handleRaw||"").replace(/^@/,"");if(!handle||!placement||typeof placement!=="object")continue;
    const asset=[...(body.data.assets||[]),...(seg.assets||[])].find(row=>row?.handle===handle);if(!asset)continue;
    const start=clamp(placement.start,0,Number(seg.duration_s||S.DEFAULT_DURATION_S)),end=clamp(placement.end,start,Number(seg.duration_s||S.DEFAULT_DURATION_S));
    if(asset.kind==="image"){
      if(asset.role==="first_frame")lines.push(`Use @${handle} as the required opening frame. From ${start.toFixed(2)} to ${end.toFixed(2)} sec, preserve its visible identity, composition, and scene anchors as the shot begins.`);
      else if(asset.role==="last_frame")lines.push(`Use @${handle} as the required final frame. From ${start.toFixed(2)} to ${end.toFixed(2)} sec, transition toward its visible identity, composition, and scene anchors so the shot lands on that frame.`);
      else lines.push(`From ${start.toFixed(2)} to ${end.toFixed(2)} sec, use @${handle} as the active visual reference for the subject, scene, prop, style, or detail assigned to it.`);
      continue;
    }
    if(asset.kind==="video"&&asset.track!=="sound"){lines.push(`From ${start.toFixed(2)} to ${end.toFixed(2)} sec, use @${handle} as the motion/video reference while preserving the authored shot timing and requested camera behavior.`);continue;}
    if(asset.kind==="audio"||asset.track==="sound"){lines.push(`From ${start.toFixed(2)} to ${end.toFixed(2)} sec, use @${handle} as the audio reference or soundtrack cue, aligned to that interval.`);}
  }
  const camera=[...director.camera_points].sort((a,b)=>Number(a.t)-Number(b.t));
  for(const point of camera){const time=clamp(point.t,0,Number(seg.duration_s||S.DEFAULT_DURATION_S)),framing=point.framing||"medium shot",move=point.move||"holds steady",amp=point.amplitude||"small",speed=point.speed||"slow",position=framePosition(point);let text=`At ${time.toFixed(2)} sec, ${framing}; the camera ${move}`;if(move!=="holds steady")text+=` with ${amp} amplitude at ${speed} speed`;text+=`, settling the focal composition near the ${position}.`;lines.push(text);}
  const cameraSettings=director.camera_settings||{},cameraNotes=[];if(cameraSettings.stabilization&&cameraSettings.stabilization!=="auto")cameraNotes.push(`${cameraSettings.stabilization} stabilization`);if(clean(cameraSettings.lens))cameraNotes.push(`lens perspective: ${clean(cameraSettings.lens)}`);if(clean(cameraSettings.depth))cameraNotes.push(`depth of field: ${clean(cameraSettings.depth)}`);if(clean(cameraSettings.focus))cameraNotes.push(`focus behavior: ${clean(cameraSettings.focus)}`);if(clean(cameraSettings.custom))cameraNotes.push(clean(cameraSettings.custom));if(cameraNotes.length)lines.push(`Camera treatment: ${cameraNotes.join("; ")}.`);
  const beats=[...director.beats].sort((a,b)=>Number(a.t)-Number(b.t));
  for(const beat of beats){const time=clamp(beat.t,0,Number(seg.duration_s||S.DEFAULT_DURATION_S)),text=clean(beat.text),handle=String(beat.speaker||"").replace(/^@/,""),sid=speakerId(body,handle);if(!text&&!["lora_on","lora_off"].includes(beat.type))continue;
    if(beat.type==="dialogue"){lines.push(`At ${time.toFixed(2)} sec, ${handle?`@${handle} (${sid})`:"the speaker"} says: <d>[${beat.language||"English"}] ${text}</d>`);continue;}
    if(beat.type==="voiceover"){lines.push(`At ${time.toFixed(2)} sec, ${handle?`@${handle} (${sid})`:"the narrator"} says in an off-screen voiceover: <d>[${beat.language||"English"}] ${text}</d> while the corresponding on-screen character's lips remain completely closed.`);continue;}
    if(beat.type==="sound"){lines.push(`At ${time.toFixed(2)} sec, sound cue: ${text}`);continue;}
    if(beat.type==="transition"){lines.push(`At ${time.toFixed(2)} sec, ${text}`);continue;}
    if(beat.type==="lora_on"||beat.type==="lora_off"){const name=clean(beat.lora);if(name)lines.push(`At ${time.toFixed(2)} sec *${beat.type==="lora_off"?"-":""}{${name}}${text?` ${text}`:""}`);continue;}
    lines.push(`At ${time.toFixed(2)} sec, ${text}`);
  }
  const edit=director.edit||{};if(edit.type&&edit.type!=="none"){
    const protect=[];if(edit.protect_identity)protect.push("subject identity and appearance");if(edit.protect_camera)protect.push("existing camera motion and framing");if(edit.protect_audio)protect.push("existing dialogue, ambience, and timing");if(edit.protect_background)protect.push("unrequested background details");const preserved=protect.length?` Preserve ${protect.join(", ")}.`:"";
    const target=clean(edit.target)||"the referenced source",change=clean(edit.change)||"the requested change";
    const copy={
      insertion:`Ref2VA insertion workflow: insert ${change} into ${target}.${preserved}`,
      replacement:`Ref2VA replacement workflow: replace ${target} with ${change}.${preserved}`,
      targeted_edit:`Ref2VA targeted edit workflow: change only ${target}: ${change}.${preserved}`,
      relighting:`Ref2VA relighting workflow: relight ${target} so ${change}. Preserve geometry, performance, timing, and identity unless explicitly changed.${preserved}`,
      performance_transfer:`Ref2VA performance-transfer workflow: transfer the motion and performance from the referenced source video to ${target}; ${change}.${preserved}`,
      continuation:`Continuation workflow: continue naturally from the preceding shot with ${change}.${preserved}`,
    }[edit.type];if(copy)lines.push(copy);
  }
  return lines.join("\n").trim();
}
function quietPersist(body){
  if(!body?.data)return false;
  const raw=S.serializeData(body.data);
  if(body.dataWidget)body.dataWidget.value=raw;
  body.node.properties ||= {};persistCreatorBackup(body.node,raw);
  body.node.graph?.setDirtyCanvas?.(true,true);
  return true;
}
function updateDirectorPrompt(body,index,{notify=true,historyLabel="Edit Director"}={}){const seg=body.data.segments?.[index];if(!seg||seg.kind==="clip")return false;const next=buildDirectorPrompt(body,index);if(next)seg.director_prompt=next;else delete seg.director_prompt;if(notify)body.commitData?.(true,{historyLabel});else quietPersist(body);return true;}
function directorNotice(message,tone="good"){
  const root=activeDock?.root;if(!root?.isConnected)return false;let notice=root.querySelector?.(".z3h3-director-notice");if(!notice){notice=el("div","z3h3-director-notice");root.append(notice);}notice.textContent=String(message||"");notice.className=`z3h3-director-notice ${tone}`;notice.dataset.visible="1";clearTimeout(notice._hideTimer);notice._hideTimer=setTimeout(()=>{if(notice?.isConnected)delete notice.dataset.visible;},2600);return true;
}
function moveSegment(body,index,delta){const next=index+delta;if(index<0||next<0||next>=body.data.segments.length)return false;const [seg]=body.data.segments.splice(index,1);body.data.segments.splice(next,0,seg);body.target=next;body.commitData?.(true,{historyLabel:"Reorder storyboard shot"});body.syncPrompt?.(false);return true;}
function duplicateSegment(body,index){const seg=body.data.segments?.[index];if(!seg)return;const clone=seg.kind==="clip"?structuredClone(seg):S.duplicateSegment(seg);body.data.segments.splice(index+1,0,clone);body.target=index+1;body.commitData?.(true,{historyLabel:"Duplicate storyboard shot"});body.syncPrompt?.(false);}
function addGeneratedShot(body){const base=body.data.segments?.[Math.max(0,Number(body.target)||0)];body.data.segments.push(S.cloneSegment(base?.kind==="clip"?S.DEFAULT_SEGMENT():base));body.target=body.data.segments.length-1;body.commitData?.(true,{historyLabel:"Add storyboard shot"});body.syncPrompt?.(false);}
function deleteSegment(body,index){if(!confirm(`Delete timeline card ${index+1}?`))return;if(body.data.segments.length>1)body.data.segments.splice(index,1);else body.data.segments[0]=S.DEFAULT_SEGMENT();body.target=Math.max(0,Math.min(index-1,body.data.segments.length-1));body.commitData?.(true,{historyLabel:"Delete storyboard shot"});body.syncPrompt?.(false);}
function shotColor(mode){return MODE_COLORS[mode]||MODE_COLORS.T2VA;}
function routeText(body,index){const seg=body.data.segments?.[index];if(seg?.kind==="clip")return "CLIP";const mode=inferMode(body,index),checkpoint=String(seg?.checkpoint||"auto");return `${mode} · ${checkpoint==="auto"?(mode==="REF2VA"?"REF":"FL"):checkpoint.toUpperCase()}`;}
function counts(body,index){return referenceCounts(body,index);}
function localChecks(body){
  const checks=[];const add=(level,title,detail,index=null)=>checks.push({level,title,detail,index});
  for(const row of validateCreatorShots(body))add(row.level,`Shot ${Number(row.index)+1}: ${row.title}`,row.detail,row.index);
  body.data.segments.forEach((seg,index)=>{if(seg?.kind==="clip")return;const director=directorFor(seg),mode=inferMode(body,index),duration=Number(seg.duration_s||S.DEFAULT_DURATION_S),text=activeText(body,index);
    if(duration<4||duration>15)add("warn",`Shot ${index+1}: ${duration}s is outside the normal H3 single-generation range`,`MiniMax H3 is designed around 4–15 second generations; Creator can still assemble longer pieces from multiple cards.`,index);
    if(director?.edit?.type&&director.edit.type!=="none"&&!['REF2VA'].includes(mode)&&director.edit.type!=="continuation")add("warn",`Shot ${index+1}: ${director.edit.type.replaceAll("_"," ")} normally needs Ref2VA`,`Attach the source video/image as a reference so the edit has something to preserve and modify.`,index);
    if(text.length>7000)add("warn",`Shot ${index+1}: prompt source is very long`,`${text.length} characters before final structured rewrite; H3 prompt limits are finite, so review the resolved prompt.`,index);
    for(const beat of director?.beats||[]){if((beat.type==="dialogue"||beat.type==="voiceover")&&!clean(beat.text))add("warn",`Shot ${index+1}: empty ${beat.type} beat`,`Add spoken text or delete the beat.`,index);if((beat.type==="dialogue"||beat.type==="voiceover")&&!beat.speaker)add("warn",`Shot ${index+1}: ${beat.type} has no speaker`,`Choose a Cast member so the voice identity stays stable.`,index);}
  });
  try{const timing=timingSummary(body);for(const beat of timing.beats||[]){const match=(beat.text||"").match(/["“]([^"”]+)["”]/);if(match){const words=match[1].trim().split(/\s+/).filter(Boolean).length,estimate=words/2.55,window=Math.max(0,beat.end-beat.start);if(estimate>window+.25)add("warn","Dialogue may overrun a timing window",`${words} words need about ${estimate.toFixed(1)}s but this beat has ${window.toFixed(1)}s.`,beat.shot?beat.shot-1:null);}}}catch{}
  try{const audit=body.persistenceAudit?.();if(audit&&!audit.ok)add("warn","Creator save/reload audit needs attention",(audit.warnings||[audit.error||"Canonical state did not round-trip cleanly."]).join(" · "));}catch{}
  if(!checks.length)add("ok","Director check is clean","No obvious timing, routing, reference, camera, audio, or persistence conflicts were found.");return checks;
}

function renderCastMini(body,index,host){host.replaceChildren();const rows=subjectsForShot(body,index);if(!rows.length){host.append(el("span","z3h3-director-muted","No Cast mentioned"));return;}for(const subject of rows){const chip=el("button","z3h3-director-cast-chip");chip.type="button";chip.append(createSubjectAvatar(body,subject),el("span",null,subjectDisplayName(subject)));chip.title=`@${subject.handle}`;activate(chip,()=>openCastStudio(body,{edit:subject.handle}));host.append(chip);}}
function tabButton(label,id,state,render){const b=button(label,()=>{state.tab=id;render();},`z3h3-director-tab${state.tab===id?" active":""}`);return b;}

function renderTimelineTab(body,state,content,render){
  return renderStoryboardTimeline(body,state,content,{
    directorFor,inferMode,routeText,counts,subjectsForShot,assetsForShot,updateDirectorPrompt,quietPersist,localChecks,savePrefs:(state)=>saveStoryPrefs(state,activeDock?.root),
    addGeneratedShot,duplicateSegment,deleteSegment,moveSegment,openBeatEditor,openCameraPointEditor,saveDirectorCameraPoint,openTimingInspector,
  },render);
}

export function upsertDirectorBeat(segment,draft){
  const director=directorFor(segment);if(!director)throw new Error("Timed beats can only be added to generated H3 shots.");
  const duration=Math.max(.2,Number(segment.duration_s)||S.DEFAULT_DURATION_S),data={...draft};data.id=String(data.id||`beat_${Date.now()}_${Math.random().toString(36).slice(2,7)}`);data.t=clamp(data.t,0,duration);data.type=BEAT_TYPES.some(([value])=>value===data.type)?data.type:"action";data.speaker=String(data.speaker||"").replace(/^@/,"");data.language=clean(data.language)||"English";data.text=clean(data.text);data.lora=String(data.lora||"");
  if(["lora_on","lora_off"].includes(data.type)){if(!data.lora)throw new Error("Choose the LoRA this timed cue controls.");}
  else if(!data.text)throw new Error(data.type==="dialogue"||data.type==="voiceover"?"Write the spoken line before adding this beat.":"Write what happens at this beat.");
  const hit=director.beats.findIndex(beat=>beat?.id===data.id);if(hit>=0)director.beats[hit]=data;else director.beats.push(data);director.beats.sort((a,b)=>Number(a.t)-Number(b.t));return data;
}

export function saveDirectorBeat(body,index,draft,{historyLabel="Add storyboard beat"}={}){
  const segment=body?.data?.segments?.[index];if(!segment||segment.kind==="clip")throw new Error("Choose a generated H3 shot before adding a beat.");const saved=upsertDirectorBeat(segment,draft);updateDirectorPrompt(body,index,{historyLabel});const canonical=body?.data?.segments?.[index]?.director?.beats?.find(beat=>beat?.id===saved.id);if(!canonical)throw new Error("The beat did not survive workflow persistence. Nothing was queued or discarded.");return canonical;
}

export function openBeatEditor(body,index,existing,refresh,atTime=null){
  const seg=body.data.segments[index],director=directorFor(seg);if(!director)throw new Error("Choose a generated H3 shot before adding a beat.");const editing=!!existing,back=el("div","z3h3-backdrop z3h3-beat-backdrop"),box=el("div","z3h3-modal small z3h3-beat-editor"),head=el("div","z3h3-modal-head"),mount=el("div","z3h3-modal-body"),close=()=>back.remove();const heading=el("div");heading.append(el("span","z3h3-editor-kicker",editing?"TIMELINE EVENT":"NEW TIMELINE EVENT"),el("b",null,editing?"Edit timed beat":"Add timed beat"),el("small",null,`Shot ${index+1} · ${fmt(seg.duration_s||S.DEFAULT_DURATION_S)} · saved into the real Creator workflow`));const closeButton=el("button","z3h3-btn","Close");closeButton.type="button";closeButton.addEventListener("click",close);head.append(heading,el("div","z3h3-spacer"),closeButton);box.append(head,mount);back.append(box);document.body.append(back);back.addEventListener("mousedown",e=>{if(e.target===back)close();});const data=existing?structuredClone(existing):{id:`beat_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,t:Number.isFinite(Number(atTime))?clamp(Number(atTime),0,Number(seg.duration_s||6)):Math.min(Number(seg.duration_s||6)-.5,Math.max(.5,Number(seg.duration_s||6)/2)),type:"action",text:"",speaker:"",language:"English",lora:""};
  const form=el("form","z3h3-beat-form"),at=input("number",data.t),type=select(BEAT_TYPES,data.type),speaker=select([["","— no speaker —"],...(body.data.subjects||[]).map(s=>[s.handle,subjectDisplayName(s)])],data.speaker||""),language=input("text",data.language||"English"),text=textarea(data.text||"",4),lora=select([["","— choose active LoRA —"],...(body.data.loras||[]).filter(l=>l.enabled!==false).map(l=>[l.name,String(l.name||"").split(/[\\/]/).pop()])],data.lora||"");at.min=0;at.max=Number(seg.duration_s||S.DEFAULT_DURATION_S);at.step=.1;text.placeholder="Describe the action, spoken line, sound, or transition…";
  const speakerField=field("Speaker",speaker,"Used for Dialogue and Voiceover."),languageField=field("Language",language),loraField=field("LoRA",lora,"Timed LoRA cues become real chained pass boundaries."),preview=el("div","z3h3-beat-preview"),status=el("div","z3h3-note","Nothing changes until Add to timeline is pressed.");const updateVisibility=()=>{speakerField.hidden=!["dialogue","voiceover"].includes(type.value);languageField.hidden=!["dialogue","voiceover"].includes(type.value);loraField.hidden=!type.value.startsWith("lora_");const label=BEAT_TYPES.find(([value])=>value===type.value)?.[1]||"Beat",copy=clean(text.value)||"Waiting for direction…";preview.replaceChildren(el("span",`beat-type type-${type.value}`,label),el("b",null,`${Number(at.value||0).toFixed(2)} sec`),el("small",null,copy));};for(const control of [type,at,speaker,text])for(const eventName of ["input","change"])control.addEventListener(eventName,updateVisibility);updateVisibility();
  const actions=el("div","z3h3-beat-actions"),cancel=el("button","z3h3-btn","Cancel"),submit=el("button","z3h3-btn primary",editing?"Save beat":"Add to timeline");cancel.type="button";submit.type="submit";cancel.addEventListener("click",close);actions.append(cancel);if(editing){const remove=el("button","z3h3-btn danger","Delete beat");remove.type="button";remove.addEventListener("click",()=>{const live=directorFor(body.data.segments[index]);live.beats=live.beats.filter(beat=>beat.id!==data.id);updateDirectorPrompt(body,index,{historyLabel:"Delete storyboard beat"});directorNotice("Beat removed from the timeline.","warn");close();refresh?.();});actions.append(remove);}actions.append(submit);
  form.addEventListener("submit",event=>{event.preventDefault();event.stopPropagation();status.className="z3h3-note";status.textContent="Saving into the workflow…";submit.disabled=true;try{data.t=Number(at.value);data.type=type.value;data.speaker=speaker.value;data.language=language.value;data.text=text.value;data.lora=lora.value;const saved=saveDirectorBeat(body,index,data,{historyLabel:editing?"Edit storyboard beat":"Add storyboard beat"});status.textContent=`Saved ${String(saved.type).replaceAll("_"," ")} at ${Number(saved.t).toFixed(2)} sec.`;status.className="z3h3-note good";form.dataset.saved="1";refresh?.();directorNotice(`Beat added · ${Number(saved.t).toFixed(2)} sec · ${String(saved.type).replaceAll("_"," ")}`);setTimeout(close,260);}catch(error){submit.disabled=false;status.textContent=error.message||String(error);status.className="z3h3-note warn";form.dataset.saved="0";}});
  form.append(preview,el("div","z3h3-beat-form-grid"));form.lastChild.append(field("Time",at,"Frame-snapped placement inside this shot."),field("Type",type),speakerField,languageField,loraField);form.append(field("Direction / line",text,"This becomes real H3 Director prompt text."),status,actions);mount.append(form);setTimeout(()=>text.focus?.({preventScroll:true}),0);return back;
}

export function upsertDirectorCameraPoint(segment,draft){
  const director=directorFor(segment);if(!director)throw new Error("Camera points can only be added to generated H3 shots.");const duration=Math.max(.2,Number(segment.duration_s)||S.DEFAULT_DURATION_S),point={...draft};point.id=String(point.id||`cam_${Date.now()}_${Math.random().toString(36).slice(2,7)}`);point.t=clamp(point.t,0,duration);point.x=clamp(point.x,.02,.98);point.y=clamp(point.y,.02,.98);point.framing=FRAMINGS.includes(point.framing)?point.framing:"medium shot";point.move=CAMERA_MOVES.includes(point.move)?point.move:"holds steady";point.amplitude=AMPLITUDES.includes(point.amplitude)?point.amplitude:"small";point.speed=SPEEDS.includes(point.speed)?point.speed:"slow";const hit=director.camera_points.findIndex(row=>row?.id===point.id);if(hit>=0)director.camera_points[hit]=point;else director.camera_points.push(point);director.camera_points.sort((a,b)=>Number(a.t)-Number(b.t));return point;
}
export function saveDirectorCameraPoint(body,index,draft,{historyLabel="Add camera point"}={}){
  const segment=body?.data?.segments?.[index];if(!segment||segment.kind==="clip")throw new Error("Choose a generated H3 shot before editing its camera path.");const saved=upsertDirectorCameraPoint(segment,draft);updateDirectorPrompt(body,index,{historyLabel});const canonical=body?.data?.segments?.[index]?.director?.camera_points?.find(point=>point?.id===saved.id);if(!canonical)throw new Error("The camera point did not survive workflow persistence.");return canonical;
}

export function openCameraPointEditor(body,index,existing,refresh){
  const seg=body.data.segments[index];if(!seg||seg.kind==="clip")throw new Error("Choose a generated H3 shot before editing its camera path.");const editing=!!existing?.id,data=existing?structuredClone(existing):{t:0,x:.5,y:.5,framing:"medium shot",move:"holds steady",amplitude:"small",speed:"slow"},back=el("div","z3h3-backdrop z3h3-camera-edit-backdrop"),box=el("div","z3h3-modal small z3h3-camera-editor"),head=el("div","z3h3-modal-head"),mount=el("div","z3h3-modal-body"),close=()=>back.remove(),heading=el("div");heading.append(el("span","z3h3-editor-kicker","CAMERA KEYPOINT"),el("b",null,editing?"Edit camera point":"Add camera point"),el("small",null,`Shot ${index+1} · timing, framing, movement, and composition remain editable`));const closeButton=el("button","z3h3-btn","Close");closeButton.type="button";closeButton.addEventListener("click",close);head.append(heading,el("div","z3h3-spacer"),closeButton);box.append(head,mount);back.append(box);document.body.append(back);back.addEventListener("mousedown",event=>{if(event.target===back)close();});
  const form=el("form","z3h3-camera-edit-form"),time=input("number",data.t),framing=select(FRAMINGS.map(value=>[value,value]),data.framing),move=select(CAMERA_MOVES.map(value=>[value,value]),data.move),amp=select(AMPLITUDES.map(value=>[value,value]),data.amplitude),speed=select(SPEEDS.map(value=>[value,value]),data.speed),x=input("range",Number(data.x??.5)*100),y=input("range",Number(data.y??.5)*100),readout=el("div","z3h3-camera-edit-readout"),status=el("div","z3h3-note","Edit freely; the main Creator is unchanged until Save camera point."),stage=el("div","z3h3-camera-edit-mini-stage");time.min=0;time.max=Number(seg.duration_s||S.DEFAULT_DURATION_S);time.step=.1;x.min=2;x.max=98;x.step=1;y.min=2;y.max=98;y.step=1;const dot=el("i","z3h3-camera-edit-mini-dot");stage.append(dot);const updatePreview=()=>{dot.style.left=`${x.value}%`;dot.style.top=`${y.value}%`;readout.textContent=`${Number(time.value||0).toFixed(2)} sec · ${framing.value} · ${move.value}${move.value!=="holds steady"?` · ${amp.value}/${speed.value}`:""}`;};for(const control of [time,framing,move,amp,speed,x,y])for(const eventName of ["input","change"])control.addEventListener(eventName,updatePreview);updatePreview();
  const actions=el("div","z3h3-beat-actions"),cancel=el("button","z3h3-btn","Cancel"),submit=el("button","z3h3-btn primary",editing?"Save camera point":"Add camera point");cancel.type="button";submit.type="submit";cancel.addEventListener("click",close);actions.append(cancel);if(editing){const remove=el("button","z3h3-btn danger","Delete point");remove.type="button";remove.addEventListener("click",()=>{const live=directorFor(body.data.segments[index]);live.camera_points=live.camera_points.filter(point=>point.id!==data.id);updateDirectorPrompt(body,index,{historyLabel:"Delete camera point"});directorNotice("Camera point removed.","warn");close();refresh?.();});actions.append(remove);}actions.append(submit);form.addEventListener("submit",event=>{event.preventDefault();event.stopPropagation();submit.disabled=true;try{const saved=saveDirectorCameraPoint(body,index,{...data,t:Number(time.value),framing:framing.value,move:move.value,amplitude:amp.value,speed:speed.value,x:Number(x.value)/100,y:Number(y.value)/100},{historyLabel:editing?"Edit camera point":"Add camera point"});status.textContent=`Saved camera point at ${Number(saved.t).toFixed(2)} sec.`;status.className="z3h3-note good";form.dataset.saved="1";refresh?.();directorNotice(`Camera point saved · ${Number(saved.t).toFixed(2)} sec · ${saved.framing}`);setTimeout(close,260);}catch(error){submit.disabled=false;status.textContent=error.message||String(error);status.className="z3h3-note warn";form.dataset.saved="0";}});form.append(stage,readout,el("div","z3h3-camera-edit-grid"));form.lastChild.append(field("Time",time),field("Framing",framing),field("Movement",move),field("Amplitude",amp),field("Speed",speed),field("Horizontal composition",x),field("Vertical composition",y));form.append(status,actions);mount.append(form);return back;
}

function renderReferencesTab(body,state,content,render){
  const seg=body.data.segments[state.index];if(!seg){return;}
  const canonicalHost=el("div","z3h3-director-canonical-host");renderCanonicalShotInspector(body,state.index,canonicalHost,{compact:true,onNavigate:(target)=>{if(target==="references")openReferenceWorkspace(body,{shotIndex:state.index});else if(target==="timing")openTimingInspector(body);}});content.append(canonicalHost);const mode=inferMode(body,state.index),director=directorFor(seg),top=el("section","z3h3-director-panel"),modeIntent=select([["auto","Auto"],["T2VA","T2VA"],["I2VA","I2VA"],["L2VA","L2VA"],["FL2VA","FL2VA"],["REF2VA","Ref2VA"]],director?.mode_intent||"auto");modeIntent.disabled=seg.kind==="clip";modeIntent.addEventListener("change",()=>{director.mode_intent=modeIntent.value;body.commitData?.();render();});const badge=el("span","z3h3-director-mode large",mode);badge.style.setProperty("--director-tone",shotColor(mode));const summary=el("div","z3h3-director-reference-summary");summary.append(badge,el("div",null));summary.lastChild.append(el("b",null,`Current route: ${mode}`),el("small",null,modeDetail(mode)));top.append(el("h3",null,"Guided H3 input setup"),summary,field("Mode intent",modeIntent,"This is a planning/check target. Actual H3 routing remains derived from the media you really connect, so the Director cannot lie about the payload."));
  const quick=el("div","z3h3-director-quick-grid");quick.append(button("T2VA · text only",()=>{director.mode_intent="T2VA";body.commitData?.();render();},"z3h3-director-mode-choice"),button("I2VA · choose start image",()=>{director.mode_intent="I2VA";body.commitData?.();body.switchTarget?.(state.index);body.openMedia?.("input",{defaultRole:"first_frame",acceptKinds:["image"],targetIndex:state.index});},"z3h3-director-mode-choice"),button("L2VA · choose final image",()=>{director.mode_intent="L2VA";body.commitData?.();body.switchTarget?.(state.index);body.openMedia?.("input",{defaultRole:"last_frame",acceptKinds:["image"],targetIndex:state.index});},"z3h3-director-mode-choice"),button("FL2VA · start + final",()=>{director.mode_intent="FL2VA";body.commitData?.();body.switchTarget?.(state.index);body.openMedia?.("input",{defaultRole:"first_frame",acceptKinds:["image"],targetIndex:state.index});},"z3h3-director-mode-choice"),button("Ref2VA · add reference",()=>{director.mode_intent="REF2VA";body.commitData?.();body.switchTarget?.(state.index);body.openMedia?.("input",{defaultRole:"reference",targetIndex:state.index});},"z3h3-director-mode-choice"));top.append(quick);content.append(top);
  if(seg.kind==="clip")return;
  const reusable=el("section","z3h3-director-panel"),actions=el("div","z3h3-director-toolbar");actions.append(button("Reference Manager",()=>openReferenceWorkspace(body,{shotIndex:state.index}),"z3h3-director-btn primary"),button("Cast Studio",()=>body.openCast?.(),"z3h3-director-btn"),button("Pick location",()=>{body.switchTarget?.(state.index);body.openScenePicker?.("location");},"z3h3-director-btn"),button("Start frame",()=>{body.switchTarget?.(state.index);body.openMedia?.("input",{defaultRole:"first_frame",acceptKinds:["image"],targetIndex:state.index});},"z3h3-director-btn","Attach the I2VA / FL2VA first frame"),button("End frame",()=>{body.switchTarget?.(state.index);body.openMedia?.("input",{defaultRole:"last_frame",acceptKinds:["image"],targetIndex:state.index});},"z3h3-director-btn","Attach the L2VA / FL2VA final frame"),button("Add reference media",()=>{body.switchTarget?.(state.index);body.openMedia?.("input",{defaultRole:"reference",targetIndex:state.index});},"z3h3-director-btn primary"),button("Add voice/audio ref",()=>body.openMedia?.("input",{defaultRole:"reference",defaultTakes:"voice",acceptKinds:["audio","video"],target:"global"}),"z3h3-director-btn"),button("Map voice to Cast",()=>openVoiceMapper(body,state.index,render),"z3h3-director-btn"),button("Grab local video frame",()=>openFrameGrabber(body,state.index,render),"z3h3-director-btn"));reusable.append(el("h3",null,"Reusable people, environments, voices & continuity"),actions);
  const environments=environmentBank(body),environmentSelect=select([["","— no saved environment set —"],...environments.map(env=>[env.id,`${env.name} · ${(env.handles||[]).length} view${(env.handles||[]).length===1?"":"s"}`])],director?.environment_id||"");environmentSelect.addEventListener("change",()=>{director.environment_id=environmentSelect.value;updateDirectorPrompt(body,state.index);render();});const envTools=el("div","z3h3-director-toolbar");envTools.append(button("Save environment set…",()=>openEnvironmentEditor(body,state.index,null,render),"z3h3-director-btn"));if(director?.environment_id)envTools.append(button("Edit set…",()=>openEnvironmentEditor(body,state.index,director.environment_id,render),"z3h3-director-btn"));envTools.append(button("Add global environment views",()=>body.openMedia?.("input",{defaultRole:"reference",acceptKinds:["image"],target:"global"}),"z3h3-director-btn"));reusable.append(field("Reusable environment set",environmentSelect,"A named multi-view image bank. Director cites the selected views in the shot so Ref2VA sees them."),envTools);
  const location=seg.scene_palette?.location||body.data.scene_palette?.location,locationRow=el("div","z3h3-director-env-row");locationRow.append(el("div",null),button(location?"Change location":"Pick location",()=>{body.switchTarget?.(state.index);body.openScenePicker?.("location");},"z3h3-director-btn"));locationRow.firstChild.append(el("small",null,"ENVIRONMENT"),el("b",null,location?.title||"No semantic location selected"));reusable.append(locationRow);
  const cast=el("div","z3h3-director-reference-cast");renderCastMini(body,state.index,cast);reusable.append(cast);
  const refs=el("div","z3h3-director-ref-list"),assets=assetsForShot(body,state.index);if(!assets.length)refs.append(el("div","z3h3-director-empty","No H3 media references are active on this shot."));for(const asset of assets){const row=el("div","z3h3-director-ref-row"),thumb=el("div","z3h3-director-ref-thumb"),url=body.assetPreviewUrl?.(asset)||"";if(url)thumb.style.backgroundImage=`url("${String(url).replaceAll('"','%22')}")`;else thumb.textContent=asset.kind==="audio"?"♪":asset.kind==="video"?"▶":"▧";const copy=el("div");copy.append(el("b",null,`@${asset.handle}`),el("small",null,`${asset._scope} · ${asset.kind} · ${String(asset.role||"reference").replaceAll("_"," ")}${asset.takes&&asset.takes!=="full"?` · ${asset.takes}`:""}`));row.append(thumb,copy,button("Edit",()=>body.openAsset?.(body.assetByHandle?.(asset.handle)||asset),"z3h3-director-btn mini"));refs.append(row);}reusable.append(refs);
  const continuity=el("div","z3h3-director-continuity"),cont=input("checkbox",seg.continue),conta=input("checkbox",seg.continue_audio);cont.disabled=conta.disabled=state.index===0;cont.addEventListener("change",()=>{seg.continue=cont.checked;body.commitData?.();render();});conta.addEventListener("change",()=>{seg.continue_audio=conta.checked;body.commitData?.();render();});continuity.append(field("Continue picture from previous shot",cont),field("Continue audio across cut",conta));reusable.append(continuity);content.append(reusable);
}

function openVoiceMapper(body,index,refresh){
  const back=el("div","z3h3-backdrop"),box=el("div","z3h3-modal small"),head=el("div","z3h3-modal-head"),mount=el("div","z3h3-modal-body"),close=()=>back.remove();head.append(el("div",null,"Map reusable voice to Cast"),el("div","z3h3-spacer"),button("Close",close,"z3h3-btn"));box.append(head,mount);back.append(box);document.body.append(back);back.addEventListener("mousedown",e=>{if(e.target===back)close();});const subjects=body.data.subjects||[],subject=select([["","— choose Cast member —"],...subjects.map(row=>[row.handle,subjectDisplayName(row)])],subjectsForShot(body,index)[0]?.handle||""),pool=(body.data.assets||[]).filter(asset=>asset?.role==="reference"&&(asset.kind==="audio"||asset.kind==="video")),voice=select([["","— no mapped voice —"],...pool.map(asset=>[asset.handle,`@${asset.handle} · ${String(asset.filename||"").split(/[\/]/).pop()}`])],"");const sync=()=>{const row=subjects.find(item=>item.handle===subject.value);voice.value=row?.voice||"";};subject.addEventListener("change",sync);sync();const save=()=>{const row=subjects.find(item=>item.handle===subject.value);if(!row)throw new Error("Choose a Cast member");if(voice.value){row.voice=voice.value;const asset=(body.data.assets||[]).find(item=>item.handle===voice.value);if(asset?.kind==="video")asset.track="sound";}else delete row.voice;body.commitData?.();close();refresh();};mount.append(el("div","z3h3-note","Voice mapping is project/workflow state, not part of the reusable Cast preset. Global audio/video references can be reused by the same character in every shot."),field("Cast member",subject),field("Global voice reference",voice),el("div","z3h3-tabs"));mount.lastChild.append(button("Save voice mapping",save,"z3h3-btn primary"),button("Add global audio/video…",()=>body.openMedia?.("input",{defaultRole:"reference",defaultTakes:"voice",acceptKinds:["audio","video"],target:"global"}),"z3h3-btn"));
}

function openEnvironmentEditor(body,index,environmentId,refresh){
  const bank=environmentBank(body),existing=bank.find(env=>env.id===environmentId)||null,back=el("div","z3h3-backdrop"),box=el("div","z3h3-modal small"),head=el("div","z3h3-modal-head"),mount=el("div","z3h3-modal-body"),close=()=>back.remove();head.append(el("div",null,existing?"Edit reusable environment":"Save reusable environment"),el("div","z3h3-spacer"),button("Close",close,"z3h3-btn"));box.append(head,mount);back.append(box);document.body.append(back);back.addEventListener("mousedown",e=>{if(e.target===back)close();});const name=input("text",existing?.name||""),note=input("text",existing?.note||""),images=(body.data.assets||[]).filter(asset=>asset?.kind==="image"&&asset.role==="reference"),chosen=new Set(existing?.handles||[]),list=el("div","z3h3-director-env-pick-list");for(const asset of images){const row=el("label","z3h3-director-env-pick"),check=input("checkbox",chosen.has(asset.handle)),thumb=el("div","z3h3-director-ref-thumb"),url=body.assetPreviewUrl?.(asset)||"";if(url)thumb.style.backgroundImage=`url("${String(url).replaceAll('"','%22')}")`;check.addEventListener("change",()=>{check.checked?chosen.add(asset.handle):chosen.delete(asset.handle);});row.append(check,thumb,el("span",null,`@${asset.handle} · ${String(asset.filename||"").split(/[\/]/).pop()}`));list.append(row);}if(!images.length)list.append(el("div","z3h3-director-empty","Add one or more Global image references first. Global views can be reused by every shot without duplicating files."));const save=()=>{const title=name.value.trim();if(!title)throw new Error("Give the environment a name");if(!chosen.size)throw new Error("Choose at least one environment view");const record={id:existing?.id||`env_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,name:title,note:note.value.trim(),handles:[...chosen]};const pos=bank.findIndex(env=>env.id===record.id);if(pos>=0)bank[pos]=record;else bank.push(record);const director=directorFor(body.data.segments[index]);director.environment_id=record.id;updateDirectorPrompt(body,index);close();refresh();};mount.append(field("Environment name",name),field("Notes",note,"Kitchen layout, hotel suite, rooftop, recurring set…"),el("div","z3h3-director-label","Global reference views"),list);const envActions=el("div","z3h3-tabs");envActions.append(button("Save environment",save,"z3h3-btn primary"));if(existing)envActions.append(button("Delete set",()=>{const pos=bank.findIndex(env=>env.id===existing.id);if(pos>=0)bank.splice(pos,1);for(const seg of body.data.segments||[]){if(seg?.director?.environment_id===existing.id){seg.director.environment_id="";updateDirectorPrompt(body,body.data.segments.indexOf(seg),{notify:false});}}body.commitData?.();close();refresh();},"z3h3-btn danger"));mount.append(envActions);
}

function openFrameGrabber(body,index,refresh){
  const back=el("div","z3h3-backdrop"),box=el("div","z3h3-modal small"),head=el("div","z3h3-modal-head"),mount=el("div","z3h3-modal-body"),close=()=>back.remove();head.append(el("div",null,"Local video frame grabber"),el("div","z3h3-spacer"),button("Close",close,"z3h3-btn"));box.append(head,mount);back.append(box);document.body.append(back);back.addEventListener("mousedown",e=>{if(e.target===back)close();});const picker=input("file");picker.accept="video/*";const video=document.createElement("video");video.controls=true;video.className="z3h3-director-frame-video";const at=input("number",0);at.min=0;at.step=.01;const role=select([["reference","Reference image"],["first_frame","Start frame"],["last_frame","End frame"]],"reference"),status=el("div","z3h3-note","Choose a local video. Nothing is uploaded until you capture one PNG into ComfyUI input.");let url="";picker.addEventListener("change",()=>{if(url)URL.revokeObjectURL(url);const file=picker.files?.[0];if(!file)return;url=URL.createObjectURL(file);video.src=url;video.addEventListener("loadedmetadata",()=>{at.max=video.duration||0;status.textContent=`${file.name} · ${Number(video.duration||0).toFixed(2)}s`;},{once:true});});at.addEventListener("change",()=>{if(video.src)video.currentTime=clamp(at.value,0,video.duration||0);});
  const capture=async()=>{if(!video.videoWidth)throw new Error("Load a video first");video.currentTime=clamp(at.value,0,video.duration||0);await new Promise(resolve=>video.addEventListener("seeked",resolve,{once:true}));const canvas=document.createElement("canvas");canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext("2d").drawImage(video,0,0);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/png"));if(!blob)throw new Error("Could not encode frame");const base=(picker.files?.[0]?.name||"video").replace(/\.[^.]+$/,'').replace(/[^A-Za-z0-9_-]+/g,'_').slice(0,60),file=new File([blob],`${base}_frame_${Number(at.value).toFixed(2).replace('.','_')}.png`,{type:"image/png"}),uploaded=await H.uploadFile(file,"z3_minimax_creator/frames");const previous=body.target;body.target=index;const asset=body.attach?.(uploaded,role.value);body.target=previous;if(asset){status.textContent=`Captured and attached @${asset.handle} as ${role.value.replaceAll('_',' ')}.`;status.className="z3h3-note good";}refresh?.();};mount.append(field("Local video",picker),video,field("Time (seconds)",at),field("Use captured frame as",role),button("Capture PNG + attach",capture,"z3h3-btn primary"),status);
}

function renderCameraTab(body,state,content,render){
  const seg=body.data.segments[state.index];if(!seg||seg.kind==="clip"){content.append(el("div","z3h3-director-empty","Camera Builder applies to generated H3 shots."));return;}const director=directorFor(seg),panel=el("section","z3h3-director-panel z3h3-camera-workbench"),head=el("div","z3h3-director-section-head"),title=el("div");title.append(el("span","z3h3-editor-kicker","SHOT CAMERA DESK"),el("b",null,"Visual Camera Builder"),el("small",null,"Place a keypoint, drag its composition, then click it anytime to edit timing, framing, movement, amplitude, or speed."));const headTools=el("div","z3h3-director-toolbar");headTools.append(button("+ Center point",()=>openCameraPointEditor(body,state.index,{t:Math.min(Number(seg.duration_s||6),Math.max(0,(director.camera_points.at(-1)?.t||-1)+1)),x:.5,y:.5,framing:"medium shot",move:"holds steady",amplitude:"small",speed:"slow"},render),"z3h3-director-btn primary"),button("Clear path",()=>{if(!director.camera_points.length)return;if(!confirm("Clear every camera point on this shot?"))return;director.camera_points=[];updateDirectorPrompt(body,state.index,{historyLabel:"Clear camera path"});directorNotice("Camera path cleared.","warn");render();},"z3h3-director-btn danger"));head.append(title,headTools);panel.append(head);
  const tool=el("div","z3h3-director-camera-tools"),time=input("number",Math.min(Number(seg.duration_s||6),Math.max(0,(director.camera_points.at(-1)?.t||0)+1))),framing=select(FRAMINGS.map(v=>[v,v]),"medium shot"),move=select(CAMERA_MOVES.map(v=>[v,v]),"pushes in"),amp=select(AMPLITUDES.map(v=>[v,v]),"small"),speed=select(SPEEDS.map(v=>[v,v]),"slow");time.min=0;time.max=Number(seg.duration_s||S.DEFAULT_DURATION_S);time.step=.1;tool.append(field("Insert time",time),field("Framing",framing),field("Movement",move),field("Amplitude",amp),field("Speed",speed));panel.append(el("div","z3h3-camera-insert-note","CLICK EMPTY FRAME SPACE TO INSERT · CLICK A NUMBERED POINT TO EDIT · DRAG A POINT TO RECOMPOSE"),tool);
  const workspace=el("div","z3h3-camera-workspace"),stage=el("div","z3h3-director-camera-stage");stage.innerHTML='<i class="v one"></i><i class="v two"></i><i class="h one"></i><i class="h two"></i><span class="frame-label">H3 COMPOSITION FIELD · RULE OF THIRDS</span>';
  const addPoint=(x,y)=>{const saved=saveDirectorCameraPoint(body,state.index,{t:clamp(time.value,0,Number(seg.duration_s||S.DEFAULT_DURATION_S)),x:clamp(x,.02,.98),y:clamp(y,.02,.98),framing:framing.value,move:move.value,amplitude:amp.value,speed:speed.value},{historyLabel:"Add camera point"});directorNotice(`Camera point added · ${Number(saved.t).toFixed(2)} sec`);render();};stage.addEventListener("pointerup",event=>{if(event.button!==0||event.target.closest?.(".z3h3-director-camera-point"))return;event.preventDefault();event.stopPropagation();const rect=stage.getBoundingClientRect();addPoint((event.clientX-rect.left)/rect.width,(event.clientY-rect.top)/rect.height);});
  for(const point of director.camera_points){const dot=el("button",`z3h3-director-camera-point${state.cameraPointId===point.id?" active":""}`,String([...director.camera_points].sort((a,b)=>Number(a.t)-Number(b.t)).findIndex(row=>row.id===point.id)+1));dot.type="button";dot.style.left=`${clamp(point.x,0,1)*100}%`;dot.style.top=`${clamp(point.y,0,1)*100}%`;dot.title=`${fmt(point.t)} · ${point.framing} · ${point.move} · click to edit`;let dragging=false,moved=false;dot.addEventListener("pointerdown",event=>{event.preventDefault();event.stopPropagation();dragging=true;moved=false;dot.setPointerCapture?.(event.pointerId);});dot.addEventListener("pointermove",event=>{if(!dragging)return;const rect=stage.getBoundingClientRect(),nextX=clamp((event.clientX-rect.left)/rect.width,.02,.98),nextY=clamp((event.clientY-rect.top)/rect.height,.02,.98);if(Math.abs(nextX-point.x)>.006||Math.abs(nextY-point.y)>.006)moved=true;point.x=nextX;point.y=nextY;dot.style.left=`${point.x*100}%`;dot.style.top=`${point.y*100}%`;});dot.addEventListener("pointerup",event=>{if(!dragging)return;dragging=false;event.preventDefault();event.stopPropagation();dot.releasePointerCapture?.(event.pointerId);state.cameraPointId=point.id;if(moved){saveDirectorCameraPoint(body,state.index,point,{historyLabel:"Recompose camera point"});directorNotice(`Camera composition updated · ${Number(point.t).toFixed(2)} sec`);render();}else openCameraPointEditor(body,state.index,point,render);});stage.append(dot);}
  const sequence=el("aside","z3h3-camera-sequence"),sequenceHead=el("div","z3h3-camera-sequence-head");sequenceHead.append(el("div",null),el("span","z3h3-camera-count",`${director.camera_points.length} point${director.camera_points.length===1?"":"s"}`));sequenceHead.firstChild.append(el("b",null,"Camera sequence"),el("small",null,"The order H3 receives"));sequence.append(sequenceHead);const list=el("div","z3h3-director-camera-list");for(const [order,point] of [...director.camera_points].sort((a,b)=>Number(a.t)-Number(b.t)).entries()){const row=el("article",`z3h3-director-camera-row${state.cameraPointId===point.id?" active":""}`),indexBadge=el("span","z3h3-camera-order",String(order+1)),copy=el("div","z3h3-camera-row-copy"),actions=el("div","z3h3-camera-row-actions");copy.append(el("b",null,`${Number(point.t).toFixed(2)} sec · ${point.framing}`),el("small",null,`${point.move}${point.move!=="holds steady"?` · ${point.amplitude}/${point.speed}`:""} · ${Math.round(point.x*100)}% / ${Math.round(point.y*100)}%`));actions.append(button("Edit",()=>{state.cameraPointId=point.id;openCameraPointEditor(body,state.index,point,render);},"z3h3-director-btn mini primary"),button("×",()=>{const live=directorFor(body.data.segments[state.index]);live.camera_points=live.camera_points.filter(row=>row.id!==point.id);updateDirectorPrompt(body,state.index,{historyLabel:"Delete camera point"});directorNotice("Camera point removed.","warn");render();},"z3h3-director-btn mini danger","Delete point"));row.append(indexBadge,copy,actions);row.addEventListener("click",event=>{if(event.target.closest?.("button"))return;state.cameraPointId=point.id;openCameraPointEditor(body,state.index,point,render);});list.append(row);}if(!list.children.length)list.append(el("div","z3h3-director-empty","No explicit path yet. Click the composition field or add a center point. The normal CAMERA prompt category still works independently."));sequence.append(list);workspace.append(stage,sequence);panel.append(workspace);
  const settings=director.camera_settings||(director.camera_settings={stabilization:"auto",lens:"",depth:"",focus:"",custom:""}),advanced=document.createElement("details");advanced.className="z3h3-director-advanced";const summary=document.createElement("summary");summary.textContent="Advanced camera treatment · optional";advanced.append(summary);const grid=el("div","z3h3-director-camera-advanced-grid"),stabilization=select([["auto","Auto / unspecified"],["locked","Locked / tripod"],["smooth","Smooth stabilized"],["handheld","Handheld"],["floating","Floating / gimbal-like"]],settings.stabilization||"auto"),lens=input("text",settings.lens||""),depth=input("text",settings.depth||""),focus=input("text",settings.focus||""),custom=textarea(settings.custom||"",2);lens.placeholder="wide-angle, normal perspective, telephoto compression…";depth.placeholder="deep focus, shallow focus, moderate depth…";focus.placeholder="locks on @Orin_Vex, rack focus from foreground to @Orin_Vex…";custom.placeholder="Only camera-specific direction that is not represented above…";const saveCameraSettings=()=>{settings.stabilization=stabilization.value;settings.lens=lens.value.trim();settings.depth=depth.value.trim();settings.focus=focus.value.trim();settings.custom=custom.value.trim();updateDirectorPrompt(body,state.index);};for(const control of [stabilization,lens,depth,focus,custom])control.addEventListener("change",saveCameraSettings);grid.append(field("Stabilization",stabilization),field("Lens perspective",lens),field("Depth of field",depth),field("Focus / rack focus",focus),field("Custom camera note",custom));advanced.append(grid);wireDetails(advanced);panel.append(advanced);content.append(panel);
}

function renderEditTab(body,state,content,render){
  const seg=body.data.segments[state.index];if(!seg||seg.kind==="clip"){content.append(el("div","z3h3-director-empty","Ref2VA editing workflows apply to generated shots. Add the source clip as a reference on a generated card."));return;}const director=directorFor(seg),edit=director.edit,panel=el("section","z3h3-director-panel"),type=select(EDIT_WORKFLOWS,edit.type),target=input("text",edit.target||""),change=textarea(edit.change||"",4),protectIdentity=input("checkbox",edit.protect_identity!==false),protectCamera=input("checkbox",edit.protect_camera!==false),protectAudio=input("checkbox",edit.protect_audio!==false),protectBackground=input("checkbox",edit.protect_background!==false),status=el("div","z3h3-director-muted");target.placeholder="the subject in the foreground, the product, the jacket, the room lighting…";change.placeholder="Describe exactly what should change or what performance should be transferred…";
  const save=()=>{edit.type=type.value;edit.target=target.value.trim();edit.change=change.value.trim();edit.protect_identity=protectIdentity.checked;edit.protect_camera=protectCamera.checked;edit.protect_audio=protectAudio.checked;edit.protect_background=protectBackground.checked;if(edit.type==="continuation"&&state.index>0)seg.continue=true;updateDirectorPrompt(body,state.index);status.textContent="Saved into this shot's Director layer. The next queue receives it automatically.";status.className="z3h3-note good";render();};
  panel.append(el("h3",null,"Guided Ref2VA editing"),el("div","z3h3-director-muted","Insertion, replacement, targeted edits, relighting and performance transfer require source reference media. Continuation can inherit the previous shot directly."),field("Workflow",type),field("Target",target),field("Requested change / transfer",change));const protections=el("div","z3h3-director-protect-grid");protections.append(field("Preserve identity",protectIdentity),field("Preserve camera",protectCamera),field("Preserve audio/timing",protectAudio),field("Preserve background",protectBackground));panel.append(protections,el("div","z3h3-director-toolbar"));panel.lastChild.append(button("Add / inspect source references",()=>{body.switchTarget?.(state.index);body.openMedia?.("input",{defaultRole:"reference",acceptKinds:["video","image","audio"],targetIndex:state.index});},"z3h3-director-btn"),button("Save workflow",save,"z3h3-director-btn primary"),button("Clear workflow",()=>{director.edit={type:"none",target:"",change:"",protect_identity:true,protect_camera:true,protect_audio:true,protect_background:true};updateDirectorPrompt(body,state.index);render();},"z3h3-director-btn danger"));panel.append(status);content.append(panel);
  const guide=el("section","z3h3-director-panel compact"),cards=el("div","z3h3-director-workflow-grid");for(const [id,label] of EDIT_WORKFLOWS.filter(([id])=>id!=="none")){const card=button(label,()=>{edit.type=id;type.value=id;if(id==="continuation"&&state.index>0)seg.continue=true;save();},`z3h3-director-workflow-card${edit.type===id?" active":""}`);cards.append(card);}guide.append(el("h3",null,"Workflow shortcuts"),cards);content.append(guide);
}

async function renderChecksTab(body,state,content,render){
  const panel=el("section","z3h3-director-panel"),head=el("div","z3h3-director-section-head"),results=el("div","z3h3-director-check-list");head.append(el("div",null),button("Run backend check",async()=>{results.replaceChildren(el("div","z3h3-progress"));results.firstChild.append(el("i"));const local=localChecks(body);try{const seed=Number(body.widgets?.seed?.value),safeSeed=Number.isFinite(seed)&&seed>=0?Math.trunc(seed):0,preview=await H.promptPreview(S.normalizeData(structuredClone(body.data)),safeSeed,String(body.widgets?.processing_mode?.value||"entire text as one"),body.currentVariationIndex?.()||0);renderCheckRows(results,local);const pass=el("div","z3h3-director-check ok");pass.append(el("b",null,"Backend compile passed"),el("small",null,`${(preview.passes||[]).filter(p=>p.kind==="generation").length} generation pass(es) compiled with the current routing.`));results.append(pass);}catch(error){renderCheckRows(results,local);const fail=el("div","z3h3-director-check error");fail.append(el("b",null,"Backend compile failed"),el("small",null,error.message||String(error)));results.append(fail);}},"z3h3-director-btn primary"));head.firstChild.append(el("b",null,"Prompt & routing checks"),el("small",null,"Structure · timing · references · camera conflicts · audio · input routing"));panel.append(head);renderCheckRows(results,localChecks(body));panel.append(results);content.append(panel);
  const map=el("section","z3h3-director-panel compact"),grid=el("div","z3h3-director-route-grid");body.data.segments.forEach((seg,index)=>{const mode=inferMode(body,index),card=el("button",`z3h3-director-route-card${state.index===index?" active":""}`);card.type="button";card.style.setProperty("--director-tone",shotColor(mode));card.append(el("small",null,seg.kind==="clip"?`CLIP ${index+1}`:`SHOT ${index+1}`),el("b",null,mode),el("span",null,routeText(body,index)));activate(card,()=>{state.index=index;body.switchTarget?.(index);render();});grid.append(card);});map.append(el("h3",null,"Per-card H3 route"),grid);content.append(map);
}
function renderCheckRows(host,checks){host.replaceChildren();for(const check of checks){const row=el("div",`z3h3-director-check ${check.level}`);row.append(el("b",null,check.title),el("small",null,check.detail));host.append(row);}}

function buildDock(body){
  if(activeDock?.root?.isConnected)activeDock.close();
  const prefs=loadStoryPrefs(),root=el("section","z3h3-director-dock"),head=el("header","z3h3-director-head"),brand=el("div","z3h3-director-brand"),tabs=el("nav","z3h3-director-tabs"),content=el("div","z3h3-director-content"),state={tab:"timeline",index:body.target==="global"?0:Math.max(0,Number(body.target)||0),minimized:false,maximized:false,zoom:Number(prefs.zoom)||74,snap:prefs.snap||"seconds",inspector:prefs.inspector!==false,trackVisibility:{visual:true,video:true,audio:true,beats:true,camera:true,...(prefs.trackVisibility||{})},scrollLeft:Number(prefs.scrollLeft)||0,scrollTop:Number(prefs.scrollTop)||0,playhead:0};
  brand.append(el("b",null,"H3 Storyboard Timeline"),el("small",null,"drag media · trim on ruler · prompt per shot · exact compiled H3 prompt"));
  const minimize=button("—",()=>{state.minimized=!state.minimized;root.classList.toggle("minimized",state.minimized);minimize.textContent=state.minimized?"▣":"—";},"z3h3-director-head-btn","Minimize / restore"),maximize=button("□",()=>{state.maximized=!state.maximized;root.classList.toggle("maximized",state.maximized);maximize.textContent=state.maximized?"❐":"□";},"z3h3-director-head-btn","Maximize / restore"),closeBtn=button("×",()=>close(),"z3h3-director-head-btn","Close Director");
  head.append(brand,tabs,el("div","z3h3-spacer"),minimize,maximize,closeBtn);root.append(head,content);document.body.append(root);
  if(prefs.layout&&Number.isFinite(Number(prefs.layout.left))&&Number.isFinite(Number(prefs.layout.top))){const width=Math.min(window.innerWidth-12,Math.max(820,Number(prefs.layout.width)||1220)),height=Math.min(window.innerHeight-12,Math.max(320,Number(prefs.layout.height)||650));root.style.left=`${clamp(Number(prefs.layout.left),4,Math.max(4,window.innerWidth-width-4))}px`;root.style.top=`${clamp(Number(prefs.layout.top),4,Math.max(4,window.innerHeight-height-4))}px`;root.style.bottom="auto";root.style.width=`${width}px`;root.style.height=`${height}px`;root.style.transform="none";}
  const render=()=>{state.index=Math.max(0,Math.min(state.index,body.data.segments.length-1));saveStoryPrefs(state,root);tabs.replaceChildren(tabButton("Storyboard","timeline",state,render),tabButton("References","references",state,render),tabButton("Camera","camera",state,render),tabButton("Edit","edit",state,render),tabButton("Checks","checks",state,render));content.replaceChildren();if(state.tab==="timeline")renderTimelineTab(body,state,content,render);else if(state.tab==="references")renderReferencesTab(body,state,content,render);else if(state.tab==="camera")renderCameraTab(body,state,content,render);else if(state.tab==="edit")renderEditTab(body,state,content,render);else renderChecksTab(body,state,content,render);};
  let syncing=false,renderQueued=false;const scheduleRender=()=>{if(renderQueued||!root.isConnected)return;renderQueued=true;(globalThis.requestAnimationFrame||((fn)=>setTimeout(fn,0)))(()=>{renderQueued=false;if(!root.isConnected)return;syncing=true;try{render();}finally{syncing=false;}});};
  const unsubscribe=subscribeCreatorBody((candidate,reason)=>{if(candidate!==body||!root.isConnected)return;if(body.target!=="global"&&Number.isInteger(Number(body.target))){state.index=Math.max(0,Math.min(Number(body.target),body.data.segments.length-1));if(String(reason)==="target"){let at=0;for(let i=0;i<state.index;i++)at+=Math.max(.2,Number(body.data.segments[i]?.duration_s||S.DEFAULT_DURATION_S));state.playhead=at;}}if(["data","target","cast-sync","sidebar-action"].includes(String(reason)))scheduleRender();});
  const close=()=>{saveStoryPrefs(state,root);unsubscribe?.();root.remove();if(activeDock?.root===root)activeDock=null;};
  head.addEventListener("pointerdown",event=>{if(event.target?.closest?.("button,nav,input,select" )||state.maximized)return;const rect=root.getBoundingClientRect(),dx=event.clientX-rect.left,dy=event.clientY-rect.top;root.style.left=`${rect.left}px`;root.style.top=`${rect.top}px`;root.style.bottom="auto";root.style.transform="none";const move=e=>{root.style.left=`${clamp(e.clientX-dx,4,window.innerWidth-root.offsetWidth-4)}px`;root.style.top=`${clamp(e.clientY-dy,4,window.innerHeight-48)}px`;};const up=()=>{document.removeEventListener("pointermove",move,true);document.removeEventListener("pointerup",up,true);saveStoryPrefs(state,root);};document.addEventListener("pointermove",move,true);document.addEventListener("pointerup",up,true);});
  // Keep ComfyUI graph/canvas shortcuts and drag handlers from stealing interaction
  // from this floating DOM workspace. These listeners run in bubble phase, so
  // native controls and their own handlers still receive the event first.
  for(const eventName of ["pointerdown","pointerup","mousedown","mouseup","click","dblclick","wheel","keydown","keyup","keypress","input","change"]){
    root.addEventListener(eventName,event=>event.stopPropagation());
  }
  root.addEventListener("pointerup",event=>{const editor=event.target?.closest?.("textarea,input[type=text],input[type=search],input[type=number],[contenteditable=true]");if(editor&&!editor.disabled){try{editor.focus({preventScroll:true});}catch{editor.focus?.();}}});
  root.addEventListener("contextmenu",event=>{if(event.target?.closest?.("input,textarea,select,[contenteditable=true]"))event.stopPropagation();});
  render();activeDock={root,close,render,body};return activeDock;
}

export function openH3Director(body){if(activeDock?.root?.isConnected&&activeDock.body===body){activeDock.root.classList.remove("minimized");activeDock.root.focus?.();return activeDock.root;}return buildDock(body).root;}
export function closeH3Director(){activeDock?.close?.();}
