import * as H from "./z3_h3_api.js";

const SIDE_GAP = 10;
const DEFAULT_WIDTH = 470;

const el = (tag, cls, text) => { const node=document.createElement(tag);if(cls)node.className=cls;if(text!=null)node.textContent=text;return node; };
const button = (text, fn, cls="z3h3-btn") => { const node=el("button",cls,text);node.type="button";node.draggable=false;for(const name of ["pointerdown","mousedown","touchstart"])node.addEventListener(name,event=>event.stopPropagation(),{passive:name==="touchstart"});node.addEventListener("click",async event=>{event.preventDefault();event.stopPropagation();try{await fn?.(event)}catch(error){console.error("PreStage Image Lab action failed",error);node.dataset.error="1";node.title=error?.message||String(error);node.dispatchEvent(new CustomEvent("z3pre-action-error",{bubbles:true,detail:error}));setTimeout(()=>delete node.dataset.error,1600)}});return node; };
const select = (rows,value) => { const node=document.createElement("select");for(const [key,label] of rows){const option=document.createElement("option");option.value=key;option.textContent=label;option.selected=String(key)===String(value);node.append(option)}return node; };
const imageKey = (image) => [image?.type,image?.subfolder,image?.filename].join("|");
const label = (value) => String(value||"").split(/[\\/]/).pop()||"Saved image";

function savedPosition(body){const value=body?.node?.properties?.z3_prestage_sidecar_position;return value&&typeof value==="object"?{...value}:null}

export class PreStageImageSidecar {
  constructor(body){
    this.body=body;this.node=body.node;this.destroyed=false;this.enabled=this.node.properties?.z3_prestage_sidecar_open===true;this.autoOpen=this.node.properties?.z3_prestage_sidecar_auto_open!==false;this.filter=this.node.properties?.z3_prestage_sidecar_filter==="shortlist"?"shortlist":"all";this.selectedKey=String(this.node.properties?.z3_prestage_sidecar_selected||"");this.manualPosition=savedPosition(body);this._raf=0;this._drag=null;
    this.toggleButton=button("Image Lab",()=>this.toggle(),"z3h3-btn z3pre-sidecar-toggle");this.toggleButton.title="Open the PreStage image preview and curation gallery.";
    this.root=el("aside","z3pre-image-sidecar");this.root.hidden=true;this.root.tabIndex=0;
    this.head=el("header","z3pre-sidecar-head");this.head.title="Drag to move. Double-click to dock beside PreStage again.";
    const brand=el("div","z3pre-sidecar-brand");brand.append(el("b",null,"PreStage Image Lab"),el("small",null,"Preview · curate · handoff"));this.countPill=el("span","z3pre-sidecar-count","0 images");const dock=button("↺",()=>this.resetPosition(),"z3h3-preview-close"),close=button("×",()=>this.setVisible(false),"z3h3-preview-close");dock.title="Dock beside PreStage";close.title="Hide Image Lab";this.head.append(brand,this.countPill,dock,close);
    this.flow=el("div","z3pre-sidecar-flow");
    this.viewport=el("div","z3pre-sidecar-viewport");this.largeImage=document.createElement("img");this.largeImage.alt="Selected PreStage result";this.empty=el("div","z3pre-sidecar-empty");this.empty.append(el("b",null,"Generate a still to begin"),el("small",null,"Results land here and in ComfyUI Assets—never across the node."),el("div","z3pre-sidecar-empty-actions"));this.empty.lastChild.append(button("Generate image",()=>this.body.runImageBatch(1),"z3h3-btn primary"),button("Generate batch",()=>this.body.runImageBatch(this.body.data.handoff.batch_count),"z3h3-btn"));this.previous=button("‹",()=>this.step(-1),"z3pre-sidecar-nav prev");this.next=button("›",()=>this.step(1),"z3pre-sidecar-nav next");this.viewport.append(this.empty,this.previous,this.next);
    this.meta=el("div","z3pre-sidecar-meta");this.metaTitle=el("b");this.metaPath=el("small");this.meta.append(el("div",null),el("div","z3pre-sidecar-meta-actions"));this.meta.firstChild.append(this.metaTitle,this.metaPath);
    this.destination=select([["first_frame","Start frame"],["reference","Reference"],["last_frame","End frame"],["new_shot","New shot · Start"]],this.body.data.handoff.destination==="none"?"first_frame":this.body.data.handoff.destination);this.destination.title="Where the currently selected Image Lab result should go in Creator";this.destination.addEventListener("change",()=>{this.body.data.handoff.destination=this.destination.value;this.body.commit(false)});
    this.useSelectedButton=button("Use selected → Creator",()=>this.useSelected(false),"z3h3-btn primary z3pre-use-selected");this.useSelectedButton.title="Attach exactly the selected Image Lab image to Creator without inserting or replacing prompt text.";
    this.useAndVideoButton=button("Use + Video",()=>this.useSelected(true),"z3h3-btn primary");this.useAndVideoButton.title="Attach the selected image, release the PreStage gate, then queue Creator video.";
    this.startButton=button("Mark Start",()=>this.assignSelected("first_frame"),"z3h3-btn");this.startButton.title="Mark this result as the opening frame for a multi-frame handoff";this.endButton=button("Mark End",()=>this.assignSelected("last_frame"),"z3h3-btn");this.endButton.title="Mark this result as the closing frame for a multi-frame handoff";this.referenceButton=button("Mark Ref",()=>this.assignSelected("reference"),"z3h3-btn");this.referenceButton.title="Mark this result as a visual reference for a multi-frame handoff";this.shortlistButton=button("☆",()=>this.toggleSelectedShortlist(),"z3h3-btn");this.shortlistButton.title="Add to audition shortlist";this.removeButton=button("Remove",()=>this.removeSelected(),"z3h3-mini");this.removeButton.title="Remove from Image Lab history only";this.meta.lastChild.append(this.destination,this.useSelectedButton,this.useAndVideoButton,this.startButton,this.endButton,this.referenceButton,this.shortlistButton,this.removeButton);
    this.assignments=el("section","z3pre-sidecar-assignments");
    this.autoWarning=el("div","z3pre-sidecar-auto");this.autoWarning.hidden=true;
    this.galleryTools=el("div","z3pre-sidecar-gallery-tools");this.gallery=el("div","z3pre-sidecar-gallery");
    this.footer=el("footer","z3pre-sidecar-footer");
    this.root.append(this.head,this.flow,this.viewport,this.meta,this.assignments,this.autoWarning,this.galleryTools,this.gallery,this.footer);document.body.append(this.root);
    // The Image Lab lives outside the node DOM. Keep ComfyUI canvas gestures from
    // treating clicks on this floating tool as graph pan/drag/select actions.
    this._stopCanvasGesture=event=>{if(event.target?.closest?.("button,select,input,textarea,a,[role=button]")||event.currentTarget===this.root)event.stopPropagation()};for(const name of ["pointerdown","mousedown","mouseup","click","dblclick","wheel"])this.root.addEventListener(name,this._stopCanvasGesture);
    this._onActionError=event=>{event.stopPropagation();this.body.announce(event.detail?.message||String(event.detail||"Image Lab action failed."),"error")};this.root.addEventListener("z3pre-action-error",this._onActionError);this.installDragging();this.installKeyboard();this._onResize=()=>this.schedulePosition();globalThis.addEventListener?.("resize",this._onResize,{passive:true});globalThis.addEventListener?.("scroll",this._onResize,{passive:true,capture:true});this.sync({focusLatest:false});
  }
  rows(){const all=[...(this.body.history||[])].reverse();return this.filter==="shortlist"?all.filter(row=>row.shortlisted):all}
  selected(){const rows=this.rows();return rows.find(row=>imageKey(row)===this.selectedKey)||rows[0]||null}
  persist(){this.node.properties ||= {};this.node.properties.z3_prestage_sidecar_open=this.enabled;this.node.properties.z3_prestage_sidecar_auto_open=this.autoOpen;this.node.properties.z3_prestage_sidecar_filter=this.filter;this.node.properties.z3_prestage_sidecar_selected=this.selectedKey;this.node.properties.z3_prestage_sidecar_position=this.manualPosition;this.node.graph?.setDirtyCanvas?.(true,true)}
  setVisible(value){this.enabled=!!value;this.autoOpen=!!value;this.persist();this.syncChrome()}
  toggle(){this.setVisible(!this.enabled)}
  sync({focusLatest=false}={}){
    if(focusLatest&&this.body.history?.length)this.selectedKey=imageKey(this.body.history.at(-1));
    if(!this.selectedKey&&this.body.history?.length)this.selectedKey=imageKey(this.body.history.at(-1));
    this.renderFlow();this.renderSelected();this.renderAssignments();this.renderGallery();this.renderFooter();this.syncChrome();this.persist();
  }
  showResults(){if(this.autoOpen||this.body.data.handoff.mode==="auto")this.enabled=true;this.sync({focusLatest:true})}
  syncChrome(){const count=this.body.history?.length||0;this.toggleButton.textContent=count?`Image Lab · ${count}`:"Image Lab";this.toggleButton.classList.toggle("on",this.enabled);this.countPill.textContent=`${count} image${count===1?"":"s"}`;this.root.hidden=!this.enabled;if(this.enabled){this.schedulePosition();this.startTracking()}else this.stopTracking()}
  renderFlow(){
    this.flow.replaceChildren();const mode=this.body.data.handoff.mode,batch=this.body.data.handoff.batch_count,pending=this.body._pendingImageBatch;
    const state=el("div","z3pre-sidecar-flow-state");
    const title=pending?`Generating · ${pending.remaining} remaining`:mode==="review"?"Review first":mode==="auto"?"AUTO · image then video":mode==="image_only"?"Image only":"PreStage bypassed";
    const detail=this.body._actionMessage||(mode==="review"?"Video waits for your frame choices.":mode==="auto"?"Video queues automatically after the countdown.":mode==="image_only"?"Create and curate without video.":"Creator is released.");
    state.append(el("b",null,title),el("small",null,detail));
    const actions=el("div","z3pre-sidecar-flow-actions"),generate=button(mode==="auto"?`Generate ${batch} + Video`:batch>1?`Generate ${batch} stills`:"Generate still",()=>this.body.runImageBatch(batch),"z3h3-mini primary");generate.disabled=!!pending;actions.append(generate,button("Re-link Creator",()=>this.body.relinkCreator(),"z3h3-mini"),button("Flow…",()=>this.body.openFlowSettings(),"z3h3-mini"));if(mode!=="bypass")actions.append(button("Release Creator + Enable Video",()=>this.body.bypassPreStage(),"z3h3-mini primary z3pre-release-creator"));this.flow.append(state,actions);
  }
  renderSelected(){
    const image=this.selected();this.viewport.replaceChildren();if(!image){this.viewport.append(this.empty);this.meta.hidden=true;return}this.meta.hidden=false;this.selectedKey=imageKey(image);this.largeImage.src=H.viewUrl(image);this.largeImage.alt=label(image.filename);this.viewport.append(this.largeImage,this.previous,this.next);this.metaTitle.textContent=label(image.filename);this.metaPath.textContent=[image.subfolder,image.filename].filter(Boolean).join("/");const preferred=this.body.data.handoff.destination==="none"?"first_frame":this.body.data.handoff.destination;if(this.destination.value!==preferred)this.destination.value=preferred;this.useSelectedButton.disabled=false;this.useAndVideoButton.disabled=false;this.shortlistButton.textContent=image.shortlisted?"★":"☆";this.shortlistButton.title=image.shortlisted?"Remove from audition shortlist":"Add to audition shortlist";this.shortlistButton.classList.toggle("active",!!image.shortlisted);const slots=this.body.slotsForImage(image);this.startButton.classList.toggle("active",slots.includes("first_frame"));this.endButton.classList.toggle("active",slots.includes("last_frame"));this.referenceButton.classList.toggle("active",slots.includes("reference"));
    const auto=this.body._autoCandidate&&imageKey(this.body._autoCandidate)===imageKey(image);this.autoWarning.hidden=!auto;this.autoWarning.replaceChildren();if(auto)this.autoWarning.append(el("span",null,"Auto video is armed for this image."),button("Cancel auto video",()=>this.body.cancelAutoVideo(),"z3h3-mini"));
  }
  renderAssignments(){
    this.assignments.replaceChildren();const start=this.body.imageForSlot("first_frame"),end=this.body.imageForSlot("last_frame"),reference=this.body.imageForSlot("reference"),head=el("div","z3pre-assignment-head");head.append(el("div",null),el("div","z3pre-assignment-actions"));head.firstChild.append(el("b",null,"Marked-frame handoff"),el("small",null,"Optional: mark different Start / End / Reference images, then send the set together."));head.lastChild.append(button("Send marked → Creator",()=>this.body.applyFrameSetup(false),"z3h3-btn primary"),button("Send marked + Video",()=>this.body.applyFrameSetup(true),"z3h3-btn primary"),button("New shot from selected",()=>this.body.handoffSelected(this.selected(),"new_shot",false),"z3h3-btn"));this.assignments.append(head);
    const slots=el("div","z3pre-assignment-slots");for(const [slot,title,image] of [["first_frame","START",start],["last_frame","END",end],["reference","REFERENCE",reference]]){const card=el("div",`z3pre-assignment-slot${image?" assigned":""}`),copy=el("div");copy.append(el("small",null,title),el("b",null,image?label(image.filename):"Not selected"));card.append(copy);if(image)card.append(button("×",()=>this.body.clearImageSlot(slot),"z3h3-mini"));slots.append(card)}this.assignments.append(slots);
  }
  renderGallery(){
    this.galleryTools.replaceChildren();const shortlist=(this.body.history||[]).filter(row=>row.shortlisted);const all=button(`All · ${this.body.history?.length||0}`,()=>{this.filter="all";this.sync()},`z3h3-mini${this.filter==="all"?" active":""}`),picked=button(`Shortlist · ${shortlist.length}`,()=>{this.filter="shortlist";this.sync()},`z3h3-mini${this.filter==="shortlist"?" active":""}`);this.galleryTools.append(el("b",null,"Gallery"),all,picked,button("Audition shortlist",()=>this.body.auditionImages(shortlist,"first_frame"),"z3h3-mini"));
    this.gallery.replaceChildren();const rows=this.rows();for(const image of rows){const assigned=this.body.slotsForImage(image),card=el("article",`z3pre-sidecar-card${imageKey(image)===this.selectedKey?" selected":""}${image.shortlisted?" shortlisted":""}`),pick=button("",()=>{this.selectedKey=imageKey(image);this.sync()},"z3pre-sidecar-card-pick");const thumb=document.createElement("img");thumb.src=H.viewUrl(image);thumb.alt=label(image.filename);pick.append(thumb);const badges=el("div","z3pre-sidecar-badges");for(const slot of assigned)badges.append(el("span",`slot-${slot}`,slot==="first_frame"?"START":slot==="last_frame"?"END":"REF"));const star=button(image.shortlisted?"★":"☆",()=>{this.body.toggleHistoryShortlist(image);this.sync()},"z3pre-sidecar-star");star.title=image.shortlisted?"Remove from audition shortlist":"Add to audition shortlist";const menu=el("div","z3pre-sidecar-hover-menu");menu.append(el("small",null,"Use…"));for(const [dest,title] of [["first_frame","Start"],["reference","Ref"],["last_frame","End"]])menu.append(button(title,()=>this.body.handoffSelected(image,dest,false),"z3h3-mini"));menu.append(button("New shot",()=>this.body.handoffSelected(image,"new_shot",false),"z3h3-mini"));card.append(pick,badges,star,menu);this.gallery.append(card)}if(!rows.length)this.gallery.append(el("div","z3pre-sidecar-gallery-empty",this.filter==="shortlist"?"Star images to build an audition shortlist.":"Generate a still batch to begin curating."));
  }
  renderFooter(){this.footer.replaceChildren();if(this.body.history?.length)this.footer.append(button("Open Renders",()=>this.body.openMedia(),"z3h3-mini"),button("Copy path",async()=>{const image=this.selected();if(image)await navigator.clipboard?.writeText?.([image.subfolder,image.filename].filter(Boolean).join("/"))},"z3h3-mini"),button("Clear history",()=>this.body.clearHistory(),"z3h3-mini"))}
  select(image){if(!image)return;this.selectedKey=imageKey(image);this.sync()}
  step(direction){const rows=this.rows();if(!rows.length)return;let index=rows.findIndex(row=>imageKey(row)===this.selectedKey);if(index<0)index=0;this.selectedKey=imageKey(rows[(index+direction+rows.length)%rows.length]);this.sync()}
  toggleSelectedShortlist(){const image=this.selected();if(image){this.body.toggleHistoryShortlist(image);this.sync()}}
  useSelected(queueVideo=false){const image=this.selected();if(!image)throw new Error("Choose an image first.");return this.body.handoffSelected(image,this.destination.value,queueVideo)}
  assignSelected(slot){const image=this.selected();if(!image)throw new Error("Choose an image first.");return this.body.assignImageSlot(image,slot)}
  removeSelected(){const image=this.selected();if(image){this.body.removeHistoryImage(image);this.selectedKey="";this.sync({focusLatest:true})}}
  installKeyboard(){this._onKey=event=>{if(event.target?.matches?.("input,select,textarea,button"))return;if(event.key==="ArrowLeft"){event.preventDefault();this.step(-1)}else if(event.key==="ArrowRight"){event.preventDefault();this.step(1)}else if(event.key==="Enter"){event.preventDefault();this.useSelected(false)}};this.root.addEventListener("keydown",this._onKey)}
  installDragging(){const start=event=>{if(event.button!==0||event.target?.closest?.("button"))return;const rect=this.root.getBoundingClientRect();this._drag={id:event.pointerId,dx:event.clientX-rect.left,dy:event.clientY-rect.top};this.head.setPointerCapture?.(event.pointerId);this.root.dataset.moving="1";event.preventDefault()};const move=event=>{if(!this._drag||event.pointerId!==this._drag.id)return;const vw=document.documentElement.clientWidth||1280,vh=document.documentElement.clientHeight||720,rect=this.root.getBoundingClientRect(),left=Math.max(8,Math.min(event.clientX-this._drag.dx,vw-rect.width-8)),top=Math.max(8,Math.min(event.clientY-this._drag.dy,vh-Math.min(rect.height,vh-16)-8));this.manualPosition={left:Math.round(left),top:Math.round(top)};this.root.style.left=`${this.manualPosition.left}px`;this.root.style.top=`${this.manualPosition.top}px`;event.preventDefault()};const end=event=>{if(!this._drag||event.pointerId!==this._drag.id)return;this.head.releasePointerCapture?.(event.pointerId);this._drag=null;delete this.root.dataset.moving;this.persist()};const reset=event=>{if(event.target?.closest?.("button"))return;event.preventDefault();this.resetPosition()};this.head.addEventListener("pointerdown",start);this.head.addEventListener("pointermove",move);this.head.addEventListener("pointerup",end);this.head.addEventListener("pointercancel",end);this.head.addEventListener("dblclick",reset);this._dragCleanup=()=>{this.head.removeEventListener("pointerdown",start);this.head.removeEventListener("pointermove",move);this.head.removeEventListener("pointerup",end);this.head.removeEventListener("pointercancel",end);this.head.removeEventListener("dblclick",reset)}}
  resetPosition(){this.manualPosition=null;this.persist();this.schedulePosition()}
  startTracking(){if(this._raf||this.destroyed)return;const tick=()=>{this._raf=0;if(this.destroyed||this.root.hidden)return;this.position();this._raf=requestAnimationFrame(tick)};this._raf=requestAnimationFrame(tick)}
  stopTracking(){if(this._raf){cancelAnimationFrame(this._raf);this._raf=0}}
  schedulePosition(){if(!this.root.hidden)this.position()}
  position(){const anchor=this.body.root?.getBoundingClientRect?.();if(!anchor||anchor.width<1){this.root.style.visibility="hidden";return}const vw=Math.max(320,document.documentElement.clientWidth||1280),vh=Math.max(300,document.documentElement.clientHeight||720),width=Math.min(DEFAULT_WIDTH,Math.max(300,vw-16));let left=anchor.right+SIDE_GAP,side="right";if(left+width>vw-8&&anchor.left-SIDE_GAP-width>=8){left=anchor.left-SIDE_GAP-width;side="left"}let top=Math.max(8,Math.min(anchor.top,vh-260));if(this.manualPosition){left=Math.max(8,Math.min(Number(this.manualPosition.left)||8,vw-width-8));top=Math.max(8,Math.min(Number(this.manualPosition.top)||8,vh-260));side="free"}left=Math.max(8,Math.min(left,vw-width-8));this.root.dataset.side=side;this.root.style.width=`${width}px`;this.root.style.left=`${Math.round(left)}px`;this.root.style.top=`${Math.round(top)}px`;this.root.style.maxHeight=`${Math.max(260,vh-top-8)}px`;this.root.style.visibility=anchor.bottom<0||anchor.top>vh?"hidden":"visible"}
  destroy(){this.destroyed=true;this.stopTracking();this._dragCleanup?.();this.root.removeEventListener("keydown",this._onKey);this.root.removeEventListener("z3pre-action-error",this._onActionError);for(const name of ["pointerdown","mousedown","mouseup","click","dblclick","wheel"])this.root.removeEventListener(name,this._stopCanvasGesture);globalThis.removeEventListener?.("resize",this._onResize);globalThis.removeEventListener?.("scroll",this._onResize,true);this.root.remove()}
}

export function installPreStageImageSidecar(body){return new PreStageImageSidecar(body)}
