import * as H from "./z3_h3_api.js";
import * as S from "./z3_h3_state.js";
import { canonicalShotSnapshot, validateShotSnapshot, shotIndexFor, shotText } from "./h3_shot_snapshot.js";
import { openReferenceWorkspace } from "./h3_reference_workspace.js";
import { subscribeCreatorBody } from "./h3_workspace_runtime.js";
import { H3_SCENE_SLOT_ORDER } from "./h3_prompt_categories.js";
import { castMentionRanges } from "./h3_prompt_tokens.js";

const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;};
const INSPECT_PREF_KEY="z3.minimaxCreator.shotInspector.v1";
function readInspectPrefs(){try{const v=JSON.parse(localStorage.getItem(INSPECT_PREF_KEY)||"{}");return v&&typeof v==="object"&&!Array.isArray(v)?v:{};}catch{return {};}}
function writeInspectPrefs(patch){try{localStorage.setItem(INSPECT_PREF_KEY,JSON.stringify({...readInspectPrefs(),...patch}));}catch{}}

const clean=(value)=>String(value??"").trim();
const short=(value,max=64)=>{const s=String(value||"").replace(/\s+/g," ").trim();return s.length>max?`${s.slice(0,max-1)}…`:s;};
const safeSeed=(value)=>{const n=Number(value);return Number.isInteger(n)&&n>=0?n:0;};
const button=(text,fn,cls="z3h3-inspect-btn",title="")=>{const n=el("button",cls,text);n.type="button";if(title)n.title=title;n.addEventListener("pointerdown",e=>e.stopPropagation());n.addEventListener("click",async e=>{e.preventDefault();e.stopPropagation();try{await fn?.(e);}catch(error){console.error("MiniMax Shot Inspector action failed",error);n.dataset.error="1";n.title=error?.message||String(error);setTimeout(()=>delete n.dataset.error,1600);}});return n;};
let active=null;

function generationPasses(result,mode){return (result?.[mode]?.passes||[]).filter(pass=>pass?.kind!=="clip");}
function generationIndex(body,index){return (body?.data?.segments||[]).slice(0,index).filter(seg=>seg?.kind!=="clip").length;}
export async function canonicalPromptForShot(body,index=null){
  const i=shotIndexFor(body,index),seg=body?.data?.segments?.[i];if(!seg||seg.kind==="clip")return {index:i,kind:"clip",authored:clean(seg?.prompt),raw:"",h3:"",actual:"",activeMode:"clip",result:null,pass:null};
  const nodeSeed=safeSeed(body?.widgets?.seed?.value),processing=String(body?.widgets?.processing_mode?.value||"entire text as one"),variation=Number(body?.currentVariationIndex?.()??body?.widgets?.variation_index?.value??0)||0;
  const result=await H.promptPreview(S.normalizeData(structuredClone(body.data)),nodeSeed,processing,variation),gi=generationIndex(body,i),rawPass=generationPasses(result,"raw")[gi]||null,h3Pass=generationPasses(result,"h3")[gi]||null,activeMode=result.active_mode==="h3"?"h3":"raw",activePass=activeMode==="h3"?h3Pass:rawPass;
  // The canonical preview endpoint receives the Creator seed; its shared RAW uses
  // that seed while an explicitly retaken shot uses segment.seed for shot-local
  // wildcard/variation resolution. Keep both visible rather than mislabeling the
  // node seed as the shot's effective prompt seed.
  const promptSeed=seg.seed!=null&&seg.seed!==""?safeSeed(seg.seed):nodeSeed+i;
  return {index:i,kind:"generation",authored:String(seg.prompt||""),globalAuthored:String(body.data.prompt||""),raw:String(rawPass?.prompt||""),h3:String(h3Pass?.prompt||""),actual:String(activePass?.prompt||""),activeMode,result,pass:activePass,rawPass,h3Pass,resolutionOrder:result.resolution_order||[],wildcards:result.wildcards||[],seed:promptSeed,nodeSeed,promptSeed,processing,variation};
}
function effectiveAuditions(body,index){
  const seg=body?.data?.segments?.[index]||{},merge=(shared,own)=>({...((shared&&typeof shared==="object")?shared:{}),...((own&&typeof own==="object")?own:{})});return {cast:merge(body?.data?.cast_auditions,seg.cast_auditions),scene:merge(body?.data?.scene_auditions,seg.scene_auditions)};
}
function variationSummary(body,index){
  const source=shotText(body,index),aud=effectiveAuditions(body,index),hasCastAudition=Object.values(aud.cast).some(cfg=>Array.isArray(cfg?.candidates)&&cfg.candidates.length),hasSceneAudition=Object.values(aud.scene).some(cfg=>Array.isArray(cfg?.candidates)&&cfg.candidates.length&&cfg.mode!=="prepared"),hasAudition=hasCastAudition||hasSceneAudition,hasSequential=castMentionRanges(source,(body?.data?.subjects||[]).map((row)=>row?.handle).filter(Boolean)).some((row)=>row.direction!==0)||/\u2063[^\u2063]+\u2063[ \t]*[+-]/.test(source)||/\b(?:LOCATION|CLOTHING|PROP|ACTION|CAMERA|LIGHT|DIALOGUE|AUDIO|MUSIC)[ \t]*[+-](?![A-Za-z0-9_])/.test(source)||/__[-+][^_]+__/.test(source),hasRandom=/__(?![-+])(?:[*~%])?[A-Za-z0-9_.\/-]+__/.test(source),active=[];if(hasSequential)active.push("sequential");if(hasRandom)active.push("random");if(hasAudition)active.push("audition");if(!active.length)active.push("fixed");return {active,hasSequential,hasRandom,hasAudition,index:Number(body?.currentVariationIndex?.()??body?.widgets?.variation_index?.value??0)||0,auditions:aud};
}
function sceneValue(row){return row?.title||row?.prompt||"selected";}
function section(title,subtitle="",open=true){const d=document.createElement("details");d.className="z3h3-inspect2-section";const prefs=readInspectPrefs(),sections=prefs.sections&&typeof prefs.sections==="object"?prefs.sections:{};d.open=Object.prototype.hasOwnProperty.call(sections,title)?sections[title]!==false:open;d.addEventListener("toggle",()=>{const current=readInspectPrefs();writeInspectPrefs({sections:{...(current.sections||{}),[title]:d.open}});});const s=document.createElement("summary"),copy=el("span");copy.append(el("b",null,title));if(subtitle)copy.append(el("small",null,subtitle));s.append(copy);d.append(s);return d;}
function readout(label,value,cls=""){const row=el("div",`z3h3-inspect2-readout ${cls}`.trim());row.append(el("small",null,label),el("b",null,String(value??"")));return row;}
function pill(label,value,cls=""){const n=el("span",`z3h3-inspect-pill ${cls}`.trim());n.append(el("small",null,label),el("b",null,String(value)));return n;}
function promptBlock(label,text,{primary=false,badge=""}={}){const wrap=el("div",`z3h3-inspect2-prompt-block${primary?" primary":""}`),head=el("div");head.append(el("b",null,label));if(badge)head.append(el("span",null,badge));wrap.append(head,el("pre",null,text||"(empty)"));return wrap;}
function normalizeSeedInput(value){const s=String(value??"").trim();if(!s)return null;const n=Number(s);if(!Number.isInteger(n)||n<0)throw new Error("Shot seed must be a whole number ≥ 0, or blank to inherit the node seed.");return n;}
function updateShotField(body,index,key,value,label){const seg=body?.data?.segments?.[index];if(!seg||seg.kind==="clip")return false;if(value===undefined)delete seg[key];else seg[key]=value;body.commitData?.(true,{historyLabel:label});return true;}
function loraLabel(row){return String(row?.name||"").split(/[\\/]/).pop()||"LoRA";}
function auditionText(config){const candidates=Array.isArray(config?.candidates)?config.candidates:[];return candidates.length?`${candidates.length} candidates · ${config?.mode==="prepared"?"prepared":"shortlist"}`:"off";}

function renderCompact(body,index,host){
  const i=shotIndexFor(body,index),snap=canonicalShotSnapshot(body,i),checks=validateShotSnapshot(body,i),errors=checks.filter(r=>r.level==="error").length,warnings=checks.filter(r=>r.level==="warn").length,varState=variationSummary(body,i),shell=el("section","z3h3-canonical-inspector compact v3133"),head=el("div","z3h3-inspect-head"),copy=el("div");
  copy.append(el("b",null,snap.seg?.kind==="clip"?`Clip ${i+1}`:`Shot ${i+1}${clean(snap.seg?.name)?` · ${snap.seg.name}`:""} · ${snap.route}`),el("small",null,`${snap.duration.toFixed(1)}s · ${snap.frames}f · canonical state`));head.append(copy,el("span",`z3h3-inspect-health ${errors?"error":warnings?"warn":"ok"}`,errors?`${errors} ERROR${errors===1?"":"S"}`:warnings?`${warnings} WARN${warnings===1?"":"S"}`:"READY"));shell.append(head);
  const pills=el("div","z3h3-inspect-pills");pills.append(pill("Cast",snap.cast.length?snap.cast.map(row=>`@${row.handle}`).join(", "):"none"),pill("Refs",snap.refs.rows.length?`${snap.refs.rows.length} · ${snap.route}`:"none"),pill("LoRAs",snap.loras.filter(row=>row.enabled!==false).length||"none"),pill("Variation",varState.active.join(" + ")),pill("Seed",snap.seg?.seed??body.widgets?.seed?.value??"node"));shell.append(pills);
  if(snap.seg?.kind!=="clip"){const exact=el("div","z3h3-inspect2-compact-exact","Resolving exact output…");shell.append(exact);canonicalPromptForShot(body,i).then(result=>{if(exact.isConnected){exact.textContent=short(result.actual,220)||"No compiled prompt.";exact.title=result.actual||"";exact.dataset.mode=result.activeMode;}}).catch(error=>{if(exact.isConnected){exact.textContent=error.message||String(error);exact.dataset.state="error";}});}
  host.replaceChildren(shell);return {shell,snapshot:snap,checks};
}

export function renderCanonicalShotInspector(body,index,host,{compact=false,onNavigate=null}={}){
  if(!host)return null;if(compact)return renderCompact(body,index,host);
  const i=shotIndexFor(body,index),snap=canonicalShotSnapshot(body,i),checks=validateShotSnapshot(body,i),errors=checks.filter(r=>r.level==="error").length,warnings=checks.filter(r=>r.level==="warn").length,varState=variationSummary(body,i),shell=el("section","z3h3-canonical-inspector v3133"),head=el("div","z3h3-inspect-head"),copy=el("div");copy.append(el("b",null,snap.seg?.kind==="clip"?`Clip ${i+1}`:`Shot ${i+1}${clean(snap.seg?.name)?` · ${snap.seg.name}`:""} · ${snap.route}`),el("small",null,"Canonical Shot Inspector · reads live Creator state and the exact queue compiler"));head.append(copy,el("span",`z3h3-inspect-health ${errors?"error":warnings?"warn":"ok"}`,errors?`${errors} ERROR${errors===1?"":"S"}`:warnings?`${warnings} WARNING${warnings===1?"":"S"}`:"READY"));shell.append(head);
  if(snap.seg?.kind==="clip"){const clip=section("CLIP","Supplied footage card",true),bodyEl=el("div","z3h3-inspect2-grid");bodyEl.append(readout("File",snap.seg.filename||""),readout("Duration",`${snap.duration.toFixed(2)} s`),readout("Audio",snap.seg.sound===false?"off":"on"),readout("Continue",snap.seg.continue?"yes":"no"));clip.append(bodyEl,button("Open Clip Options",()=>body.openShotOptions?.(i),"z3h3-inspect-btn"));shell.append(clip);host.replaceChildren(shell);return {shell,snapshot:snap,checks};}

  const shotSec=section("SHOT","Identity, timing and sampling seed",true),shotGrid=el("div","z3h3-inspect2-shot-grid"),name=document.createElement("input"),duration=document.createElement("input"),seed=document.createElement("input");name.value=clean(snap.seg.name);name.placeholder=`Shot ${i+1}`;duration.type="number";duration.min=.2;duration.max=120;duration.step=.1;duration.value=String(snap.duration);seed.type="number";seed.min=0;seed.step=1;seed.placeholder=`inherit node seed · ${safeSeed(body.widgets?.seed?.value)}`;seed.value=snap.seg.seed!=null?String(snap.seg.seed):"";
  const miniField=(label,control,hint="")=>{const f=el("label","z3h3-inspect2-field");f.append(el("span",null,label),control);if(hint)f.append(el("small",null,hint));return f;};shotGrid.append(miniField("Name",name),miniField("Duration (s)",duration),readout("Frames",snap.frames),miniField("Seed",seed,"Blank inherits the Creator node seed."));
  name.addEventListener("change",()=>updateShotField(body,i,"name",clean(name.value)||undefined,"Rename shot"));duration.addEventListener("change",()=>{const value=Math.max(.2,Math.min(120,Number(duration.value)||S.DEFAULT_DURATION_S));duration.value=String(value);updateShotField(body,i,"duration_s",value,"Change shot duration");});seed.addEventListener("change",()=>{try{const value=normalizeSeedInput(seed.value);updateShotField(body,i,"seed",value==null?undefined:value,"Change shot seed");}catch(error){seed.setCustomValidity(error.message);seed.reportValidity();setTimeout(()=>seed.setCustomValidity(""),1000);}});shotSec.append(shotGrid);shell.append(shotSec);

  const promptSec=section("PROMPT","RAW source + exact resolved RAW/H3 from the actual queue pipeline",true),promptStatus=el("div","z3h3-inspect2-prompt-status","Resolving this shot through the canonical compiler…"),promptHost=el("div","z3h3-inspect2-prompts");promptSec.append(promptStatus,promptHost);shell.append(promptSec);
  canonicalPromptForShot(body,i).then(result=>{if(!promptHost.isConnected)return;promptStatus.replaceChildren(el("b",null,`ACTUAL OUTPUT · ${result.activeMode==="h3"?"H3 FORMAT":"RAW"}`),el("span",null,`variation ${result.variation+1} · shot prompt seed ${result.promptSeed}${result.nodeSeed!==result.promptSeed?` · Creator seed ${result.nodeSeed}`:""}${result.wildcards.length?` · wildcards ${result.wildcards.join(", ")}`:""}`));promptHost.replaceChildren(promptBlock("WHAT THIS SHOT SENDS TO H3",result.actual,{primary:true,badge:result.activeMode.toUpperCase()}),promptBlock("RAW EDITOR SOURCE",result.authored,{badge:"AUTHORED"}));if(result.globalAuthored)promptHost.append(promptBlock("SHARED RAW SOURCE",result.globalAuthored,{badge:"INHERITED"}));promptHost.append(promptBlock("RESOLVED RAW",result.raw,{badge:"CANONICAL"}),promptBlock("RESOLVED H3",result.h3,{badge:result.activeMode==="h3"?"ACTIVE":"PREVIEW"}));const pipe=el("div","z3h3-inspect2-pipeline");for(const stage of result.resolutionOrder)pipe.append(el("span",null,String(stage).replaceAll("_"," ")));promptHost.append(pipe);}).catch(error=>{if(promptStatus.isConnected){promptStatus.textContent=error.message||String(error);promptStatus.dataset.state="error";}});

  const castSec=section("CAST","Characters actually referenced by this shot + audition state",true),castList=el("div","z3h3-inspect2-list");for(const subject of snap.cast){const cfg=varState.auditions.cast?.[subject.handle],row=el("div","z3h3-inspect2-row"),copy2=el("div");copy2.append(el("b",null,`@${subject.handle}`),el("small",null,subject.display_name||subject.name||subject.preset_group||"Cast character"));row.append(copy2,pill("Audition",auditionText(cfg),cfg?.candidates?.length?"active":""));castList.append(row);}if(!snap.cast.length)castList.append(el("div","z3h3-inspect2-empty","No Cast @mentions resolve into this shot."));castSec.append(castList,button("Open Cast Studio",()=>body.openCast?.(),"z3h3-inspect-btn"));shell.append(castSec);

  const sceneSec=section("SCENE","Location, wardrobe, action, camera, lighting and other semantic slots",true),sceneList=el("div","z3h3-inspect2-scene-list");for(const slot of H3_SCENE_SLOT_ORDER){const row=snap.scene[slot];if(!row)continue;const cfg=varState.auditions.scene?.[slot],item=el("div","z3h3-inspect2-scene-row"),copy2=el("div");copy2.append(el("small",null,(row._meta?.label||slot).toUpperCase()),el("b",null,sceneValue(row)),el("span",null,row._scope||""));item.append(copy2,pill("Audition",auditionText(cfg),cfg?.candidates?.length?"active":""));item.addEventListener("dblclick",()=>body.openScenePicker?.(slot));sceneList.append(item);}if(!sceneList.children.length)sceneList.append(el("div","z3h3-inspect2-empty","No Scene category selections are active."));sceneSec.append(sceneList);shell.append(sceneSec);

  const pinMap=seg?.director?.timeline?.media&&typeof seg.director.timeline.media==="object"?seg.director.timeline.media:{};const refSec=section("REFERENCES",`${snap.refs.rows.length} effective source${snap.refs.rows.length===1?"":"s"} · ${snap.route}`,true),refList=el("div","z3h3-inspect2-list");if(snap.refs.rows.length){const files=[...new Set(snap.refs.rows.map(row=>row.filename).filter(Boolean))];H.assetStatus(files).catch(()=>({})).then(status=>{if(!refList.isConnected)return;refList.replaceChildren();for(const ref of snap.refs.rows){const missing=status[ref.filename]===false,pin=pinMap[ref.handle]?.pin===true?` · H3 PIN ${Number(pinMap[ref.handle]?.start||0).toFixed(2)}s`:"",row=el("div",`z3h3-inspect2-row${missing?" missing":""}`),copy2=el("div");copy2.append(el("b",null,`${missing?"⚠ ":""}@${ref.handle}`),el("small",null,`${ref._scope||"Assigned"} · ${ref.role||"reference"} · ${ref.subject_role||"reference"}${ref.reference_name?` · ${ref.reference_name}`:""}${pin}`),el("span",null,ref.filename||"No file linked"));row.append(copy2,pill("Influence",Number(ref.strength??1).toFixed(2)),ref.library_ref_id?pill("Library",ref.library_ref_id,"library"):pill("Library","workflow local","local"));refList.append(row);}});}else refList.append(el("div","z3h3-inspect2-empty","No effective reference media for this shot."));refSec.append(refList,button("Open Reference Workspace",()=>openReferenceWorkspace(body,{shotIndex:i}),"z3h3-inspect-btn primary"));shell.append(refSec);

  const loraSec=section("LORAS","Shared + shot-specific LoRAs sent with this shot",false),loraList=el("div","z3h3-inspect2-list");for(const lora of snap.loras){const row=el("div","z3h3-inspect2-row"),copy2=el("div");copy2.append(el("b",null,loraLabel(lora)),el("small",null,`${lora._scope||"Shared"}${lora.enabled===false?" · disabled":""}`));row.append(copy2,pill("Strength",Number(lora.strength??1).toFixed(2),lora.enabled===false?"muted":""));if(lora.trigger||lora.at||lora.start!=null)row.append(pill("Timed",String(lora.trigger||lora.at||lora.start)));loraList.append(row);}if(!snap.loras.length)loraList.append(el("div","z3h3-inspect2-empty","No LoRAs are assigned to this shot."));loraSec.append(loraList,button("Open LoRAs",()=>body.openLoras?.(),"z3h3-inspect-btn"));shell.append(loraSec);

  const varSec=section("VARIATION","Readout of the real semantic/wildcard/audition state",false),modeGrid=el("div","z3h3-inspect2-variation-grid");for(const [id,label,detail] of [["fixed","Fixed","No active variation syntax"],["sequential","Sequential","@/$ +/- or stepped wildcard"],["random","Random","Seeded/random wildcard call"],["audition","Audition","Cast or Scene audition candidates"]]){const on=varState.active.includes(id),card=el("div",`z3h3-inspect2-variation-card${on?" active":""}`);card.append(el("b",null,label),el("small",null,on?detail:"inactive"));modeGrid.append(card);}const audDetail=el("div","z3h3-inspect2-auditions");for(const [role,cfg] of Object.entries(varState.auditions.cast||{}))if(Array.isArray(cfg?.candidates)&&cfg.candidates.length)audDetail.append(readout(`CAST @${role}`,cfg.candidates.map(v=>`@${String(v).replace(/^@/,"")}`).join(" · ")));for(const [slot,cfg] of Object.entries(varState.auditions.scene||{}))if(Array.isArray(cfg?.candidates)&&cfg.candidates.length)audDetail.append(readout(`SCENE ${slot.toUpperCase()}`,`${cfg.candidates.length} candidates`));varSec.append(modeGrid,readout("Current variation index",varState.index),audDetail);shell.append(varSec);

  if(checks.length){const issueSec=section("VALIDATION",`${checks.length} canonical routing check${checks.length===1?"":"s"}`,false),issues=el("div","z3h3-inspect-issues");for(const row of checks){const issue=el("div",`z3h3-inspect-issue ${row.level}`);issue.append(el("b",null,row.title),el("span",null,row.detail));issues.append(issue);}issueSec.append(issues);shell.append(issueSec);}
  const audit=body.persistenceAudit?.();if(audit){const health=el("div",`z3h3-inspect-save-health${audit.ok?"":" warn"}`);health.append(el("b",null,audit.ok?"SAVE / RELOAD · STABLE":"SAVE / RELOAD · CHECK"),el("span",null,audit.ok?"Canonical Creator state round-trips without structural loss.":(audit.warnings||[audit.error||"State audit failed."]).join(" · ")));shell.append(health);}
  host.replaceChildren(shell);return {shell,snapshot:snap,checks};
}

export function openCanonicalShotInspector(body,index=null){
  if(!body)throw new Error("No MiniMax Creator is active");if(active?.root?.isConnected)active.close();
  const root=el("div","z3h3-inspect-backdrop"),panel=el("section","z3h3-inspect-modal v3133"),head=el("header","z3h3-inspect-modal-head"),content=el("div","z3h3-inspect-modal-content");const savedShot=Number(readInspectPrefs().lastShot);let current=shotIndexFor(body,index==null&&body.target==="global"&&Number.isInteger(savedShot)?savedShot:index),renderQueued=false,unsubscribe=null,pendingRender=false;
  const close=()=>{unsubscribe?.();unsubscribe=null;root.remove();if(active?.root===root)active=null;};
  const render=()=>{current=shotIndexFor(body,current);writeInspectPrefs({lastShot:current});const nav=el("div","z3h3-inspect-nav");nav.append(button("‹",()=>{current=Math.max(0,current-1);body.switchTarget?.(current);render();},"z3h3-inspect-btn"),el("b",null,`Shot ${current+1} of ${body.data.segments.length}`),button("›",()=>{current=Math.min(body.data.segments.length-1,current+1);body.switchTarget?.(current);render();},"z3h3-inspect-btn"));const host=el("div");renderCanonicalShotInspector(body,current,host);const actions=el("div","z3h3-inspect-modal-actions");actions.append(button("References",()=>openReferenceWorkspace(body,{shotIndex:current}),"z3h3-inspect-btn primary"),button("Cast",()=>body.openCast?.(),"z3h3-inspect-btn"),button("LoRAs",()=>body.openLoras?.(),"z3h3-inspect-btn"),button("Director",()=>body.openDirector?.(),"z3h3-inspect-btn"));content.replaceChildren(nav,host,actions);};
  const scheduleRender=()=>{if(renderQueued||!root.isConnected)return;const focused=panel.contains(document.activeElement)&&document.activeElement?.matches?.("input,textarea,select,[contenteditable=true]");if(focused){pendingRender=true;return;}renderQueued=true;(globalThis.requestAnimationFrame||((fn)=>setTimeout(fn,0)))(()=>{renderQueued=false;if(root.isConnected)render();});};panel.addEventListener("focusout",()=>{if(pendingRender){pendingRender=false;queueMicrotask(scheduleRender);}});
  const brand=el("div");brand.append(el("b",null,"Canonical Shot Inspector"),el("small",null,"What exactly is this shot going to send to H3? · one live state + one compiler pipeline"));head.append(brand,el("div","z3h3-spacer"),button("Close",close,"z3h3-inspect-btn"));panel.append(head,content);root.append(panel);document.body.append(root);root.addEventListener("mousedown",e=>{if(e.target===root)close();});for(const name of ["pointerdown","pointerup","mousedown","mouseup","click","dblclick","wheel","keydown","keyup","keypress","beforeinput","input","change","compositionstart","compositionend"])panel.addEventListener(name,e=>e.stopPropagation());
  unsubscribe=subscribeCreatorBody((candidate,reason)=>{if(candidate!==body||!root.isConnected)return;if(body.target!=="global"&&Number.isInteger(Number(body.target))&&reason==="target")current=shotIndexFor(body,body.target);if(["data","target","cast-sync","sidebar-action"].includes(String(reason)))scheduleRender();});active={root,close,render};render();return active;
}
