import * as H from "./z3_h3_api.js";
import * as S from "./z3_h3_state.js";
import { saveMachineSettings } from "./h3_settings_store.js";
import { createH3ThemeStudio } from "./h3_theme_studio.js";
import { applyCreatorAppearance } from "./h3_suite_appearance.js";
import { describeH3Resolution, firstPassResolutionOptions, videoResolutionOptions } from "./h3_canvas.js";
import { h3SelectedModelProfile } from "./h3_model_profile.js";
import { H3PackAPI } from "./h3_pack_api.js";
import { castStateIntegrity, refreshCastPresetCache, syncBodyFromCastPresets } from "./h3_cast_studio.js";
import { formatWorkloadRatio, planH3Workload } from "./h3_workload.js";

let openDrawer=null;
const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!=null)node.textContent=text;return node;};
const button=(text,fn,cls="z3h3-btn")=>{const node=el("button",cls,text);node.type="button";node.addEventListener("pointerdown",e=>e.stopPropagation());node.addEventListener("click",async e=>{e.preventDefault();e.stopPropagation();try{await fn?.(e);}catch(error){console.error("MiniMax Creator settings action failed",error);node.dataset.error="1";node.title=error?.message||String(error);setTimeout(()=>delete node.dataset.error,1600);}});return node;};
const input=(type,value)=>{const node=document.createElement("input");node.type=type;if(type==="checkbox")node.checked=!!value;else node.value=value??"";return node;};
const select=(options,value)=>{const node=document.createElement("select");for(const raw of options||[]){const [v,label]=Array.isArray(raw)?raw:[raw,raw],o=document.createElement("option");o.value=v;o.textContent=label;if(String(v)===String(value))o.selected=true;node.append(o);}return node;};
const field=(label,control,hint="")=>{const wrap=el("label","z3h3-setting-field"),copy=el("div");copy.append(el("b",null,label));if(hint)copy.append(el("small",null,hint));wrap.append(copy,control);return wrap;};
const section=(title,...children)=>{const node=el("section","z3h3-setting-section");node.append(el("h3",null,title),...children.filter(Boolean));return node;};
const row=(...children)=>{const node=el("div","z3h3-setting-row");node.append(...children.filter(Boolean));return node;};
const check=(value)=>{const c=input("checkbox",value);return c;};

const SPECS={
  seed_hunt_beta:["Seed Hunt Lab (beta)","Off by default. When enabled, adds a Seed Hunt button that can queue up to four real H3 drafts sequentially, show TinyVAE checks, and lock one seed into Creator. Multiple drafts take proportionally longer; nothing runs until you explicitly start a hunt.","toggle","Optional beta"],
  preview_sidecar:["Preview sidecar","Show the docked TinyVAE preview beside the active Creator. Use Preview setup for decoder frames, size, FPS, information and hidden-overhead behavior.","toggle","Experience"],
  autoplay_previews:["Autoplay previews","Play finished and sampling previews automatically.","toggle","Experience"],
  advanced:["Advanced controls","Show deliberately technical schedule/acceleration controls.","toggle","Experience"],
  show_shift_pills:["Flow-shift pills","Expose native video/audio shift controls on the main node.","toggle","Experience"],
  define_refs:["Write reference scope into prompt","Add mechanical H3 reference-role prose when no richer refined form already defines it.","toggle","Prompting"],
  turbo_lead_in:["Turbo base-weight lead-in","Opening steps before the distillation LoRA takes over. 0 keeps native turbo behavior.","number","Rendering"],
  video_crf:["Video CRF","H.264 output quality. Lower is larger / higher quality; 23 is the encoder default.","number","Output"],
  video_prefix:["Video output prefix","ComfyUI output path / filename prefix for rendered video.","text","Output"],
  image_prefix:["Image output prefix","ComfyUI output path / filename prefix for Pre-Stage images.","text","Output"],
};
const GROUPS=["Experience","Optional beta","Prompting","Rendering","Output"];
function close(){try{openDrawer?._z3Cleanup?.();}catch{}openDrawer?.remove();openDrawer=null;}
function setWidget(body,name,value){const widget=body?.widgets?.[name];if(!widget)return;widget.value=value;widget.callback?.(value,body.node.graph?.canvas,body.node);body.node.graph?.setDirtyCanvas?.(true,true);body.renderQuick?.();body.renderStatus?.();}
function widgetOptions(widget){const values=widget?.options?.values||widget?.combo_options||widget?.options||[];return Array.isArray(values)?values.map(v=>[v,v]):[[widget?.value,widget?.value]];}
function filename(value){return String(value||"").split(/[\\/]/).pop()||"not selected";}

function launchOutsideDrawer(fn){
  close();
  queueMicrotask(async()=>{try{await fn?.();}catch(error){console.error("MiniMax Creator secondary panel failed",error);}});
}

function creatorSetup(body){
  if(!body)return el("div","z3h3-note","Select a Creator node to edit workflow-specific setup.");
  const host=el("div","z3h3-settings-live");

  const models=body.data.models||(body.data.models={}),modelSummary=el("div","z3h3-setting-summary"),modelCopy=el("div","z3h3-setting-summary-copy");
  modelCopy.append(el("b",null,"Models & devices"),el("small",null,[models.route&&models.route!=="auto"?`route ${String(models.route).toUpperCase()}`:"auto route",models.fl2va?`FL ${filename(models.fl2va)}`:"FL not selected",models.ref2va?`REF ${filename(models.ref2va)}`:"REF not selected"].join(" · ")));
  modelSummary.append(modelCopy,button("Open Models / Devices",()=>launchOutsideDrawer(()=>body.openModels?.()),"z3h3-btn primary"));
  if("dynamic_vram" in models){delete models.dynamic_vram;body.commitData?.(false);}
  const memoryNote=el("div","z3h3-note good","Memory management: native ComfyUI DynamicVRAM/AIMDO. Creator no longer overrides H3 memory mode because the retired bypass could stall generation.");
  host.append(section("Model routing",modelSummary,memoryNote));

  const previewSummary=el("div","z3h3-setting-summary"),previewCopy=el("div","z3h3-setting-summary-copy");
  previewCopy.append(el("b",null,"TinyVAE live preview"),el("small",null,models.preview?`decoder ${filename(models.preview)}`:"preview decoder not selected"));
  previewSummary.append(previewCopy,button("Open Preview Settings",()=>launchOutsideDrawer(()=>body.previewSidecar?.openSettings?.()),"z3h3-btn primary"));
  host.append(section("Preview",previewSummary,el("div","z3h3-note","Controls decode frames, proxy size, playback FPS, JPEG quality, information shown and zero-overhead behavior. These hardware preferences do not change the final VAE render.")));

  const integrityStatus=el("div","z3h3-integrity-status z3h3-note","Not checked yet. Integrity tools inspect the reusable Library and this workflow without changing either one."),integrityActions=el("div","z3h3-setting-profile-actions");
  const describeIssues=(library,workflow)=>{
    const libraryCount=Number(library?.counts?.issues||0),workflowCount=Number(workflow?.counts?.issues||0),total=libraryCount+workflowCount;
    integrityStatus.className=`z3h3-integrity-status z3h3-note${total?" warn":" good"}`;
    integrityStatus.textContent=total?`Found ${libraryCount} reusable Library issue${libraryCount===1?"":"s"} and ${workflowCount} workflow Cast issue${workflowCount===1?"":"s"}. Repair is rollback-protected and preserves workflow-local characters when a reusable record is gone.`:`State integrity is clean · ${library?.counts?.cast||0} reusable Cast records · ${workflow?.counts?.subjects||0} workflow Cast records.`;
    const labels=[...(library?.issues||[]),...(workflow?.issues||[])].slice(0,8).map(issue=>`${issue.kind}${issue.key?`: ${issue.key}`:""}`);
    integrityStatus.title=labels.join("\n");
  };
  const checkIntegrity=async()=>{
    integrityStatus.className="z3h3-integrity-status z3h3-note";integrityStatus.textContent="Checking reusable Library and workflow state…";
    const [library,presets]=await Promise.all([H3PackAPI.integrity(),refreshCastPresetCache()]);
    describeIssues(library,castStateIntegrity(body,presets));
  };
  const repairIntegrity=async()=>{
    if(!globalThis.confirm?.("Repair Creator Palette state integrity?\n\nA rollback ZIP is created before reusable Library changes. Missing/deleted reusable Cast links will be unlinked from this workflow while preserving the workflow-local character data."))return;
    integrityStatus.className="z3h3-integrity-status z3h3-note";integrityStatus.textContent="Creating rollback backup and repairing state…";
    const result=await H3PackAPI.repairIntegrity(),presets=await refreshCastPresetCache();
    const workflowChanged=syncBodyFromCastPresets(body,presets,{commit:false});
    if(workflowChanged)body.commitData?.();
    const workflow=castStateIntegrity(body,presets);describeIssues(result.report,workflow);
    const count=Array.isArray(result.changes)?result.changes.length:0;
    if(count)integrityStatus.textContent+=` Repaired ${count} reusable Library item${count===1?"":"s"}${result.backup?` · rollback ${result.backup}`:""}.`;
    window.dispatchEvent?.(new CustomEvent("z3-h3-pack-changed",{detail:{kind:"integrity",source:"settings"}}));
    body.refreshAll?.();
  };
  integrityActions.append(button("Check integrity",checkIntegrity,"z3h3-btn"),button("Repair Library + workflow",repairIntegrity,"z3h3-btn primary"));
  host.append(section("State integrity",el("div","z3h3-note","Detects duplicate IDs/handles, stale Cast links, duplicate starter records and broken local thumbnails. Repair never restores deleted starter packs or silently substitutes a different character for a missing link."),integrityActions,integrityStatus));

  // One front door onto the inference paths Creator already has. These buttons
  // deliberately reuse setTurbo + turbo_lead_in rather than inventing a second
  // sampler/profile state machine.
  const weightProfile=h3SelectedModelProfile(models),profileSection=section("Inference profile"),profileNote=el("div","z3h3-note","Choose the selected base checkpoint for maximum prompt authority, the Turbo adapter for maximum speed, or a hybrid that lets base weights establish the opening steps before Turbo finishes the same schedule."),modelProfileNote=el("div",`z3h3-note${weightProfile.hasConvRot?" good":""}`,weightProfile.guidance),profileActions=el("div","z3h3-setting-profile-actions");
  const profileButtons={},profileStatus=el("div","z3h3-profile-status");
  const turboState=()=>S.turboAdapterState(body.data,body.target);
  const adoptDetected=()=>{const turbo=body.data.turbo||(body.data.turbo=S.DEFAULT_TURBO()),state=turboState();if(!turbo.lora&&state.detectedName){turbo.lora=state.detectedName;body.commitData?.(false);}return turbo;};
  const refreshProfiles=async()=>{let lead=0;try{lead=Number((await H.readSettings())?.settings?.turbo_lead_in||0);}catch{}const turbo=body.data.turbo||S.DEFAULT_TURBO(),adapter=turboState(),manual=!turbo.on&&!turbo.lora&&!!adapter.detectedName,mode=manual?"manual":!turbo.on?"full":(lead>0&&turbo.lora&&!turbo.merged?"hybrid":"turbo"),sampler=String(body.widgets?.sampler_name?.value||"res_multistep"),scheduler=String(body.widgets?.scheduler?.value||"simple"),steps=Number(body.widgets?.steps?.value||20),sampling=`${sampler} / ${scheduler} · ${steps} steps`,baseName=weightProfile.allConvRot?weightProfile.formatLabel:"Base model";for(const [key,node] of Object.entries(profileButtons))node.classList.toggle("active",key===mode);if(turbo.on&&turbo.merged)profileStatus.textContent=`Full Turbo is active through the merged distillation checkpoint · ${sampling}. Hybrid is unavailable because merged weights cannot be switched mid-schedule.`;else if(turbo.on&&turbo.lora)profileStatus.textContent=`${mode==="hybrid"?"Hybrid base → Turbo":"Turbo adapter"} is active with ${filename(turbo.lora)} · ${sampling}${sampler==="euler"&&scheduler==="beta"?" · Turbo sampling defaults":" · custom sampling preserved"}. ${weightProfile.hasConvRot?"The underlying INT8 ConvRot checkpoint does not change the adapter's Turbo preset.":""}`.trim();else if(manual)profileStatus.textContent=`Detected active Turbo/Distillation LoRA: ${filename(adapter.detectedName)}. It is being applied as a normal LoRA, but Turbo sampler/steps are not enabled. Choose Full Turbo or Hybrid to configure it automatically, or ${baseName} to remove it.`;else if(turbo.lora)profileStatus.textContent=`Turbo adapter configured: ${filename(turbo.lora)} · currently off · ${sampling}. Choose Full Turbo or Hybrid to enable it.`;else if(turbo.merged)profileStatus.textContent=`Merged distillation checkpoint configured · currently off · ${sampling}. Choose Full Turbo to enable its sampling profile.`;else profileStatus.textContent=`${baseName} weights are active · ${sampling}. ${weightProfile.hasConvRot?"ConvRot is already handled by ComfyUI's loader; no Turbo adapter or special Turbo steps are required.":"No Turbo adapter is configured or active."}`;profileStatus.className=`z3h3-profile-status${manual?" warn":turbo.on||weightProfile.hasConvRot?" good":""}`;};
  const requireTurbo=()=>{const turbo=adoptDetected();if(turbo.lora||turbo.merged)return turbo;profileStatus.textContent="No Turbo adapter was found. Open Configure Turbo adapter and select the installed distillation LoRA; merely adding a non-Turbo LoRA does not change the inference profile.";profileStatus.className="z3h3-profile-status warn";return null;};
  profileButtons.full=button(weightProfile.buttonLabel,async()=>{adoptDetected();body.setTurbo?.(false);await saveMachineSettings({turbo_lead_in:0});await refreshProfiles();},"z3h3-btn");
  profileButtons.turbo=button("Full Turbo",async()=>{const turbo=requireTurbo();if(!turbo)return;body.setTurbo?.(true);await saveMachineSettings({turbo_lead_in:0});await refreshProfiles();},"z3h3-btn");
  profileButtons.hybrid=button("Hybrid · base → Turbo",async()=>{const turbo=requireTurbo();if(!turbo)return;if(!turbo.lora||turbo.merged){profileStatus.textContent="Hybrid needs a switchable Turbo LoRA; a merged distillation checkpoint cannot be removed for the base-weight lead-in.";profileStatus.className="z3h3-profile-status warn";return;}body.setTurbo?.(true);await saveMachineSettings({turbo_lead_in:2});await refreshProfiles();},"z3h3-btn");
  const lightxRecipe=button("Apply LightX2V v1.0 · 4-step",async()=>{const turbo=requireTurbo();if(!turbo)return;const name=turbo.lora||turboState().detectedName;if(S.turboPreset(name).recipe!=="lightx2v-v1"){profileStatus.textContent="This exact recipe is only applied to a selected LightX2V 4-step v1.0 adapter. Older or generically named Turbo LoRAs keep their existing tuning.";profileStatus.className="z3h3-profile-status warn";return;}turbo.quality="draft";body.setTurbo?.(true);setWidget(body,"steps",4);setWidget(body,"cfg",1);setWidget(body,"shift_video",6);setWidget(body,"shift_audio",3);body.commitData?.();await saveMachineSettings({turbo_lead_in:0});await refreshProfiles();},"z3h3-btn primary");
  const configureTurbo=button("Configure Turbo adapter…",()=>launchOutsideDrawer(()=>body.openLoras?.({focusTurbo:true})),"z3h3-btn");
  profileActions.append(profileButtons.full,profileButtons.turbo,profileButtons.hybrid);profileSection.append(profileActions,profileNote,modelProfileNote,profileStatus,row(configureTurbo,lightxRecipe),el("div","z3h3-note","LightX2V v1.0 is opt-in and filename-gated. It applies the confirmed 4-step, CFG 1.0, video shift 6 and audio shift 3 recipe; existing Turbo adapters and custom sampler/scheduler choices are otherwise untouched."));host.append(profileSection);refreshProfiles();

  const archive=body.data.archive_stitch||(body.data.archive_stitch=S.DEFAULT_ARCHIVE_STITCH()),archiveOn=check(archive.enabled),archiveFolder=input("text",archive.folder||"h3_context"),archivePattern=input("text",archive.pattern||"clip_*.safetensors"),archiveFirst=input("number",archive.first_clip??1),archiveLast=input("number",archive.last_clip??0),archiveContext=select([[5,"5 frames"],[22,"22 frames · normal"],[39,"39 frames"],[56,"56 frames"]],Number(archive.context_length||22)),archiveFps=input("number",archive.fps||24),archiveState=el("div","z3h3-note");
  archiveFirst.min=1;archiveFirst.step=1;archiveLast.min=0;archiveLast.step=1;archiveFps.min=1;archiveFps.max=240;archiveFps.step=.001;
  const applyArchive=(commit=true)=>{body.data.archive_stitch={enabled:archiveOn.checked,folder:archiveFolder.value.trim()||"h3_context",pattern:archivePattern.value.trim()||"clip_*.safetensors",first_clip:Math.max(1,Math.trunc(Number(archiveFirst.value)||1)),last_clip:Math.max(0,Math.trunc(Number(archiveLast.value)||0)),context_length:Number(archiveContext.value)||22,fps:Number(archiveFps.value)||24};archiveState.textContent=archiveOn.checked?"ARCHIVE ASSEMBLY MODE IS ON — Queue decodes/stitches the selected saved Motion Context clips and bypasses Qwen, the DiT and sampling. Your authored shots stay untouched.":"Off — normal Creator generation / continuation is active.";archiveState.className=`z3h3-note${archiveOn.checked?" warn":""}`;if(commit)body.commitData?.();};
  for(const control of [archiveOn,archiveFolder,archivePattern,archiveFirst,archiveLast,archiveContext,archiveFps])control.addEventListener("change",()=>applyArchive(true));applyArchive(false);
  const archiveSection=section("H3 Motion Context archive stitcher",el("div","z3h3-note","Compatibility for numbered h3_motion_context_av_v1 .safetensors made by NikoDemon80/noEmbryo-style Motion Context workflows. Creator already handles its own generated continuation seams, so this mode is only for assembling external saved archives — no duplicate seam engine."),field("Archive stitch mode",archiveOn,"Use this queue as final assembly instead of generating new frames."),field("Folder",archiveFolder,"Absolute path or path relative to ComfyUI/output."),field("Filename pattern",archivePattern),row(field("First clip",archiveFirst),field("Last clip · 0 = all",archiveLast)),row(field("Context dissolve",archiveContext,"Video dissolve + synchronized equal-power audio crossfade."),field("FPS",archiveFps)),archiveState);host.append(archiveSection);

  const capability=section("MiniMax H3 capability map"),caps=el("div","z3h3-capability-grid");for(const [name,detail] of [["All five H3 video modes","T2VA · I2VA · L2VA · FL2VA · full Ref2VA — Director shows the intent and the actual route derived from real inputs."],["Native multi-reference","Up to 9 images · 3 videos · 3 audio refs — already routed through H3 Ref2VA."],["Timeline Director","Optional floating Director adds timed beats, cast photos, reusable environment sets, camera paths and route checks without expanding the node."],["Guided Ref2VA editing","Insertion, replacement, targeted edits, relighting, performance transfer and continuation share the existing compiler instead of a second workflow."],["First / last frame","Native I2VA/L2VA/FL2VA constraints + real timeline continuation — already integrated."],["Motion Context archives","External numbered AV archive assembly — integrated above."],["High resolution","Native first pass plus Creator's local two-pass regeneration path — already integrated."],["Model path","Full base weights, full Turbo, or hybrid base→Turbo — same sampler architecture, selectable above."],["Advanced local execution","GGUF, Multi-GPU placement, attention backend, caches, Spectrum, Chunk FFN, FP16 accumulation and optional H3-specific memory/sparse providers remain independently selectable."]]){const card=el("div","z3h3-capability-card");card.append(el("b",null,name),el("small",null,detail));caps.append(card);}capability.append(caps);host.append(capability);

  const aspectOptions=[["16:9","16:9 Landscape"],["9:16","9:16 Portrait"],["1:1","1:1 Square"],["4:3","4:3"],["3:4","3:4"],["21:9","21:9 Cinema"]];if(!aspectOptions.some(([value])=>value===body.data.aspect))aspectOptions.push([body.data.aspect,`${body.data.aspect} Custom`]);
  const aspect=select(aspectOptions,body.data.aspect||"16:9"),aspectSource=select([["pill","Use aspect preset / custom ratio"],["auto","Auto from first suitable keyframe/footage"],...S.allKnownAssets(body.data).filter(a=>a.kind!=="audio").map(a=>[a.handle,`@${a.handle} · ${filename(a.filename)}`])],body.data.aspect_source||"pill"),target=select(videoResolutionOptions(body.data.aspect,body.data.short_edge),Number(body.data.short_edge||S.NATIVE_SHORT_EDGE)),upscale=select([["two_pass","Two-pass above sampler edge"],["direct","Direct one-pass at final size"]],body.data.upscale||"two_pass"),first=select(firstPassResolutionOptions(body.data.aspect,body.data.short_edge,body.data.sample_edge),Number(body.data.sample_edge||768)),den=input("number",body.data.refine_denoise??.5),faceOn=check(body.data.face?.on),faceCanvas=select([[384,"384"],[448,"448"],[512,"512"],[576,"576"],[640,"640"],[704,"704"],[768,"768"]],body.data.face?.canvas||512),faceDen=input("number",body.data.face?.denoise??.45),canvasState=el("div","z3h3-note good");
  den.min=.1;den.max=.9;den.step=.05;faceDen.min=.1;faceDen.max=.9;faceDen.step=.05;
  const replaceOptions=(control,options,value)=>{control.replaceChildren(...options.map(([v,label])=>{const option=document.createElement("option");option.value=v;option.textContent=label;if(String(v)===String(value))option.selected=true;return option;}));};
  const refreshCanvas=()=>{const data=body.data;aspect.value=data.aspect;aspectSource.value=data.aspect_source;replaceOptions(target,videoResolutionOptions(data.aspect,data.short_edge),data.short_edge);replaceOptions(first,firstPassResolutionOptions(data.aspect,data.short_edge,data.sample_edge),data.sample_edge);upscale.value=data.upscale;den.value=data.refine_denoise;const resolved=describeH3Resolution(data.aspect,data.short_edge,{upscale:data.upscale,sampleEdge:data.sample_edge}),adaptive=data.aspect_source!=="pill";first.disabled=data.upscale==="direct";den.disabled=!resolved.twoPass;canvasState.textContent=adaptive?`Final canvas uses the selected source's aspect at a ${resolved.target.shortEdge}px short edge${resolved.twoPass?`, sampled first at ${resolved.first.shortEdge}px`:" in one pass"}. Exact dimensions are resolved from that media when queued.`:resolved.twoPass?`Queue contract: ${resolved.first.width}×${resolved.first.height} first pass → ${resolved.target.width}×${resolved.target.height} final.`:`Queue contract: ${resolved.target.width}×${resolved.target.height} final in one pass.`;};
  const applyCanvas=()=>{body.data.aspect=aspect.value;body.data.aspect_source=aspectSource.value;body.data.short_edge=Number(target.value);body.data.upscale=upscale.value;body.data.sample_edge=Number(first.value);body.data.refine_denoise=Number(den.value);body.data.face={on:faceOn.checked,canvas:Number(faceCanvas.value),denoise:Number(faceDen.value)};body.commitData?.();refreshCanvas();};
  aspect.addEventListener("change",()=>{aspectSource.value="pill";applyCanvas();});
  for(const control of [aspectSource,target,upscale,first,den,faceOn,faceCanvas,faceDen])control.addEventListener("change",applyCanvas);
  refreshCanvas();
  host.append(section("Canvas / quality / face repair",field("Final aspect preset",aspect,"Choosing a preset pins it for the queue. Choose an adaptive source below only when that media should determine the aspect."),field("Aspect source",aspectSource),field("Final output resolution",target,"This is the delivered video canvas, and is the same setting as the node's Resolution preset."),field("Resolution sampler / first pass",first,"Only the first pass in two-pass mode. It can never exceed the final target or H3's native 768px edge."),field("High-resolution mode",upscale),field("Second-pass denoise",den),canvasState,field("Face repair",faceOn,"Requires a SAM3 checkpoint selected under Models / Devices."),field("Face repair canvas",faceCanvas),field("Face repair denoise",faceDen)));

  const controls={};
  const spec=[["steps","Steps","number"],["cfg","CFG · H3 default 1.0","number"],["sampler_name","Sampler","select"],["scheduler","Scheduler","select"],["attention","Attention backend","select"],["block_cache","FirstBlockCache","select"],["spectrum","Spectrum","check"],["spectrum_blend","Spectrum blend","number"],["chunk_ffn","Chunk FFN · KJNodes","check"],["fp16_accumulation","FP16 accumulation · KJNodes","check"]];
  const sampling=section("Sampling & acceleration",el("div","z3h3-note good","Workflow settings — these values are saved with this node and restored when the workflow reloads. The machine-preference section below is separate."));
  for(const [name,label,kind] of spec){const widget=body.widgets?.[name];if(!widget)continue;let control;if(kind==="select")control=select(widgetOptions(widget),widget.value);else if(kind==="check")control=check(widget.value);else control=input("number",widget.value);controls[name]=control;const apply=()=>setWidget(body,name,kind==="check"?control.checked:kind==="number"?Number(control.value):control.value);control.addEventListener("change",apply);sampling.append(field(label,control));}
  const turboSteps=[["draft",`Draft · ${S.TURBO_STEPS.draft} steps`],["medium",`Balanced · ${S.TURBO_STEPS.medium} steps`],["good",`High · ${S.TURBO_STEPS.good} steps`]],turbo=body.data.turbo||(body.data.turbo=S.DEFAULT_TURBO()),turboOn=check(turbo.on),turboQuality=select(turboSteps,turbo.quality),turboInfo=el("div","z3h3-note",turbo.lora?`Turbo adapter: ${filename(turbo.lora)} · enabling Turbo initially selects Euler/Beta, but sampler and scheduler can then be changed and are preserved.`:"No Turbo LoRA selected. Choose one in LoRA Manager if you use a distillation adapter.");
  turboOn.addEventListener("change",()=>body.setTurbo?.(turboOn.checked));turboQuality.addEventListener("change",()=>{body.data.turbo.quality=turboQuality.value;if(body.data.turbo.on)setWidget(body,"steps",S.TURBO_STEPS[turboQuality.value]);body.commitData?.();});
  sampling.append(field("Turbo on",turboOn,"Turning this on once selects the Turbo step preset plus Euler/Beta and saves your previous sampling values for restoration."),field("Turbo step preset",turboQuality,"Changes only the step count after Turbo is enabled. Sampler and scheduler remain independently selectable."),turboInfo);
  const advanced=document.createElement("details");advanced.className="z3h3-setting-details";advanced.append(el("summary",null,"Advanced sigma shifts"));const shiftVideo=input("number",body.widgets?.shift_video?.value??12),shiftAudio=input("number",body.widgets?.shift_audio?.value??3);shiftVideo.step=shiftAudio.step=.01;shiftVideo.addEventListener("change",()=>setWidget(body,"shift_video",Number(shiftVideo.value)));shiftAudio.addEventListener("change",()=>setWidget(body,"shift_audio",Number(shiftAudio.value)));advanced.append(field("Video sigma shift",shiftVideo,"H3 release default 12. Not a quality slider."),field("Audio sigma shift",shiftAudio,"H3 release default 3. Not a quality slider."));sampling.append(advanced);host.append(sampling);

  const costReadout=el("div","z3h3-workload-readout"),costDetail=el("div","z3h3-workload-runs"),costWarnings=el("div","z3h3-note");let runtimeAvailability=null;
  const refreshCost=()=>{const plan=planH3Workload(body.data,{steps:body.widgets?.steps?.value});if(plan.bypass){costReadout.textContent="Archive assembly bypasses Qwen, H3 DiT sampling and VAE generation.";costDetail.replaceChildren();costWarnings.textContent="Only decode, dissolve, audio crossfade and final mux remain.";return;}costReadout.textContent=`${formatWorkloadRatio(plan.attentionRatio)} · ${plan.scheduledEvaluations.toFixed(1)} denoise-weighted step equivalents · ${plan.runs.length} generated pass${plan.runs.length===1?"":"es"}`;costDetail.replaceChildren(...plan.runs.map((run)=>{const card=el("div","z3h3-workload-run");card.append(el("b",null,`Pass ${run.index+1} · ${run.seconds.toFixed(2)}s · ${run.frames}f`),el("small",null,`${run.first.total.toLocaleString()} target rows/step${run.refineFraction?` → ${run.target.total.toLocaleString()} refine rows/step`:""}${run.faceEnabled?` · ${run.faceRows.total.toLocaleString()} face rows/step`:""}`));return card;}));const notes=[];if(plan.adaptive)notes.push("Adaptive aspect can change the exact row count when media is probed at queue time.");notes.push("This is a deterministic floor: prompt, keyframe and reference rows add to the packed sequence; maximum-size references can dominate cost.");if(body.data?.face?.on)notes.push("Face repair adds a separate partial-denoise H3 pass.");if(plan.resolution?.twoPass)notes.push("Two-pass output adds target-canvas regeneration after the first pass.");const devices=body.data?.models?.devices||{};if(body.widgets?.spectrum?.value&&(devices.fl2va||devices.ref2va))notes.push("Spectrum forecasts are not supported on a MultiGPU-patched H3 model; use one model device or switch Spectrum off.");if(String(body.widgets?.block_cache?.value||"")==="easy")notes.push("H3 audio with EasyCache requires the Aug 7, 2026 ComfyUI audio-carry fix; update ComfyUI if sound is corrupted.");notes.push(/(?:int8.*convrot|convrot.*int8)/i.test(String(body.data?.models?.vae||""))?"INT8 ConvRot H3 video VAE selected; current ComfyUI uses its quantized decoder path.":"Current ComfyUI supports the optional INT8 ConvRot H3 video VAE path, which can reduce decode time on supported hardware.");if(runtimeAvailability){const installed=Object.entries(runtimeAvailability.providers||{}).filter(([,on])=>on).map(([name])=>name.replaceAll("_"," "));notes.push(installed.length?`Detected accelerators: ${installed.join(", ")}. Requested controls still fail closed if a provider disappears before queue.`:"No optional accelerator provider was detected; normal Creator execution remains available.");}costWarnings.textContent=notes.join(" ");};
  const nativeOnePass=button("Set native 768 one-pass",()=>{body.data.short_edge=768;body.data.sample_edge=768;body.data.upscale="direct";body.commitData?.();refreshCanvas();refreshCost();},"z3h3-btn");
  const workloadSection=section("H3 pre-queue workload",el("div","z3h3-note good","Uses ComfyUI's exact H3 17k+5 temporal packing, 32-pixel video patch grid and 40 Hz stereo audio rows. It reports relative transformer attention work, not invented wall-clock seconds."),costReadout,costDetail,costWarnings,row(nativeOnePass));host.append(workloadSection);for(const control of [...Object.values(controls),aspect,aspectSource,target,upscale,first,den,faceOn,faceCanvas,faceDen,turboOn,turboQuality,archiveOn])control.addEventListener("change",()=>queueMicrotask(()=>refreshCost()));for(const control of [profileActions,lightxRecipe])control.addEventListener("click",()=>queueMicrotask(()=>refreshCost()));refreshCost();H.acceleratorStatus().then(result=>{runtimeAvailability=result;refreshCost();}).catch(()=>refreshCost());

  const memoryWidget=body.widgets?.h3_memory,sparseWidget=body.widgets?.h3_sparse,edgeWidget=body.widgets?.h3_sparse_edges;
  if(memoryWidget&&sparseWidget&&edgeWidget){
    const memory=select([["off","Off · normal Creator execution"],["precision","Preserve precision · bounded memory"],["auto","Auto acceleration · FP8 when supported"]],memoryWidget.value),sparse=select([["off","Off · dense attention"],["full","100% video KV · backend baseline"],["conservative","50% video KV · conservative"],["balanced","30% video KV · upstream default"],["aggressive","20% video KV · aggressive"]],sparseWidget.value),edges=check(edgeWidget.value),state=el("div","z3h3-note");
    let availability=null;
    const requested=()=>memory.value!=="off"||sparse.value!=="off";
    const refreshOptimization=()=>{edges.disabled=sparse.value==="off";const installed=availability?.memory&&availability?.sparse;if(availability&&!installed){state.textContent=requested()?"Requested, but the H3-Optimizations companion is not fully installed. Queueing will stop with a clear error instead of silently rendering without it.":"Optional companion not installed. These controls remain off and normal Creator execution is unchanged.";state.className=`z3h3-note${requested()?" warn":""}`;}else if(installed){state.textContent=`H3-Optimizations detected · memory ${memory.value} · sparse ${sparse.value}${sparse.value!=="off"?` · edge detail ${edges.checked?"on":"off"}`:""}.`;state.className="z3h3-note good";}else{state.textContent="Checking whether the H3-Optimizations companion is installed…";state.className="z3h3-note";}};
    const conflict=(name,value)=>{const memoryValue=name==="h3_memory"?value:memory.value,sparseValue=name==="h3_sparse"?value:sparse.value,attention=String(body.widgets?.attention?.value||"default"),chunk=!!body.widgets?.chunk_ffn?.value;if(memoryValue!=="off"&&chunk)return "Turn off KJNodes Chunk FFN first. Both controls patch the H3 MLP, so stacking them is unsafe.";if(attention==="sage"&&(memoryValue==="auto"||sparseValue!=="off"))return "KJNodes Sage already owns the H3 attention forward. Choose Default/Kitchen, or use Preserve precision with sparse attention off.";return "";};
    const applySelect=(name,control)=>{const problem=conflict(name,control.value);if(problem){control.value=String(body.widgets?.[name]?.value||"off");state.textContent=problem;state.className="z3h3-note warn";return;}setWidget(body,name,control.value);refreshOptimization();};
    memory.addEventListener("change",()=>applySelect("h3_memory",memory));sparse.addEventListener("change",()=>applySelect("h3_sparse",sparse));edges.addEventListener("change",()=>{setWidget(body,"h3_sparse_edges",edges.checked);refreshOptimization();});
    const install=button("Open Zironic/H3-Optimizations",()=>globalThis.open?.("https://github.com/Zironic/H3-Optimizations","_blank","noopener"),"z3h3-btn");
    const optimization=document.createElement("details");optimization.className="z3h3-setting-section z3h3-optional-provider";optimization.open=requested();
    const optimizationSummary=el("summary",null,"Optional · H3-Optimizations by Zironic");
    optimization.append(optimizationSummary,el("div","z3h3-note","Convenience controls for the separately installed Zironic/H3-Optimizations node pack. Its implementation and optimization work remain upstream-owned. Everything here is optional and off by default; without that pack, normal Creator execution is unchanged. Memory Preserve keeps BF16/FP16 weights floating while bounding MLP work. Memory Auto may use FP8 E4M3 on supported weights, reducing VRAM and sometimes improving speed while potentially changing output."),field("H3 memory path",memory,"4096-row bounded execution. Do not combine with KJNodes Chunk FFN."),field("Sparse video attention",sparse,"Lower percentages keep fewer pure target-video KV tiles. Text, references, audio, non-video queries and boundary tiles remain dense."),field("Protect first / last steps",edges,"Adds 30 percentage points to the selected video KV budget for the first two and final two sampler steps, capped at 100%."),state,install);host.append(optimization);refreshOptimization();
    H.acceleratorStatus().then(result=>{availability=result?.h3_optimizations||{};refreshOptimization();}).catch(error=>{availability={memory:false,sparse:false};state.textContent=`Could not check H3-Optimizations: ${error.message||error}`;state.className="z3h3-note warn";});
  }

  const shortcuts=section("Optional authoring tools"),directorShortcut=check(body.uiPrefs?.show_director_shortcut!==false),refineShortcut=check(body.uiPrefs?.show_refine_shortcut),prestageShortcut=check(body.uiPrefs?.show_prestage_shortcut);
  directorShortcut.addEventListener("change",()=>body.setUIPref?.("show_director_shortcut",directorShortcut.checked));refineShortcut.addEventListener("change",()=>body.setUIPref?.("show_refine_shortcut",refineShortcut.checked));prestageShortcut.addEventListener("change",()=>body.setUIPref?.("show_prestage_shortcut",prestageShortcut.checked));
  shortcuts.append(row(button("Open H3 Timeline Director",()=>launchOutsideDrawer(()=>body.openDirector?.()),"z3h3-btn primary"),field("Show Director shortcut on node",directorShortcut,"Optional floating timeline; never expands the node itself.")),row(button("Open Local Refiner",()=>launchOutsideDrawer(()=>body.openRefine?.()),"z3h3-btn"),field("Show Refine shortcut on node",refineShortcut)),row(button("Create Pre-Stage node",()=>{close();body.spawnPreStage?.();},"z3h3-btn"),field("Show Pre-Stage shortcut on node",prestageShortcut)),el("div","z3h3-note","Director, Refiner and Pre-Stage remain available here even when toolbar shortcuts are hidden. Director opens as a resizable/minimizable dock outside the node so the prompt editor keeps its space."));host.append(shortcuts);
  return host;
}

export async function openH3SettingsDrawer(body=null){
  close();
  const shade=el("div","z3h3-right-shade"),drawer=el("aside","z3h3-right-drawer z3h3-setup-drawer v3133");openDrawer=shade;
  const head=el("header","z3h3-right-head"),copy=el("div");copy.append(el("b",null,"Creator Palette Settings"),el("small",null,"Workflow state · reusable Library · local UI preferences stay deliberately separate"));head.append(copy,button("Close",close));
  const content=el("div","z3h3-right-content z3h3-settings-v3133");
  const names=["Creator","Library","Cast","References","Variations","Appearance","Performance","Advanced","About"],buckets={},nav=el("nav","z3h3-settings-section-nav");
  const descriptions={Creator:"Core authoring and workflow controls",Library:"Reusable content, integrity and recovery",Cast:"Character workspace behavior",References:"Reusable and per-shot reference tools",Variations:"Sampling, auditions and prompt variation",Appearance:"Theme and local editor presentation",Performance:"Preview, quality and acceleration",Advanced:"Specialized compatibility and technical tools",About:"Project, version and licensing"};
  for(const name of names){const category=el("section","z3h3-settings-category"),title=el("div","z3h3-settings-category-head"),mount=el("div","z3h3-settings-category-body");title.append(el("h2",null,name),el("small",null,descriptions[name]));category.append(title,mount);category.dataset.settingsCategory=name.toLowerCase();buckets[name]={category,mount};content.append(category);const jump=button(name,()=>category.scrollIntoView?.({behavior:"smooth",block:"start"}),"z3h3-settings-nav-btn");nav.append(jump);}
  content.prepend(nav);
  const workflow=creatorSetup(body),place=(name,node)=>{if(node)buckets[name]?.mount.append(node);};
  for(const child of [...(workflow.children||[])]){
    const title=String(child.querySelector?.("h3")?.textContent||child.querySelector?.("summary")?.textContent||"").toLowerCase();
    let target="Creator";
    if(title.includes("state integrity"))target="Library";
    else if(title.includes("preview")||title.includes("canvas / quality")||title.includes("pre-queue workload")||title.includes("optimizations"))target="Performance";
    else if(title.includes("inference profile")||title.includes("sampling & acceleration"))target="Variations";
    else if(title.includes("archive stitcher")||title.includes("capability map"))target="Advanced";
    else if(title.includes("optional authoring")||title.includes("model routing"))target="Creator";
    place(target,child);
  }

  // Library, Cast and References are first-class destinations, not hidden secondary dialogs.
  place("Library",section("Library workspace",el("div","z3h3-note","Pack imports, Trash, stable-ID merge/append operations and rollback-protected repairs live in the reusable Library. Global Undo records supported Library mutations as transactions."),row(button("Open Library",()=>launchOutsideDrawer(()=>body?.openPromptLibrary?.(body?.uiPrefs?.last_library_tab||"personal")),"z3h3-btn primary"))));
  place("Cast",section("Cast Studio 2",el("div","z3h3-note","Gallery dimensions, selected group, gallery/list mode, Inspector disclosure state and optional search state are local UI preferences. Character records themselves remain in the reusable Library/workflow state."),button("Open Cast Studio",()=>launchOutsideDrawer(()=>body?.openCast?.()),"z3h3-btn primary")));
  place("References",section("Reference Workspace",el("div","z3h3-note","Reusable Reference records use stable IDs. Workflow-local reference attachments remain workflow data; workspace presentation stays local."),button("Open Reference Workspace",()=>launchOutsideDrawer(()=>body?.openReferences?.()),"z3h3-btn primary")));

  const themeStudio=createH3ThemeStudio(body);place("Appearance",themeStudio.root);
  const editorPrefs=section("Editor presentation",el("div","z3h3-note","These controls are browser-local presentation preferences. They are not saved into Creator workflow JSON and never persist caret, focus, hover, selection, or temporary autocomplete state."));
  if(body){
    const font=input("number",Number(body.uiPrefs?.editor_font_size||15)),zoom=input("number",Number(body.uiPrefs?.editor_zoom||1)),acWidth=input("number",Number(body.uiPrefs?.autocomplete_width||420)),acHeight=input("number",Number(body.uiPrefs?.autocomplete_max_height||320));
    font.min=11;font.max=26;font.step=1;zoom.min=.75;zoom.max=1.6;zoom.step=.05;acWidth.min=300;acWidth.max=680;acWidth.step=10;acHeight.min=180;acHeight.max=620;acHeight.step=10;
    const save=(key,control,convert=Number)=>()=>body.setUIPref?.(key,convert(control.value));
    font.addEventListener("change",save("editor_font_size",font));zoom.addEventListener("change",save("editor_zoom",zoom));acWidth.addEventListener("change",save("autocomplete_width",acWidth));acHeight.addEventListener("change",save("autocomplete_max_height",acHeight));
    editorPrefs.append(field("Editor font size",font,"11–26 px before local zoom."),field("Editor zoom",zoom,"Visual text scaling only; Editor 2 DOM/caret architecture is untouched."),field("Autocomplete width",acWidth,"Compact semantic popup width in pixels."),field("Autocomplete max height",acHeight,"Maximum semantic popup height in pixels."));
  }
  place("Appearance",editorPrefs);
  place("Advanced",section("State-domain contract",el("div","z3h3-note good","Generation/workflow state is serialized only in creator_data. Reusable records live in the server-side Library. Harmless UI presentation preferences live only in browser localStorage. Global history bridges workflow + Library mutations transactionally without merging those storage domains.")));
  const about=section("MiniMax H3 Creator Palette",el("div","z3h3-settings-about-brand","by z3rofeels"),row(button("GitHub Projects",()=>globalThis.open?.("https://github.com/z3rofeels","_blank","noopener"),"z3h3-btn primary")),field("Version",el("span","z3h3-settings-static","3.14.1")),el("div","z3h3-note","Creator Palette is distributed under GPL-3.0. Third-party components retain their own notices; see LICENSE and THIRD_PARTY_NOTICES.md in the installed package."));place("About",about);

  const progress=el("div","z3h3-progress");progress.append(el("i"));buckets.Creator.mount.append(progress);
  drawer.append(head,content);shade.append(drawer);document.body.append(shade);applyCreatorAppearance(shade,body?.node||null);shade._z3Cleanup=()=>themeStudio.cleanup?.();shade.addEventListener("mousedown",event=>{if(event.target===shade)close();});
  try{
    const response=await H.readSettings(),stored=response.settings||{},controls={};progress.remove();
    const status=el("div","z3h3-setting-status good","Machine preferences save automatically to this ComfyUI install.");let timer=0,serial=0;
    const collect=()=>{const patch={};for(const [key,control] of Object.entries(controls))patch[key]=control.type==="checkbox"?control.checked:control.type==="number"?Number(control.value):control.value;return patch;};
    const saveNow=async()=>{const mine=++serial;clearTimeout(timer);status.textContent="Saving machine preferences…";status.className="z3h3-setting-status";try{await saveMachineSettings(collect());if(mine!==serial)return;status.textContent="Saved. The next queue uses the current values.";status.classList.add("good");body?.refreshAll?.();await body?.previewSidecar?.refreshFromServer?.({autoConfigure:true});await body?.seedHunt?.refreshFromSettings?.();}catch(error){if(mine!==serial)return;status.textContent=error.message||String(error);status.classList.add("bad");}};
    const queueSave=()=>{clearTimeout(timer);timer=setTimeout(saveNow,180);};
    const groupTarget={"Experience":"Creator","Optional beta":"Advanced","Prompting":"Creator","Rendering":"Performance","Output":"Creator"};
    for(const group of GROUPS){const groupSection=section(group);for(const [key,value] of Object.entries(stored)){if(key==="model_defaults"||key==="prestage_model_defaults")continue;const spec=SPECS[key]||[key.replaceAll("_"," "),"",typeof value==="boolean"?"toggle":typeof value==="number"?"number":"text","Other"];if(spec[3]!==group)continue;const control=input(spec[2]==="toggle"?"checkbox":spec[2],value);controls[key]=control;if(key==="video_crf"){control.min=0;control.max=51;control.step=1;}if(key==="turbo_lead_in"){control.min=0;control.max=4;control.step=1;}if(control.type==="checkbox")control.addEventListener("change",saveNow);else{control.addEventListener("input",queueSave);control.addEventListener("change",saveNow);}groupSection.append(field(spec[0],control,spec[1]));}if(groupSection.children.length>1)place(groupTarget[group]||"Advanced",groupSection);}
    const foot=el("footer","z3h3-right-foot z3h3-settings-brand-foot");foot.append(status,button("Done",close,"z3h3-btn primary"));drawer.append(foot);
  }catch(error){buckets.Creator.mount.append(el("div","z3h3-error",error.message||String(error)));}
}
