import { H3_SCENE_SLOT_ORDER, categoryMeta } from "./h3_prompt_categories.js";
import { listSceneSlotPresets } from "./h3_scene_stack.js";
import { createSemanticAutocomplete } from "./h3_semantic_autocomplete.js";

let cachePromise=null,cleanup=null;
const ALIASES=Object.freeze({location:["location","locations","where","place","environment","scene"],wardrobe:["clothing","clothes","wardrobe","outfit","look","fashion"],prop:["prop","props","object","objects","item","items"],action:["action","actions","motion","move","movement","do"],camera:["camera","shot","framing","lens","movement","cinematography"],lighting:["light","lighting","illumination","exposure"],dialogue:["dialogue","dialog","speech","speaking","say","voice"],ambience:["audio","ambience","ambient","foley","sound","sounds","environment sound"],music:["music","score","soundtrack"]});
function norm(value){return String(value??"").trim().toLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," ");}
function contextAt(text,caret){const source=String(text??""),end=Math.max(0,Math.min(Number(caret)||0,source.length)),before=source.slice(0,end),match=before.match(/(?:^|[\s([{])\$([A-Za-z0-9_ ./'-]{0,72}?)([+-])?$/);if(!match)return null;const query=match[1]||"",suffix=match[2]||"",start=end-query.length-suffix.length-1;return{start,end,query,direction:suffix==="+"?1:suffix==="-"?-1:0};}
function currentPreset(body,slot){return body?.scenePreset?.(slot)||(body?.target!=="global"?body?.data?.scene_palette?.[slot]:null)||null;}
async function allPresets(){if(!cachePromise)cachePromise=Promise.all(H3_SCENE_SLOT_ORDER.map(async(slot)=>({slot,rows:await listSceneSlotPresets(slot)}))).catch((error)=>{cachePromise=null;throw error;});return cachePromise;}
window.addEventListener?.("z3-h3-pack-changed",()=>{cachePromise=null;});
function categoryHay(slot){const meta=categoryMeta(slot);return norm([meta.label,meta.title,...(ALIASES[slot]||[])].join(" "));}
function scoreItem(item,q){if(!q)return item.kind==="category"?100:0;const title=norm(item.title),category=categoryHay(item.slot),hay=norm(`${item.title} ${item.note||""} ${item.subcategory||""} ${item.prompt||""} ${category}`);if(title===q||norm(item.label)===q)return 150;if(category.split(" ").includes(q)||category===q)return 135;if(title.startsWith(q))return 120;if(category.includes(q))return 105;if(title.includes(q))return 90;return hay.includes(q)?60:-1;}
async function itemsFor(body,query){const q=norm(query),groups=await allPresets(),items=[];for(const {slot,rows} of groups){const meta=categoryMeta(slot),current=currentPreset(body,slot),category={key:`scene:${slot}:category`,kind:"category",slot,title:meta.title,label:meta.label,note:current?.title?`Current: ${current.title}`:`Browse ${meta.title.toLowerCase()} presets`,current,color:meta.color,icon:meta.label.slice(0,2),meta:`$${meta.title} · CATEGORY`};const catScore=scoreItem(category,q);if(!q||catScore>=0)items.push({...category,label:meta.title,description:category.note,score:catScore,exact:catScore>=150});if(q){for(const preset of rows||[]){const item={key:`scene:${slot}:${preset.id||preset.title||preset.prompt}`,kind:"preset",slot,title:preset.title||meta.title,label:preset.title||meta.title,note:preset.note||preset.subcategory||"",description:preset.note||preset.prompt||"",subcategory:preset.subcategory||"",prompt:preset.prompt||"",preset,color:meta.color,icon:meta.label.slice(0,2),meta:`${meta.title} · ${preset.subcategory||"PRESET"}`};const score=scoreItem(item,q);if(score>=0)items.push({...item,score,exact:score>=150});}}}return items;}
function replaceCallWithNothing(editor,start,end){editor.setRangeText("",start,end,"end");editor.dispatchEvent(new Event("input",{bubbles:true}));return start;}
export function installSceneAutocomplete(body,editor){cleanup?.();cleanup=createSemanticAutocomplete({domain:"scene",prefix:"$",title:"$ Scene",subtitle:"Search categories + presets · favorites · recent · Enter/Tab insert",body,editor,getContext:contextAt,getItems:itemsFor,emptyText:"No matching scene category or preset",maxItems:16,actionLabel:(item,action)=>action.id==="fixed"&&item.kind==="category"&&!item.current?"Pick":action.label,onCommit:async({snapshot,item,direction})=>{if(item.kind==="preset"){snapshot.body.applyScenePresetAtRange?.(item.slot,item.preset,snapshot.start,snapshot.end,direction);return;}const current=currentPreset(snapshot.body,item.slot);if(current){snapshot.body.applyScenePresetAtRange?.(item.slot,current,snapshot.start,snapshot.end,direction);return;}const anchor=replaceCallWithNothing(snapshot.editor,snapshot.start,snapshot.end);await snapshot.body.openScenePicker?.(item.slot,{onPick:(preset)=>snapshot.body.applyScenePresetAtRange?.(item.slot,preset,anchor,anchor,direction)});}});return()=>{cleanup?.();cleanup=null;};}
export function cleanupSceneAutocomplete(){cleanup?.();cleanup=null;cachePromise=null;}
