import {
  downloadJsonFile,
  pickJsonFile,
  normalizeThemeFilename,
} from "./prompt_palette_shared.js";
import {
  loadTheme, defaultTheme, saveTheme,
  UI_THEME_KEYS, BUILTIN_UI_THEMES, THEME_PACKS, normalizeUiThemeName,
  loadUiThemes, saveUiThemes, loadActiveUiThemeName, saveActiveUiThemeName,
} from "./editor/preferences.js";
import { sanitizeHexColor, contrastRatio, categoryColorFromHue } from "./editor/text_utils.js";
import { dialogPrompt, dialogConfirm } from "./editor/dialogs.js";
import { onPromptPaletteAppearanceChanged } from "./prompt_palette_shared.js";

const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!=null)node.textContent=text;return node;};
const button=(text,fn,cls="wg-button")=>{const node=el("button",cls,text);node.type="button";node.addEventListener("pointerdown",e=>e.stopPropagation());node.addEventListener("click",async e=>{e.preventDefault();e.stopPropagation();try{await fn?.(e);}catch(error){console.error("MiniMax Creator theme action failed",error);}});return node;};
const escapeHtml=(value)=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));

function themeTone(colors){
  const raw=sanitizeHexColor(colors?.bg,BUILTIN_UI_THEMES.Cinder.bg).slice(1),rgb=[0,2,4].map(o=>parseInt(raw.slice(o,o+2),16)/255),linear=rgb.map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4),lum=.2126*linear[0]+.7152*linear[1]+.0722*linear[2];
  return lum>.42?"Light":"Dark";
}
function primaryPackForTheme(name){return THEME_PACKS.find(pack=>pack.themes.includes(name))||null;}
function packAccent(pack,themes){const first=(pack?.themes||[]).map(name=>themes[name]).find(Boolean);return sanitizeHexColor(first?.accent,BUILTIN_UI_THEMES.Cinder.accent);}

function buildThemePack(theme,activeUiThemeName,allUiThemes){
  const colors=allUiThemes()[activeUiThemeName]||BUILTIN_UI_THEMES.Cinder;
  return {
    schema:"comfyui.prompt-palette.theme",version:4,name:activeUiThemeName||"Prompt Palette Theme",exportedAt:new Date().toISOString(),
    interface:{name:activeUiThemeName,colors:{...colors}},
    tokens:{hueRotate:Number(theme.hueRotate)||0,saturation:Number(theme.saturation)||58,categoryPins:{...(theme.categoryPins||{})},promptTextColor:sanitizeHexColor(theme.promptTextColor,"#f1eee8"),promptTextColorMode:theme.promptTextColorMode==="custom"?"custom":"theme"},
    typography:{fontFamily:theme.fontFamily||"",editorFontSize:Number(theme.editorFontSize)||12.5,uiFontScale:Number(theme.uiFontScale)||1},
    effects:{cornerRadius:Math.max(4,Math.min(18,Number(theme.cornerRadius)||10)),nodeAccentBorder:theme.nodeAccentBorder===true},
    layout:Object.fromEntries(Object.entries(theme).filter(([key])=>key.startsWith("show")||["syntaxInjectorEnabled","promptHistoryEnabled","starterPacksEnabled","zenMode","layoutPreset","dayTheme","nightTheme"].includes(key))),
  };
}
function parseThemePack(parsed){
  if(!parsed||typeof parsed!=="object")throw new Error("Theme file is empty or invalid.");
  if(parsed.schema==="comfyui.prompt-palette.theme"){
    if(Number(parsed.version)>4)throw new Error(`Theme schema v${parsed.version} is newer than this build supports.`);
    return parsed;
  }
  if(parsed.colors||UI_THEME_KEYS.some(([key])=>parsed[key]))return {schema:"comfyui.prompt-palette.theme",version:4,name:parsed.name||"Imported theme",interface:{name:parsed.name||"Imported theme",colors:parsed.colors||parsed}};
  return {schema:"comfyui.prompt-palette.theme",version:4,name:parsed.name||"Imported Prompt Palette preferences",tokens:parsed,typography:parsed,effects:parsed,layout:parsed};
}

export function createH3ThemeStudio(body=null){
  let theme=loadTheme(),customUiThemes=loadUiThemes(),activeUiThemeName=loadActiveUiThemeName();
  const root=el("section","z3h3-setting-section z3h3-theme-studio-section");
  const title=el("div","z3h3-theme-heading"),titleCopy=el("div");titleCopy.append(el("h3",null,"Prompt Palette Theme Studio"),el("small",null,"The same z3rofeels palette now drives Creator, Sidebar, Storyboard, Preview and the embedded Prompt Palette editor."));
  const countBadge=el("span","wg-badge",`${Object.keys(BUILTIN_UI_THEMES).length} palettes`);title.append(titleCopy,countBadge);root.append(title);

  const studio=el("div","wg-theme-studio z3h3-theme-studio"),packStrip=el("div","wg-theme-pack-strip"),gallery=el("div","wg-theme-gallery");studio.append(packStrip,gallery);root.append(studio);
  const selection=el("div","wg-theme-selection-bar"),selectionCopy=el("div","wg-theme-selection-copy");selectionCopy.append(el("small",null,"Selected palette"),el("strong","z3h3-theme-active-name",""),el("span","z3h3-theme-active-pack",""));
  const customize=button("Customize theme",()=>newCustomTheme(),"wg-button primary");selection.append(selectionCopy,customize);root.append(selection);
  const status=el("div","wg-status");root.append(status);

  const dayNight=document.createElement("details");dayNight.className="z3h3-setting-details z3h3-theme-details";dayNight.open=false;const daySummary=el("summary",null,"Day / night pairing, typography & shape");dayNight.append(daySummary);
  const dayNightGrid=el("div","z3h3-theme-control-grid"),daySelect=document.createElement("select"),nightSelect=document.createElement("select");daySelect.className=nightSelect.className="wg-theme-select";
  dayNightGrid.append(labelField("Day palette",daySelect,"Used by the day/night shortcut."),labelField("Night palette",nightSelect,"Used by the day/night shortcut."));
  const swapButton=button("Switch day / night now",()=>{const target=activeUiThemeName===theme.nightTheme?theme.dayTheme:theme.nightTheme;selectTheme(target);});dayNightGrid.append(swapButton);
  const fontInput=document.createElement("input");fontInput.type="text";fontInput.className="wg-theme-select";fontInput.placeholder="Default system / monospace stack";
  const editorSize=rangeControl(10,24,.5,theme.editorFontSize||12.5,"px"),uiScale=rangeControl(80,140,1,Math.round((theme.uiFontScale||1)*100),"%"),radius=rangeControl(4,18,1,theme.cornerRadius||10,"px"),nodeAccentBorder=document.createElement("input");nodeAccentBorder.type="checkbox";nodeAccentBorder.checked=theme.nodeAccentBorder===true;
  dayNightGrid.append(labelField("Font family",fontInput,"Same typography across Creator-owned surfaces."),editorSize.wrap,uiScale.wrap,radius.wrap,labelField("Accent node border",nodeAccentBorder,"Optional. Off keeps the main ComfyUI node border quiet; on uses the theme accent."));
  fontInput.addEventListener("change",()=>{theme.fontFamily=fontInput.value.replace(/[\u0000-\u001f\u007f]/g,"").slice(0,120);saveTheme(theme);});
  editorSize.input.addEventListener("input",()=>{theme.editorFontSize=Number(editorSize.input.value);editorSize.out.textContent=`${editorSize.input.value}px`;saveTheme(theme);});
  uiScale.input.addEventListener("input",()=>{theme.uiFontScale=Number(uiScale.input.value)/100;uiScale.out.textContent=`${uiScale.input.value}%`;saveTheme(theme);});
  radius.input.addEventListener("input",()=>{theme.cornerRadius=Number(radius.input.value);radius.out.textContent=`${radius.input.value}px`;saveTheme(theme);});
  nodeAccentBorder.addEventListener("change",()=>{theme.nodeAccentBorder=nodeAccentBorder.checked;saveTheme(theme);});
  dayNight.append(dayNightGrid);root.append(dayNight);

  const tokenDetails=document.createElement("details");tokenDetails.className="z3h3-setting-details z3h3-theme-details";tokenDetails.append(el("summary",null,"Prompt / token color behavior"));
  const tokenGrid=el("div","z3h3-theme-control-grid"),hue=rangeControl(0,359,1,theme.hueRotate||0,"°"),sat=rangeControl(30,90,1,theme.saturation||58,"%"),promptAuto=document.createElement("input"),promptColor=document.createElement("input");promptAuto.type="checkbox";promptAuto.checked=theme.promptTextColorMode!=="custom";promptColor.type="color";promptColor.value=sanitizeHexColor(theme.promptTextColor,"#f1eee8");
  hue.label.textContent="Wildcard / folder hue rotation";sat.label.textContent="Wildcard / folder saturation";
  tokenGrid.append(hue.wrap,sat.wrap,labelField("Match prompt text to theme",promptAuto,"When enabled, prompt text follows the selected palette."),labelField("Custom prompt text",promptColor,"Used only when theme matching is disabled."));
  hue.input.addEventListener("input",()=>{theme.hueRotate=Number(hue.input.value);hue.out.textContent=`${hue.input.value}°`;saveTheme(theme);});sat.input.addEventListener("input",()=>{theme.saturation=Number(sat.input.value);sat.out.textContent=`${sat.input.value}%`;saveTheme(theme);});promptAuto.addEventListener("change",()=>{theme.promptTextColorMode=promptAuto.checked?"theme":"custom";saveTheme(theme);render();});promptColor.addEventListener("input",()=>{theme.promptTextColor=promptColor.value;theme.promptTextColorMode="custom";promptAuto.checked=false;saveTheme(theme);});
  tokenDetails.append(tokenGrid);root.append(tokenDetails);

  const advanced=document.createElement("details");advanced.className="z3h3-setting-details z3h3-theme-details";advanced.append(el("summary",null,"Advanced palette editor · 12 colors"));
  const advancedActions=el("div","z3h3-theme-actions"),renameBtn=button("Rename custom",()=>renameCustomTheme()),deleteBtn=button("Delete custom",()=>deleteCustomTheme(),"wg-button danger-quiet"),swatches=el("div","wg-swatch-grid");advancedActions.append(renameBtn,deleteBtn);advanced.append(advancedActions,swatches);root.append(advanced);

  const portable=document.createElement("details");portable.className="z3h3-setting-details z3h3-theme-details";portable.append(el("summary",null,"Theme packs · Prompt Palette v4 import / export"));
  const drop=el("div","wg-import-drop");drop.tabIndex=0;drop.innerHTML="<strong>Drop a Prompt Palette theme here</strong><small>Same v4 theme pack format as Prompt Palette v2. Older theme JSON is migrated automatically.</small>";
  const portableActions=el("div","z3h3-theme-actions"),importBtn=button("Import file",()=>importFile(),"wg-button primary"),exportBtn=button("Export file",()=>exportFile()),copyBtn=button("Copy pack",()=>copyPack()),pasteBtn=button("Paste pack",()=>pastePack()),resetBtn=button("Reset appearance",()=>resetAppearance(),"wg-button danger-quiet");portableActions.append(importBtn,exportBtn,copyBtn,pasteBtn,resetBtn);const themeJson=document.createElement("textarea");themeJson.className="z3h3-theme-json";themeJson.readOnly=true;themeJson.setAttribute("aria-label","Prompt Palette theme pack JSON preview");const portableStatus=el("div","wg-status");portable.append(drop,portableActions,themeJson,portableStatus);root.append(portable);
  for(const type of ["dragenter","dragover"])drop.addEventListener(type,e=>{e.preventDefault();drop.classList.add("dragging");});for(const type of ["dragleave","drop"])drop.addEventListener(type,e=>{e.preventDefault();drop.classList.remove("dragging");});drop.addEventListener("drop",async e=>{const file=[...(e.dataTransfer?.files||[])].find(f=>f.type==="application/json"||f.name.toLowerCase().endsWith(".json"));if(!file)return setPortableStatus("Drop a JSON theme file here.",true);try{applyThemePack(JSON.parse(await file.text()));setPortableStatus(`Imported ${file.name}.`);}catch(error){setPortableStatus(error.message||String(error),true);}});drop.addEventListener("click",()=>importFile());drop.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();importFile();}});

  let activeThemePackId=primaryPackForTheme(activeUiThemeName)?.id||(customUiThemes[activeUiThemeName]?"custom":"all");
  const allUiThemes=()=>({...BUILTIN_UI_THEMES,...customUiThemes});
  const isBuiltin=name=>!!BUILTIN_UI_THEMES[name]&&!customUiThemes[name];
  if(!allUiThemes()[activeUiThemeName])activeUiThemeName="Cinder";

  function labelField(label,control,hint=""){const wrap=el("label","z3h3-setting-field z3h3-theme-field"),copy=el("div");copy.append(el("b",null,label));if(hint)copy.append(el("small",null,hint));wrap.append(copy,control);return wrap;}
  function rangeControl(min,max,step,value,suffix){const wrap=el("label","z3h3-theme-range"),head=el("div"),label=el("b",null,"Control"),out=el("output",null,`${value}${suffix}`),input=document.createElement("input");input.type="range";input.min=min;input.max=max;input.step=step;input.value=value;head.append(label,out);wrap.append(head,input);return {wrap,label,out,input};}
  function setStatus(message,isError=false){status.textContent=message||"";status.className=`wg-status${isError?" err":""}`;}
  function setPortableStatus(message,isError=false){portableStatus.textContent=message||"";portableStatus.className=`wg-status${isError?" err":""}`;}

  function renderPackStrip(){
    const themes=allUiThemes(),packs=[{id:"all",name:"All themes",tone:"Browse",description:"Every built-in palette.",themes:Object.keys(BUILTIN_UI_THEMES)},...THEME_PACKS];if(Object.keys(customUiThemes).length)packs.push({id:"custom",name:"My Themes",tone:"Custom",description:"Your editable palette copies.",themes:Object.keys(customUiThemes)});packStrip.replaceChildren();
    for(const pack of packs){const b=document.createElement("button");b.type="button";b.className=`wg-theme-pack-card${pack.id===activeThemePackId?" active":""}`;b.dataset.themePack=pack.id;b.title=pack.description;b.style.setProperty("--pack-accent",pack.id==="all"?(themes[activeUiThemeName]?.accent||BUILTIN_UI_THEMES.Cinder.accent):packAccent(pack,themes));const count=(pack.themes||[]).filter(name=>themes[name]).length;b.innerHTML=`<span class="wg-theme-pack-dot"></span><span class="wg-theme-pack-copy"><strong>${escapeHtml(pack.name)}</strong><small>${escapeHtml(pack.tone)} · ${count}</small></span>`;b.addEventListener("pointerdown",e=>e.stopPropagation());b.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();activeThemePackId=pack.id;renderPackStrip();renderGallery();});packStrip.append(b);}
  }
  function galleryNames(){if(activeThemePackId==="custom")return Object.keys(customUiThemes).sort((a,b)=>a.localeCompare(b));if(activeThemePackId==="all")return THEME_PACKS.flatMap(pack=>pack.themes).filter((name,index,list)=>list.indexOf(name)===index&&allUiThemes()[name]);const pack=THEME_PACKS.find(entry=>entry.id===activeThemePackId);return (pack?.themes||[]).filter(name=>allUiThemes()[name]);}
  function renderGallery(){gallery.replaceChildren();const themes=allUiThemes();for(const name of galleryNames()){const colors=themes[name],pack=primaryPackForTheme(name),b=document.createElement("button");b.type="button";b.className=`wg-theme-gallery-card${name===activeUiThemeName?" active":""}`;b.style.setProperty("--theme-bg",sanitizeHexColor(colors.bg,BUILTIN_UI_THEMES.Cinder.bg));b.style.setProperty("--theme-panel",sanitizeHexColor(colors["panel-bg"],BUILTIN_UI_THEMES.Cinder["panel-bg"]));b.style.setProperty("--theme-surface",sanitizeHexColor(colors.surface,BUILTIN_UI_THEMES.Cinder.surface));b.style.setProperty("--theme-border",sanitizeHexColor(colors.border,BUILTIN_UI_THEMES.Cinder.border));b.style.setProperty("--theme-accent",sanitizeHexColor(colors.accent,BUILTIN_UI_THEMES.Cinder.accent));b.style.setProperty("--theme-text",sanitizeHexColor(colors.text,BUILTIN_UI_THEMES.Cinder.text));b.innerHTML=`<span class="wg-theme-card-preview"><span class="wg-theme-card-top"><i></i><i></i><i></i></span><span class="wg-theme-card-body"><i class="wg-theme-card-side"></i><span><i></i><i></i></span></span></span><span class="wg-theme-gallery-copy"><strong>${escapeHtml(name)}</strong><small>${escapeHtml(pack?.name||(customUiThemes[name]?"My Themes":"Theme"))} · ${themeTone(colors)}</small></span>`;b.addEventListener("pointerdown",e=>e.stopPropagation());b.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();selectTheme(name,true);});gallery.append(b);}if(!gallery.children.length)gallery.append(el("div","wg-empty-state","No palettes in this collection yet."));}
  function renderSwatches(){swatches.replaceChildren();const colors=allUiThemes()[activeUiThemeName]||BUILTIN_UI_THEMES.Cinder,locked=isBuiltin(activeUiThemeName);for(const [key,label] of UI_THEME_KEYS){const item=el("label","wg-swatch-item"),title=el("span","wg-swatch-label",label),controls=el("span","wg-swatch-controls"),hex=document.createElement("input"),picker=document.createElement("input");hex.type="text";hex.className="wg-swatch-hex";hex.maxLength=7;hex.value=sanitizeHexColor(colors[key],BUILTIN_UI_THEMES.Cinder[key]);picker.type="color";picker.value=hex.value;hex.disabled=picker.disabled=locked;const commit=value=>{if(locked)return;const safe=sanitizeHexColor(value,customUiThemes[activeUiThemeName][key]);customUiThemes[activeUiThemeName][key]=safe;hex.value=picker.value=safe;saveUiThemes(customUiThemes);render();};picker.addEventListener("input",e=>commit(e.target.value));hex.addEventListener("change",e=>commit(e.target.value));controls.append(hex,picker);item.append(title,controls);swatches.append(item);}const ratio=contrastRatio(sanitizeHexColor(colors.text,BUILTIN_UI_THEMES.Cinder.text),sanitizeHexColor(colors.surface,BUILTIN_UI_THEMES.Cinder.surface));setStatus(`${locked?"Built-in palette — Customize theme makes an editable copy.":"Custom palette — changes save live."} Text contrast ${ratio.toFixed(1)}:1${ratio>=4.5?" · AA+":" · low contrast"}.`,ratio<4.5);renameBtn.disabled=deleteBtn.disabled=locked;}
  function refreshSelects(){const names=Object.keys(allUiThemes()).sort((a,b)=>a.localeCompare(b));for(const [selectNode,value] of [[daySelect,theme.dayTheme],[nightSelect,theme.nightTheme]]){selectNode.replaceChildren(...names.map(name=>{const o=document.createElement("option");o.value=name;o.textContent=name;if(name===value)o.selected=true;return o;}));}daySelect.onchange=()=>{theme.dayTheme=daySelect.value;saveTheme(theme);};nightSelect.onchange=()=>{theme.nightTheme=nightSelect.value;saveTheme(theme);};fontInput.value=theme.fontFamily||"";promptAuto.checked=theme.promptTextColorMode!=="custom";promptColor.disabled=promptAuto.checked;promptColor.value=theme.promptTextColorMode==="custom"?sanitizeHexColor(theme.promptTextColor,"#f1eee8"):sanitizeHexColor(allUiThemes()[activeUiThemeName]?.text,"#f1eee8");}
  function renderSelection(){const colors=allUiThemes()[activeUiThemeName]||BUILTIN_UI_THEMES.Cinder,pack=primaryPackForTheme(activeUiThemeName);selectionCopy.querySelector("strong").textContent=activeUiThemeName;selectionCopy.querySelector("span").textContent=pack?`${pack.name} · ${themeTone(colors)}`:`My Themes · ${themeTone(colors)}`;}
  function render(){theme=loadTheme();customUiThemes=loadUiThemes();const stored=loadActiveUiThemeName();if(allUiThemes()[stored])activeUiThemeName=stored;renderPackStrip();renderGallery();renderSelection();renderSwatches();refreshSelects();editorSize.input.value=theme.editorFontSize||12.5;editorSize.out.textContent=`${editorSize.input.value}px`;uiScale.input.value=Math.round((theme.uiFontScale||1)*100);uiScale.out.textContent=`${uiScale.input.value}%`;radius.input.value=theme.cornerRadius||10;radius.out.textContent=`${radius.input.value}px`;nodeAccentBorder.checked=theme.nodeAccentBorder===true;hue.input.value=theme.hueRotate||0;hue.out.textContent=`${hue.input.value}°`;sat.input.value=theme.saturation||58;sat.out.textContent=`${sat.input.value}%`;themeJson.value=JSON.stringify(buildThemePack(theme,activeUiThemeName,allUiThemes),null,2);}
  function selectTheme(name,preservePack=false){const normalized=normalizeUiThemeName(String(name||""));if(!allUiThemes()[normalized])return false;if(!preservePack)activeThemePackId=primaryPackForTheme(normalized)?.id||(customUiThemes[normalized]?"custom":activeThemePackId);activeUiThemeName=normalized;saveActiveUiThemeName(normalized);render();return true;}
  async function newCustomTheme(){const base=allUiThemes()[activeUiThemeName]||BUILTIN_UI_THEMES.Cinder;let name=await dialogPrompt({title:"New Theme",message:"Name for the new theme:",defaultValue:`${activeUiThemeName} copy`});if(!name)return;name=name.trim();if(!name)return;if(allUiThemes()[name])return setStatus("A theme with that name already exists.",true);customUiThemes[name]={...base};saveUiThemes(customUiThemes);activeUiThemeName=name;activeThemePackId="custom";saveActiveUiThemeName(name);render();}
  async function renameCustomTheme(){if(isBuiltin(activeUiThemeName))return setStatus("Built-in themes can't be renamed.",true);let name=await dialogPrompt({title:"Rename Theme",message:"Rename theme:",defaultValue:activeUiThemeName});if(!name)return;name=name.trim();if(!name||name===activeUiThemeName)return;if(allUiThemes()[name])return setStatus("A theme with that name already exists.",true);customUiThemes[name]=customUiThemes[activeUiThemeName];delete customUiThemes[activeUiThemeName];saveUiThemes(customUiThemes);activeUiThemeName=name;activeThemePackId="custom";saveActiveUiThemeName(name);render();}
  async function deleteCustomTheme(){if(isBuiltin(activeUiThemeName))return;const doomed=activeUiThemeName;if(!await dialogConfirm({title:"Delete theme",message:`Delete “${doomed}”? This cannot be undone.`}))return;delete customUiThemes[doomed];saveUiThemes(customUiThemes);activeUiThemeName="Cinder";activeThemePackId=primaryPackForTheme(activeUiThemeName)?.id||"all";saveActiveUiThemeName(activeUiThemeName);render();}
  function applyThemePack(raw){const pack=parseThemePack(raw);if(pack.interface?.colors){const base=String(pack.interface.name||pack.name||"Imported theme").trim()||"Imported theme";let name=base,suffix=2;while(allUiThemes()[name])name=`${base} ${suffix++}`;const colors={};for(const [key] of UI_THEME_KEYS)colors[key]=sanitizeHexColor(pack.interface.colors[key],BUILTIN_UI_THEMES.Cinder[key]);customUiThemes[name]=colors;saveUiThemes(customUiThemes);activeUiThemeName=name;activeThemePackId="custom";saveActiveUiThemeName(name);}if(pack.tokens){if(Number.isFinite(Number(pack.tokens.hueRotate)))theme.hueRotate=Math.max(0,Math.min(359,Number(pack.tokens.hueRotate)));if(Number.isFinite(Number(pack.tokens.saturation)))theme.saturation=Math.max(30,Math.min(90,Number(pack.tokens.saturation)));if(pack.tokens.categoryPins&&typeof pack.tokens.categoryPins==="object")theme.categoryPins=Object.fromEntries(Object.entries(pack.tokens.categoryPins).map(([key,value])=>[key,sanitizeHexColor(value,categoryColorFromHue(0,theme.saturation))]));if(pack.tokens.promptTextColor)theme.promptTextColor=sanitizeHexColor(pack.tokens.promptTextColor,theme.promptTextColor);if(["theme","custom"].includes(pack.tokens.promptTextColorMode))theme.promptTextColorMode=pack.tokens.promptTextColorMode;}if(pack.typography){if(typeof pack.typography.fontFamily==="string")theme.fontFamily=pack.typography.fontFamily.replace(/[\u0000-\u001f\u007f]/g,"").slice(0,120);if(Number.isFinite(Number(pack.typography.editorFontSize)))theme.editorFontSize=Math.max(10,Math.min(64,Number(pack.typography.editorFontSize)));if(Number.isFinite(Number(pack.typography.uiFontScale)))theme.uiFontScale=Math.max(.8,Math.min(2,Number(pack.typography.uiFontScale)));}if(pack.effects&&Number.isFinite(Number(pack.effects.cornerRadius)))theme.cornerRadius=Math.max(4,Math.min(18,Number(pack.effects.cornerRadius)));if(pack.effects&&typeof pack.effects.nodeAccentBorder==="boolean")theme.nodeAccentBorder=pack.effects.nodeAccentBorder;if(pack.layout&&typeof pack.layout==="object"){const defaults=defaultTheme();for(const [key,value] of Object.entries(pack.layout)){if(!(key in defaults)||!["boolean","string"].includes(typeof value))continue;theme[key]=value;}}saveTheme(theme);render();return pack;}
  async function importFile(){try{const files=await pickJsonFile();if(!files.length)return;const pack=applyThemePack(JSON.parse(files[0].text));setPortableStatus(`Imported “${pack.name||"theme"}” from ${files[0].file.name}.`);}catch(error){setPortableStatus(error.message||"That file is not a valid Prompt Palette theme.",true);}}
  function exportFile(){const pack=buildThemePack(theme,activeUiThemeName,allUiThemes);downloadJsonFile(normalizeThemeFilename(pack.name),pack);setPortableStatus(`Exported “${pack.name}”.`);}
  async function copyPack(){try{await navigator.clipboard.writeText(JSON.stringify(buildThemePack(theme,activeUiThemeName,allUiThemes),null,2));setPortableStatus("Theme pack copied to clipboard.");}catch{setPortableStatus("Clipboard permission was denied.",true);}}
  async function pastePack(){try{const pack=applyThemePack(JSON.parse(await navigator.clipboard.readText()));setPortableStatus(`Imported “${pack.name||"theme"}” from the clipboard.`);}catch(error){setPortableStatus(error?.message||"Clipboard does not contain a valid Prompt Palette theme.",true);}}
  async function resetAppearance(){if(!await dialogConfirm({title:"Reset Creator appearance",message:"Reset Prompt Palette appearance, token colors, typography and day/night pairing to defaults? Creator/H3 settings are not affected."}))return;theme=defaultTheme();saveTheme(theme);activeUiThemeName="Cinder";activeThemePackId=primaryPackForTheme(activeUiThemeName)?.id||"all";saveActiveUiThemeName(activeUiThemeName);render();setPortableStatus("Appearance reset to Cinder.");}

  const cleanup=onPromptPaletteAppearanceChanged(()=>{theme=loadTheme();customUiThemes=loadUiThemes();const next=loadActiveUiThemeName();if(allUiThemes()[next]){if(next!==activeUiThemeName)activeThemePackId=primaryPackForTheme(next)?.id||(customUiThemes[next]?"custom":"all");activeUiThemeName=next;}render();});
  render();
  return {root,cleanup};
}
