import { app } from "../../scripts/app.js";
import * as H from "./z3_h3_api.js";
import * as S from "./z3_h3_state.js";
import { findCreatorForPreStage, pullCreatorIntoPreStage, setCreatorPreStageGate, applyPreStageImageToCreator, applyPreStageImagesToCreator, bindPreStageToActiveCreator } from "./h3_prestage_bridge.js";
import { normalizePreStageHandoff, preStageNeedsCreatorGate, pickPreStageCandidate } from "./h3_prestage_handoff.js";
import { resolveH3Canvas } from "./h3_canvas.js";
import { saveMachineSettings } from "./h3_settings_store.js";
import { normalizeLoraLibraryRows, loraLibraryIdentity, loraLibrarySelection } from "./h3_lora_library.js";
import { installPreStageImageSidecar } from "./h3_prestage_sidecar.js";

const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n};
const btn=(text,fn,cls="z3h3-btn")=>{const b=el("button",cls,text);b.type="button";b.addEventListener("pointerdown",e=>e.stopPropagation());b.addEventListener("click",async e=>{e.stopPropagation();try{await fn?.(e)}catch(error){console.error("MiniMax PreStage action failed",error);b.title=error?.message||String(error);b.dataset.error="1";b.dispatchEvent(new CustomEvent("z3pre-action-error",{bubbles:true,detail:error}));setTimeout(()=>delete b.dataset.error,1400)}});return b};
const input=(type,value)=>{const n=document.createElement("input");n.type=type;if(type!=="checkbox")n.value=value??"";return n};
const checkbox=(v)=>{const n=input("checkbox","");n.checked=!!v;return n};
const select=(options,value)=>{const n=document.createElement("select");for(const o of options){const [v,l]=Array.isArray(o)?o:[o,o],x=document.createElement("option");x.value=v;x.textContent=l;if(String(v)===String(value))x.selected=true;n.append(x)}return n};
const field=(label,control,hint="")=>{const w=el("label","z3h3-field");w.append(el("span",null,label),control);if(hint)w.append(el("small","z3h3-note",hint));return w};
const section=(title,...children)=>{const s=el("section","z3h3-section");if(title)s.append(el("h3",null,title));s.append(...children.filter(Boolean));return s};
const row=(...children)=>{const r=el("div","z3h3-tabs");r.append(...children.filter(Boolean));return r};
const setWidget=(widget,value,node)=>{if(!widget)return;widget.value=value;widget.callback?.(value,node.graph?.canvas,node);node.graph?.setDirtyCanvas?.(true,true)};
const fileLabel=(p)=>String(p||"").replace(/ \[output\]$/,'').split(/[\\/]/).pop()||String(p||"");
const imageUrl=(p)=>H.inputViewUrl(p);
const historyKey=(image)=>[image?.type,image?.subfolder,image?.filename].join("|");
const PRESTAGE_FRAME_SLOTS=["first_frame","last_frame","reference"];
function slotsForHistoryKey(handoff,key){const slots=handoff?.slots||{};return key?PRESTAGE_FRAME_SLOTS.filter(slot=>slots[slot]===key):[]}
function toggleHistorySlot(handoff,slot,key){if(!PRESTAGE_FRAME_SLOTS.includes(slot))return false;handoff.slots ||= {first_frame:"",last_frame:"",reference:""};handoff.slots[slot]=handoff.slots[slot]===key?"":key;return true}
const json=(value,fallback)=>{try{return JSON.parse(String(value||""))}catch{return structuredClone(fallback)}};
const H3_RES=[384,512,640,704,768,832,896];
const IMAGE_RES=[512,768,1024,1280,1536,2048];
function resolutionOptions(aspect,isH3,current){const values=[...(isH3?H3_RES:IMAGE_RES)],n=Number(current);if(Number.isFinite(n)&&!values.includes(n))values.push(n);values.sort((a,b)=>a-b);const labels=isH3?{384:"draft",512:"fast",640:"balanced",704:"high",768:"native · recommended",832:"large",896:"maximum"}:{512:"draft",768:"fast",1024:"standard",1280:"high",1536:"large",2048:"maximum"};return values.map((edge)=>{const d=isH3?resolveH3Canvas(aspect,edge):S.aspectDimensions(aspect,edge);return [edge,`${d.width}×${d.height} · ${labels[edge]||`custom ${edge}px`}`];});}
const DEFAULT={version:1,arch:"krea2",prompt:"",aspect:"16:9",short_edge:1024,init:null,refs:[],loras:[],turbo:{on:false,quality:"good",saved:null},quality:"default",output_prefix:"minimax/stills/prestage",minimax:{frames:124,latent_index:0,request:{prompt:"",assets:[],loras:[],aspect:"16:9",short_edge:768,output_prefix:"minimax/stills/prestage",models:{}}},models:{krea2:{},ideogram4:{},minimax:{}},peer:null,handoff:normalizePreStageHandoff(null)};

function normalize(raw){
  const d={...structuredClone(DEFAULT),...(raw&&typeof raw==="object"?raw:{})};
  d.models={...structuredClone(DEFAULT.models),...(d.models||{})};
  d.refs=Array.isArray(d.refs)?d.refs:[];d.loras=Array.isArray(d.loras)?d.loras:[];
  d.turbo={...DEFAULT.turbo,...(d.turbo||{})};d.minimax={...structuredClone(DEFAULT.minimax),...(d.minimax||{})};
  d.minimax.request={...structuredClone(DEFAULT.minimax.request),...(d.minimax.request||{})};
  d.minimax.request.assets=Array.isArray(d.minimax.request.assets)?d.minimax.request.assets:[];
  d.minimax.request.loras=Array.isArray(d.minimax.request.loras)?d.minimax.request.loras:[];
  d.minimax.request.models={...(d.minimax.request.models||{})};
  d.handoff=normalizePreStageHandoff(d.handoff);
  return d;
}
function modePrompt(d){return d.arch==="minimax"?String(d.minimax.request.prompt||""):String(d.prompt||"")}
function setModePrompt(d,v){if(d.arch==="minimax")d.minimax.request.prompt=String(v??"");else d.prompt=String(v??"")}
function promptRefs(d){return d.arch==="minimax"?d.minimax.request.assets:d.refs}
function promptLoras(d){return d.arch==="minimax"?d.minimax.request.loras:d.loras}
function nextHandle(d,prefix="ref"){const used=new Set(promptRefs(d).map(x=>x.handle).filter(Boolean));let i=1;while(used.has(`${prefix}-${i}`))i++;return `${prefix}-${i}`}

function modal(title,build,{small=false}={}){const back=el("div","z3h3-backdrop"),box=el("div",`z3h3-modal${small?" small":""}`),head=el("div","z3h3-modal-head"),body=el("div","z3h3-modal-body"),close=btn("Close",()=>back.remove());head.append(el("b",null,title),el("div","z3h3-spacer"),close);box.append(head,body);back.append(box);document.body.append(back);back.onmousedown=e=>{if(e.target===back)back.remove()};build(body,()=>back.remove());return back}

export class PreStagePaletteBody{
  constructor(node,ppRoot,textWidget){
    this.node=node;this.ppRoot=ppRoot;this.textWidget=textWidget;this.widgets=Object.fromEntries((node.widgets||[]).map(w=>[w.name,w]));this.dataWidget=this.widgets.prestage_data;const widgetRaw=String(this.dataWidget?.value||""),backupRaw=String(node.properties?.z3_prestage_data_backup||"");this.data=normalize(json(backupRaw.length>widgetRaw.length?backupRaw:widgetRaw,DEFAULT));this.node.properties ||= {};this.history=Array.isArray(this.node.properties.z3_prestage_history)?this.node.properties.z3_prestage_history.filter(x=>x?.filename).slice(-64):[];this.node.properties.z3_prestage_data_backup=JSON.stringify(this.data);if(this.dataWidget){this.dataWidget.options ||= {};this.dataWidget.options.serialize=true;this.dataWidget.value=JSON.stringify(this.data);this.dataWidget.serializeValue=()=>JSON.stringify(this.data);}this.root=el("div","z3h3 z3pre");this._wrapText();this._installInteractionBoundary();this.imageSidecar=installPreStageImageSidecar(this);this.renderShell();this.syncPrompt(false);this.refresh();this.hydrateMachineDefaults();queueMicrotask(()=>this.syncCreatorGate());
  }
  async hydrateMachineDefaults(){
    try{
      const response=await H.readSettings(),saved=response.settings?.prestage_model_defaults;if(!saved||typeof saved!=="object")return;
      let changed=false;
      for(const arch of ["krea2","ideogram4"]){const live=this.data.models[arch]||=( {}),defaults=saved[arch]||{};for(const [key,value] of Object.entries(defaults)){if(!live[key]&&value){live[key]=value;changed=true;}}}
      const h3=this.data.minimax.request.models||=( {}),h3Defaults=saved.minimax||{};for(const [key,value] of Object.entries(h3Defaults)){if(!h3[key]&&value){h3[key]=value;changed=true;}}
      if(!this.data.models.dtype&&saved.dtype){this.data.models.dtype=saved.dtype;changed=true;}
      if(changed)this.commit(false);
    }catch(error){console.debug("MiniMax PreStage: model defaults unavailable",error);}
  }
  async persistModelDefaults(status=null){
    const snapshot={krea2:structuredClone(this.data.models.krea2||{}),ideogram4:structuredClone(this.data.models.ideogram4||{}),minimax:structuredClone(this.data.minimax.request.models||{}),dtype:String(this.data.models.dtype||"default")};
    const serial=(this._modelSaveSerial||0)+1;this._modelSaveSerial=serial;
    if(status){status.textContent="Saving automatically…";status.className="z3h3-note";}
    try{await saveMachineSettings({prestage_model_defaults:snapshot});if(serial===this._modelSaveSerial&&status){status.textContent="Saved automatically. New PreStage nodes reuse these local model choices.";status.className="z3h3-note good";}return true;}catch(error){if(serial===this._modelSaveSerial&&status){status.textContent=`Could not save defaults: ${error.message||error}`;status.className="z3h3-error";}return false;}
  }
  destroy(){clearTimeout(this._autoTimer);clearTimeout(this._actionMessageTimer);this.imageSidecar?.destroy?.();this._restoreText?.();this._interactionCleanup?.();this.root.remove()}
  _installInteractionBoundary(){const selector="button,input,select,textarea,[contenteditable=true],[role=button],a";const stop=e=>{if(e.target?.closest?.(selector))e.stopPropagation()},actionError=e=>{e.stopPropagation();this.announce(e.detail?.message||String(e.detail||"PreStage action failed."),"error")};const events=["pointerdown","pointerup","mousedown","mouseup","click","dblclick","wheel"];for(const name of events)this.root.addEventListener(name,stop);this.root.addEventListener("z3pre-action-error",actionError);this._interactionCleanup=()=>{for(const name of events)this.root.removeEventListener(name,stop);this.root.removeEventListener("z3pre-action-error",actionError)}}
  _wrapText(){const w=this.textWidget,old=w.callback,self=this;w.callback=function(v){setModePrompt(self.data,v);self.commit(false);return old?.apply(this,arguments)};this._restoreText=()=>{w.callback=old}}
  commit(notify=true){this.data=normalize(this.data);const raw=JSON.stringify(this.data);if(this.dataWidget)this.dataWidget.value=raw;this.node.properties ||= {};this.node.properties.z3_prestage_data_backup=raw;if(notify)this.dataWidget?.callback?.(raw,this.node.graph?.canvas,this.node);this.node.graph?.setDirtyCanvas?.(true,true);this.refresh()}
  syncPrompt(notify=false){const v=modePrompt(this.data),g=this.node._ppPromptStateGuard;if(g)g.commit(v,{notify,dirty:false});else this.textWidget.value=v;this.node._wgRefreshFromHidden?.()}
  renderShell(){
    const top=el("div","z3h3-top"),brand=el("div","z3h3-brand");brand.append(el("b",null,"PreStage"),el("span","z3h3-badge","Krea 2 · Ideogram 4 · H3 still"));top.append(brand,el("div","z3h3-spacer"),this.imageSidecar.toggleButton,btn("Pull Creator",()=>this.pullCreator()),btn("Media",()=>this.openMedia()),btn("LoRAs",()=>this.openLoras()),btn("Models",()=>this.openModels()),btn("Sampling",()=>this.openSampling()));
    this.arch=el("div","z3pre-arch");this.assets=el("div","z3h3-refrail");this.promptHost=el("div","z3h3-prompt-host");this.promptHost.append(this.ppRoot);this.controls=el("div","z3h3-controls");this.handoffPanel=el("div","z3pre-handoff");this.status=el("div","z3h3-status");this.root.append(top,this.arch,this.assets,this.promptHost,this.controls,this.handoffPanel,this.status)
  }
  refresh(){this.renderArch();this.renderAssets();this.renderControls();this.renderHandoff();this.renderGallery();this.renderStatus()}
  refreshAll(){this.refresh()}
  renderArch(){this.arch.replaceChildren();for(const [id,label] of [["krea2","Krea 2"],["ideogram4","Ideogram 4"],["minimax","MiniMax H3 Still"]]){const b=btn(label,()=>this.setArch(id),`z3h3-pill${this.data.arch===id?" active":""}`);this.arch.append(b)}}
  setArch(id){if(this.data.arch===id)return;setModePrompt(this.data,modePrompt(this.data));this.data.arch=id;if(id==="krea2"){setWidget(this.widgets.steps,52,this.node);setWidget(this.widgets.cfg,3.5,this.node);setWidget(this.widgets.sampler_name,"euler",this.node);setWidget(this.widgets.scheduler,"simple",this.node)}else if(id==="ideogram4"){setWidget(this.widgets.steps,20,this.node);setWidget(this.widgets.cfg,7,this.node)}else{setWidget(this.widgets.steps,20,this.node);setWidget(this.widgets.cfg,1,this.node);setWidget(this.widgets.sampler_name,"res_multistep",this.node);setWidget(this.widgets.scheduler,"simple",this.node)}this.commit();this.syncPrompt(false)}
  renderAssets(){
    this.assets.replaceChildren(el("span","z3h3-note",this.data.arch==="minimax"?"H3 references":"Init + style references"));
    if(this.data.arch!=="minimax"&&this.data.init){const c=btn(`▧ init · ${fileLabel(this.data.init.filename)}`,()=>this.editInit(),"z3h3-chip");this.assets.append(c)}
    for(const a of promptRefs(this.data)){const filename=a.filename||a.path,c=btn(`▧ @${a.handle||"ref"} · ${fileLabel(filename)}`,()=>this.editRef(a),"z3h3-chip");this.assets.append(c)}
    this.assets.append(btn("+ attach",()=>this.openMedia(),"z3h3-chip"));
    for(const l of promptLoras(this.data).filter(x=>x.enabled!==false)){this.assets.append(btn(`◇ ${fileLabel(l.name)} ${Number(l.strength??1).toFixed(2)}`,()=>this.openLoras(),"z3h3-chip"))}
  }
  renderControls(){
    this.controls.replaceChildren();const isH3=this.data.arch==="minimax";const aspect=select(["16:9","9:16","1:1","4:3","3:4","3:2","2:3","21:9"],isH3?this.data.minimax.request.aspect:this.data.aspect);
    const currentEdge=isH3?this.data.minimax.request.short_edge:this.data.short_edge,edge=select(resolutionOptions(aspect.value,isH3,currentEdge),Number(currentEdge));
    const rebuildResolution=()=>{const current=Number(isH3?this.data.minimax.request.short_edge:this.data.short_edge),options=resolutionOptions(aspect.value,isH3,current);edge.replaceChildren(...options.map(([v,label])=>{const option=document.createElement("option");option.value=v;option.textContent=label;if(Number(v)===current)option.selected=true;return option;}));};
    aspect.onchange=()=>{if(isH3)this.data.minimax.request.aspect=aspect.value;else this.data.aspect=aspect.value;rebuildResolution();this.commit()};edge.onchange=()=>{const n=Number(edge.value);if(isH3)this.data.minimax.request.short_edge=n;else this.data.short_edge=n;this.commit()};
    const steps=input("number",this.widgets.steps?.value??20);steps.min=1;steps.max=100;steps.onchange=()=>setWidget(this.widgets.steps,Number(steps.value),this.node);
    if(isH3){const frames=select([[5,"~0.2s / 5 frames"],[22,"~0.9s / 22 frames"],[39,"~1.6s / 39 frames"],[56,"~2.3s / 56 frames"],[90,"~3.8s / 90 frames"],[124,"~5.2s / 124 frames"]],this.data.minimax.frames);frames.onchange=()=>{this.data.minimax.frames=Number(frames.value);this.commit()};this.controls.append(field("H3 source length",frames),field("Aspect",aspect),field("Resolution preset",edge,"Pick a known H3 canvas size instead of guessing with a slider."),field("Quality (steps)",steps))}
    else{const quality=this.data.arch==="ideogram4"?select([["quality","Quality · 48"],["default","Default · 20"],["turbo","Turbo · 12"]],this.data.quality):select([["raw","RAW · 52"],["turbo","Krea Turbo"]],this.data.turbo.on?"turbo":"raw");quality.onchange=()=>{if(this.data.arch==="ideogram4"){this.data.quality=quality.value;setWidget(this.widgets.steps,{quality:48,default:20,turbo:12}[quality.value],this.node);setWidget(this.widgets.cfg,7,this.node)}else{const on=quality.value==="turbo";this.data.turbo.on=on;setWidget(this.widgets.steps,on?8:52,this.node);setWidget(this.widgets.cfg,on?1:3.5,this.node);setWidget(this.widgets.sampler_name,"euler",this.node);setWidget(this.widgets.scheduler,"simple",this.node)}this.commit()};this.controls.append(field("Mode / quality",quality),field("Aspect",aspect),field("Resolution preset",edge,"Common image sizes, ordered from fast to maximum."),field("Sampling steps",steps))}
  }
  renderHandoff(){
    const h=this.data.handoff,panel=this.handoffPanel;panel.replaceChildren();
    const modeLabel={review:"Review first",auto:"Auto image → video",image_only:"Image only",bypass:"Bypassed"}[h.mode]||"Review first";
    const marked=[h.slots.first_frame&&"Start ✓",h.slots.last_frame&&"End ✓",h.slots.reference&&"Ref ✓"].filter(Boolean).join(" · ")||"no frames selected";
    const summary=el("div","z3pre-handoff-summary");summary.append(el("b",null,this._pendingImageBatch?`Generating · ${this._pendingImageBatch.remaining} remaining`:modeLabel),el("small",null,`${h.batch_count} image${h.batch_count===1?"":"s"} · ${marked}`));
    const runLabel=h.mode==="bypass"?"Enable Review + Generate":h.mode==="auto"?`Generate ${h.batch_count} + Video`:h.batch_count>1?`Generate ${h.batch_count} stills`:"Generate still";
    const run=btn(runLabel,()=>this.runImageBatch(),"z3h3-btn primary");run.disabled=!!this._pendingImageBatch;
    panel.append(el("div","z3pre-handoff-head","PRESTAGE FLOW"),summary,run,btn("Flow…",()=>this.openFlowSettings(),"z3h3-btn"));
    if(preStageNeedsCreatorGate(h)){const release=btn("Release Creator + Enable Video",()=>this.bypassPreStage(),"z3h3-btn primary z3pre-release-creator");release.title="Stop PreStage from gating video. Creator will run normally until you generate another PreStage batch.";panel.append(release)}
  }
  openFlowSettings(){
    modal("PreStage Flow",(body,close)=>{const h=this.data.handoff;
    const mode=select([["review","Review first · video waits for you"],["auto","Auto · generate and queue video"],["image_only","Image only · never queue video"],["bypass","Bypass · Creator runs alone"]],h.mode);
    const destination=select([["first_frame","Start frame · current shot"],["reference","Reference · current shot"],["last_frame","End frame · current shot"],["new_shot","New timeline shot · start frame"],["none","Keep file only · no handoff"]],h.destination);
    const count=select([[1,"1 image"],[2,"2 images"],[4,"4 images"],[8,"8 images"],[16,"16 images"]],h.batch_count);
    const policy=select([["first","First result"],["last","Last result"],["seeded","Seeded pick · repeatable"]],h.selection_policy);
    const hint=h.mode==="review"?"Creator is stopped first. Results appear below; choose one before video can run.":h.mode==="auto"?"After the image batch, the chosen result is previewed for 4 seconds, then attached and video is queued. You can cancel during the preview.":h.mode==="image_only"?"Only stills run. Creator stays paused until you use an image or explicitly resume it.":"PreStage does not render and Creator is free to run.";
    const liveHint=el("div","z3h3-note",hint),syncHint=()=>{liveHint.textContent=h.mode==="review"?"Creator waits while you curate in Image Lab.":h.mode==="auto"?"The chosen still is previewed for four seconds before video queues.":h.mode==="image_only"?"Generate and curate stills without starting video.":"PreStage stays out of the queue; Creator runs normally."};
    mode.onchange=()=>{clearTimeout(this._autoTimer);this._autoTimer=null;h.mode=mode.value;h.phase=mode.value==="bypass"?"idle":"ready";if(h.mode==="auto"&&h.destination==="none"){h.destination="first_frame";destination.value=h.destination}this.commit();this.syncCreatorGate();syncHint()};
    destination.onchange=()=>{h.destination=destination.value;if(h.mode==="auto"&&h.destination==="none"){h.mode="review";mode.value=h.mode}this.commit();this.syncCreatorGate();syncHint()};
    count.onchange=()=>{h.batch_count=Number(count.value);this.commit()};policy.onchange=()=>{h.selection_policy=policy.value;this.commit()};
    body.append(el("div","z3h3-note good","Choose a flow once; it is stored in the workflow. Image Lab owns result review and sends selected frames to Creator without rewriting your prompt."),el("div","z3h3-two"),liveHint,row(btn("Generate now",async()=>{await this.runImageBatch();close()},"z3h3-btn primary"),btn("Run Creator only",async()=>{await this.runCreatorOnly();close()},"z3h3-btn primary"),btn("Release Creator + Enable Video",()=>{this.bypassPreStage();close()},"z3h3-btn primary z3pre-release-creator"),btn("Done",close,"z3h3-btn")));body.querySelector(".z3h3-two").append(field("After still generation",mode),field("Auto handoff target",destination),field("Images this batch",count),field("Automatic batch pick",policy));
    },{small:true});
  }
  syncCreatorGate(){return setCreatorPreStageGate(this,preStageNeedsCreatorGate(this.data.handoff),this.data.handoff.mode==="image_only"?"Creator is paused while PreStage is in image-only mode.":"Creator is waiting for a reviewed PreStage image.")}
  setHandoffMode(mode){clearTimeout(this._autoTimer);this._autoTimer=null;this._autoCandidate=null;this.data.handoff.mode=mode;this.data.handoff.phase=mode==="bypass"?"idle":"ready";if(mode==="auto"&&this.data.handoff.destination==="none")this.data.handoff.destination="first_frame";this.commit(false);this.syncCreatorGate();this.imageSidecar?.sync();return mode}
  relinkCreator(){const result=bindPreStageToActiveCreator(this);if(result.ok){this.announce("PreStage linked to the active Creator and its current shot.");this.renderStatus();this.imageSidecar?.sync();}else this.announce(result.message,"error");return result}
  async runImageBatch(countOverride=null){
    if(this._pendingImageBatch)throw new Error("A PreStage image batch is already running.");
    if(this.data.handoff.mode==="bypass")this.data.handoff.mode="review";
    if(countOverride!=null)this.data.handoff.batch_count=Math.max(1,Math.min(16,Math.trunc(Number(countOverride)||1)));
    if(!modePrompt(this.data).trim())this.autoPullIfBlank();
    if(!modePrompt(this.data).trim())throw new Error("Add a PreStage prompt or Pull Creator before generating.");
    clearTimeout(this._autoTimer);this._autoTimer=null;this._autoCandidate=null;this._batchCandidates=[];
    this.data.handoff.phase="ready";this._pendingImageBatch={remaining:this.data.handoff.batch_count};this.announce(this.data.handoff.mode==="auto"?`Queued ${this.data.handoff.batch_count} still(s); Auto will queue video after its visible countdown.`:`Queued ${this.data.handoff.batch_count} still(s); Creator is waiting for Image Lab.`);this.commit(false);this.syncCreatorGate();
    try{if(typeof app?.queuePrompt!=="function")throw new Error("ComfyUI queue action is unavailable in this frontend build.");await app.queuePrompt(0,this.data.handoff.batch_count);}catch(error){this._pendingImageBatch=null;this.announce(`Could not queue PreStage: ${error.message||error}`,"error");this.refresh();throw error}
  }
  announce(message,kind="good"){this._actionMessage=String(message||"");this._actionKind=kind;clearTimeout(this._actionMessageTimer);this._actionMessageTimer=setTimeout(()=>{this._actionMessage="";this.renderStatus();this.imageSidecar?.sync()},5000);this.renderStatus();this.imageSidecar?.sync()}
  bypassPreStage(){clearTimeout(this._autoTimer);this._autoTimer=null;this._autoCandidate=null;this.data.handoff.mode="bypass";this.data.handoff.phase="idle";this.commit(false);const result=setCreatorPreStageGate(this,false);this.announce(result.ok?"Creator released — video is enabled. PreStage will stay bypassed until you generate another still batch.":result.message,result.ok?"good":"error");this.imageSidecar?.sync();return result}
  async runCreatorOnly(){const released=this.bypassPreStage();if(!released.ok)throw new Error(released.message);if(typeof app?.queuePrompt!=="function")throw new Error("ComfyUI queue action is unavailable in this frontend build.");this.announce("PreStage bypassed; Creator-only queue submitted.");await app.queuePrompt(0,1)}
  imageForSlot(slot){const key=this.data.handoff.slots?.[slot]||"";return this.history.find(image=>historyKey(image)===key)||null}
  slotsForImage(image){return slotsForHistoryKey(this.data.handoff,historyKey(image))}
  assignImageSlot(image,slot){if(!image?.filename)return false;const key=historyKey(image);if(!toggleHistorySlot(this.data.handoff,slot,key))return false;this.data.handoff.mode=this.data.handoff.mode==="bypass"?"review":this.data.handoff.mode;this.data.handoff.phase="review";this.commit(false);this.syncCreatorGate();this.announce(`${slot==="first_frame"?"Start":slot==="last_frame"?"End":"Reference"} ${this.data.handoff.slots[slot]?"selected":"cleared"}.`);return true}
  clearImageSlot(slot){if(this.data.handoff.slots?.[slot]){this.data.handoff.slots[slot]="";this.commit(false);this.announce(`${slot==="first_frame"?"Start":slot==="last_frame"?"End":"Reference"} cleared.`)}}
  async handoffSelected(image,destination=this.data.handoff.destination,queueVideo=false){if(!image?.filename)throw new Error("Choose an image in Image Lab first.");if(destination==="none")throw new Error("Choose Start frame, End frame, Reference, or New shot before handoff.");const result=applyPreStageImageToCreator(this,image,destination);if(!result.ok)throw new Error(result.message);this.data.handoff.destination=destination;this.data.handoff.phase="idle";this.commit(false);this.syncCreatorGate();const label=destination==="first_frame"?"Start frame":destination==="last_frame"?"End frame":destination==="reference"?"Reference":"New shot start frame";this.announce(`${label} sent to Creator without changing the authored prompt${queueVideo?"; video queued":""}.`);this.imageSidecar?.select?.(image);if(queueVideo){if(typeof app?.queuePrompt!=="function")throw new Error("ComfyUI queue action is unavailable in this frontend build.");setTimeout(()=>app.queuePrompt(0,1),0)}return result}
  async applyFrameSetup(queueVideo=false){const ordered=["first_frame","last_frame","reference"],chosen=ordered.map(slot=>[slot,this.imageForSlot(slot)]).filter(([,image])=>image);if(!chosen.length)throw new Error("Mark at least a Start, End, or Reference image first.");const result=applyPreStageImagesToCreator(this,chosen.map(([destination,image])=>({destination,image})),{historyLabel:"Send marked PreStage frames"});if(!result.ok)throw new Error(result.message);this.data.handoff.phase="idle";this.commit(false);this.syncCreatorGate();this.announce(`${chosen.map(([slot])=>slot==="first_frame"?"Start":slot==="last_frame"?"End":"Reference").join(" + ")} sent to Creator without changing the authored prompt${queueVideo?"; video queued":""}.`);this.imageSidecar?.sync();if(queueVideo){if(typeof app?.queuePrompt!=="function")throw new Error("ComfyUI queue action is unavailable in this frontend build.");setTimeout(()=>app.queuePrompt(0,1),0)}return result}
  async makeNewShotFromSelected(image,queueVideo=false){if(!image?.filename)throw new Error("Choose an image first.");const result=this.useImage(image,false,"new_shot");this.announce(`New Creator shot prepared from ${fileLabel(image.filename)}${queueVideo?"; video queued":""}.`);if(queueVideo){if(typeof app?.queuePrompt!=="function")throw new Error("ComfyUI queue action is unavailable in this frontend build.");setTimeout(()=>app.queuePrompt(0,1),0)}return result}
  persistHistory(){this.history=this.history.filter(x=>x?.filename).slice(-64);this.node.properties.z3_prestage_history=this.history;this.node.graph?.setDirtyCanvas?.(true,true);this.imageSidecar?.sync()}
  clearHistory(){this.history=[];this.data.handoff.slots={first_frame:"",last_frame:"",reference:""};this.commit(false);this.persistHistory();this.renderGallery()}
  removeHistoryImage(image){const key=historyKey(image);this.history=this.history.filter(row=>historyKey(row)!==key);for(const slot of ["first_frame","last_frame","reference"])if(this.data.handoff.slots?.[slot]===key)this.data.handoff.slots[slot]="";this.commit(false);this.persistHistory();this.renderGallery()}
  toggleHistoryShortlist(image){const key=[image?.type,image?.subfolder,image?.filename].join("|"),row=this.history.find(item=>[item.type,item.subfolder,item.filename].join("|")===key);if(!row)return false;row.shortlisted=!row.shortlisted;this.persistHistory();this.renderGallery();return row.shortlisted}
  useImageAs(image,destination,queueVideo=false){this.data.handoff.destination=destination;return this.useImage(image,queueVideo,destination)}
  useImage(image,queueVideo=false,destination=this.data.handoff.destination){
    clearTimeout(this._autoTimer);this._autoTimer=null;this._autoCandidate=null;
    if(destination==="none")throw new Error("Choose a Creator destination before using this image.");
    const result=applyPreStageImageToCreator(this,image,destination);if(!result.ok)throw new Error(result.message);
    this.data.handoff.phase="idle";this.commit(false);this.renderGallery();
    if(queueVideo){if(typeof app?.queuePrompt!=="function")throw new Error("ComfyUI queue action is unavailable in this frontend build.");setTimeout(()=>app.queuePrompt(0,1),0)}
    return result;
  }
  async auditionImages(images,destination=this.data.handoff.destination){
    const rows=(images||[]).filter(x=>x?.filename);if(!rows.length)throw new Error("Add images to the shortlist first.");if(destination==="none")destination="first_frame";if(typeof app?.queuePrompt!=="function")throw new Error("ComfyUI queue action is unavailable in this frontend build.");clearTimeout(this._autoTimer);this._autoTimer=null;this.data.handoff.phase="idle";
    let creator=null,variation=null,seed=null;
    for(const image of rows){const result=applyPreStageImageToCreator(this,image,destination);if(!result.ok)throw new Error(result.message);creator ||= result.creator;if(variation==null)variation=creator.currentVariationIndex?.()??0;if(seed==null)seed=Number(creator.widgets?.seed?.value);creator.setVariationIndex?.(variation,false);if(Number.isFinite(seed)&&creator.widgets?.seed)creator.widgets.seed.value=seed;await app.queuePrompt(0,1)}
    creator?.setVariationIndex?.(variation??0,false);if(Number.isFinite(seed)&&creator?.widgets?.seed)creator.widgets.seed.value=seed;this.commit(false);this.imageSidecar?.sync();return rows.length;
  }
  cancelAutoVideo(){clearTimeout(this._autoTimer);this._autoTimer=null;this._autoCandidate=null;this.data.handoff.mode="review";this.data.handoff.phase="review";this.commit(false);this.syncCreatorGate()}
  scheduleAutoVideo(image){
    clearTimeout(this._autoTimer);this._autoCandidate=image;const slot=["first_frame","last_frame","reference"].includes(this.data.handoff.destination)?this.data.handoff.destination:"first_frame";this.data.handoff.slots[slot]=historyKey(image);this.commit(false);this.announce(`Auto selected ${fileLabel(image.filename)} as ${slot==="first_frame"?"Start":slot==="last_frame"?"End":"Reference"}. Video queues in 4 seconds unless cancelled.`);this.renderGallery();this.imageSidecar?.select(image);
    this._autoTimer=setTimeout(()=>{this._autoTimer=null;this.useImage(image,true)},4000);
  }
  renderGallery(){
    // Image Lab is the sole PreStage result surface. Keeping generated stills off
    // the node avoids duplicate previews and makes the next step unambiguous.
    this.imageSidecar?.sync();
  }
  renderStatus(){const model=this.data.arch==="krea2"?(this.data.turbo.on?"Krea 2 Turbo":"Krea 2 RAW"):this.data.arch==="ideogram4"?`Ideogram 4 · ${this.data.quality}`:`MiniMax H3 still · ${this.data.minimax.frames} frames`;const prompt=modePrompt(this.data).trim(),peer=findCreatorForPreStage(this);this.status.replaceChildren(el("strong",null,model),el("span",null,prompt?"Ready":(peer?"Idle · linked to Creator":"Idle · add a prompt or Pull Creator")),el("span",null,peer?`Creator #${peer.node?.id??"linked"} · ${peer.target==="global"?"GLOBAL":`Shot ${Number(peer.target)+1}`}`:"Creator not linked"),el("span",null,`${promptRefs(this.data).length} reference(s)`),el("span",null,`${promptLoras(this.data).filter(x=>x.enabled!==false).length} LoRA(s)`));if(this._actionMessage)this.status.append(el("span",this._actionKind==="error"?"z3h3-error":"z3h3-good",this._actionMessage))}
  async openMedia(){
    modal("PreStage Media",async(body,close)=>{let root="input",rows=[];const tabs=row(),search=input("search","");search.placeholder="Search local media…";const grid=el("div","z3h3-grid"),note=el("div","z3h3-note");const render=()=>{grid.replaceChildren();const q=search.value.toLowerCase();for(const r of rows.filter(x=>!q||String(x.path).toLowerCase().includes(q))){if(this.data.arch!=="minimax"&&r.kind!=="image")continue;const c=el("div","z3h3-card"),th=el("div","z3h3-thumb");if(r.kind==="image")th.style.backgroundImage=`url("${H.thumbUrl(r.path,256)}")`;else th.textContent=r.kind==="video"?"▶":"♪";const meta=el("div","z3h3-card-meta");meta.append(el("b",null,fileLabel(r.path)));const actions=row();if(this.data.arch==="minimax"){actions.append(btn("Reference",()=>{const kind=r.kind,a=S.createAsset(kind,r.path,this.data,"reference");this.data.minimax.request.assets.push(a);this.commit();close()},"z3h3-mini"));if(r.kind==="image")actions.append(btn("Start",()=>{const a=S.createAsset("image",r.path,this.data,"first_frame");this.data.minimax.request.assets.push(a);this.commit();close()},"z3h3-mini"),btn("End",()=>{const a=S.createAsset("image",r.path,this.data,"last_frame");this.data.minimax.request.assets.push(a);this.commit();close()},"z3h3-mini"))}else{if(this.data.arch==="krea2"&&this.data.refs.length<3)actions.append(btn("Style ref",()=>{this.data.refs.push({handle:nextHandle(this.data),filename:r.path});this.commit();close()},"z3h3-mini"));actions.append(btn("Init",()=>{this.data.init={filename:r.path,denoise:this.data.init?.denoise??0.65};this.commit();close()},"z3h3-mini"))}meta.append(actions);c.append(th,meta);grid.append(c)}note.textContent=`${grid.children.length} compatible local item(s)`};
      const load=async()=>{try{const r=await H.listAssets(root);rows=r.assets||[];render()}catch(e){note.textContent=e.message}};for(const [id,label] of [["input","Input"],["output","Renders"]])tabs.append(btn(label,()=>{root=id;load()},"z3h3-tab"));search.oninput=render;body.append(tabs,search,note,grid);await load()})
  }
  pullCreator(){const result=pullCreatorIntoPreStage(this);this.renderStatus();if(!result.ok){modal("Pull Creator",(body,close)=>body.append(el("div","z3h3-note",result.message),row(btn("Link active Creator",()=>{const linked=this.relinkCreator();if(linked.ok){pullCreatorIntoPreStage(this);close()}},"z3h3-btn primary"),btn("Close",close,"z3h3-btn"))),{small:true});}return result.ok}
  autoPullIfBlank(){if(modePrompt(this.data).trim())return false;const creator=findCreatorForPreStage(this);if(!creator)return false;return pullCreatorIntoPreStage(this).ok}
  editInit(){modal("Init image",(body,close)=>{const d=select([[.2,"0.20 · preserve strongly"],[.4,"0.40 · preserve"],[.55,"0.55 · balanced"],[.65,"0.65 · flexible"],[.8,"0.80 · loose"],[1,"1.00 · effectively ignore init"]],Number(this.data.init?.denoise??.65));d.onchange=()=>{if(this.data.init){this.data.init.denoise=Number(d.value);this.commit();}};body.append(el("img","z3pre-preview"),el("div","z3h3-note good","Live setting — changing denoise immediately updates the next queue."),field("Denoise / strength",d,"Choose a clear preservation preset instead of hunting on a slider."),row(btn("Done",close,"z3h3-btn primary"),btn("Remove",()=>{this.data.init=null;this.commit();close()})));body.querySelector("img").src=imageUrl(this.data.init.filename)},{small:true})}
  editRef(a){modal("Reference",(body,close)=>{const original=String(a.handle||"ref"),handle=input("text",original);const current=()=>promptRefs(this.data).find(x=>x.handle===original)||promptRefs(this.data).find(x=>x.filename===a.filename);handle.onchange=()=>{const row=current();if(!row)return;row.handle=handle.value.trim()||row.handle;this.commit();};body.append(el("div","z3h3-note good","Live reference settings — no Save step."),field("Handle",handle),el("div","z3h3-note",a.filename),row(btn("Insert @ mention",()=>this.insertText(`@${handle.value.trim()||original}`)),btn("Done",close,"z3h3-btn primary"),btn("Remove",()=>{const item=current(),list=promptRefs(this.data),i=list.indexOf(item);if(i>=0)list.splice(i,1);this.commit();close()})))},{small:true})}
  insertText(t){const text=String(t??"").trim();if(!text)return false;const ta=this.ppRoot.querySelector('[data-el="textarea"]')||this.ppRoot.querySelector('[data-pp-editor-surface]')||this.ppRoot.querySelector("textarea.wg-textarea")||this.ppRoot.querySelector("textarea");if(ta&&typeof ta.setRangeText==="function"){const value=String(ta.value??""),s=ta.selectionStart??value.length,e=ta.selectionEnd??s,pad=s&&/\S$/.test(value.slice(0,s))?" ":"",tail=e<value.length&&/^\S/.test(value.slice(e))?" ":"";ta.setRangeText(`${pad}${text}${tail}`,s,e,"end");ta.dispatchEvent(new Event("input",{bubbles:true}));setModePrompt(this.data,String(ta.value??""));this.commit();ta.focus?.({preventScroll:true});return true}const current=modePrompt(this.data).trim();setModePrompt(this.data,current?`${current}\n\n${text}`:text);this.commit();this.syncPrompt(false);return true}
  async openLoras(){modal("PreStage LoRAs",async(body,close)=>{
    const list=el("div","z3h3-list"),search=input("search","");search.placeholder="Search installed LoRAs…";const cat=el("div","z3h3-grid"),note=el("div","z3h3-note");let all=[];
    const container=()=>this.data.arch==="minimax"?this.data.minimax.request:this.data;
    const find=(name)=>(container().loras||[]).find(x=>x.name===name);
    const active=()=>{list.replaceChildren();for(const l of container().loras||[]){const r=el("div","z3h3-row"),on=checkbox(l.enabled!==false),st=input("number",l.strength??1);st.step=.05;on.onchange=()=>{const e=find(l.name);if(e){e.enabled=on.checked;this.commit();active();render();}};st.onchange=()=>{const e=find(l.name);if(e){e.strength=Number(st.value);this.commit();active();render();}};r.append(el("b",null,fileLabel(l.name)),field("On",on),field("Strength",st),btn("Remove",()=>{const c=container(),i=(c.loras||[]).findIndex(x=>x.name===l.name);if(i>=0)c.loras.splice(i,1);this.commit();active();render()}));list.append(r)}if(!list.children.length)list.append(el("div","z3h3-note","No LoRAs attached. Pick one below and it becomes active immediately."))};
    const render=()=>{cat.replaceChildren();const q=search.value.toLowerCase(),c=container();for(const l of all.filter(x=>!q||String(x.name).toLowerCase().includes(q))){const identity=loraLibraryIdentity(l),selection=loraLibrarySelection(l),loraName=selection.name,card=el("div","z3h3-card"),meta=el("div","z3h3-card-meta"),existing=(c.loras||[]).find(x=>x.name===loraName);card.dataset.loraName=loraName;card.title=loraName;meta.append(el("b",null,identity.filename),el("small","z3h3-note",[identity.folder,identity.metadataTitle,...selection.triggers].filter(Boolean).join(" · ")),btn(existing&&existing.enabled!==false?"Active":"Add",()=>{const live=container();let e=(live.loras||[]).find(x=>x.name===loraName);if(!e){e={name:loraName,strength:1,enabled:true,triggers:[...selection.triggers]};live.loras.push(e)}else e.enabled=true;this.commit();active();render();},existing&&existing.enabled!==false?"z3h3-btn active":"z3h3-btn primary"));card.append(meta);cat.append(card)}note.textContent=`${cat.children.length} installed LoRA(s) · every selection is live`};
    search.oninput=render;body.append(el("div","z3h3-note good","Live selection: Add, On/Off and strength changes are committed immediately."),section("Active",list),section("Installed",search,note,cat),row(btn("Done",close,"z3h3-btn primary")));active();try{const r=await H.listLoras("",false);all=normalizeLoraLibraryRows(r.loras||r.entries||[]);render()}catch(e){note.textContent=e.message}
  })}
  async openModels(){modal("PreStage Models",async(body,close)=>{const note=el("div","z3h3-note","Loading local model folders…");body.append(note);try{const m=await H.listModels();body.replaceChildren();const by=m.by_folder||{};
    const side=()=>this.data.arch==="minimax"?this.data.minimax.request.models:(this.data.models[this.data.arch]||=( {}));
    const liveSave=async()=>{this.commit();await this.persistModelDefaults(note);};
    const defs=this.data.arch==="krea2"?[["model","Krea RAW checkpoint","diffusion_models"],["turbo_model","Krea Turbo checkpoint","diffusion_models"],["clip","Krea text encoder","text_encoders"],["vae","VAE","vae"]]:this.data.arch==="ideogram4"?[["model","Ideogram checkpoint","diffusion_models"],["uncond_model","Ideogram unconditional checkpoint","diffusion_models"],["clip","Ideogram text encoder","text_encoders"],["vae","VAE","vae"]]:[["fl2va","H3 FL2VA checkpoint","diffusion_models"],["ref2va","H3 Ref2VA checkpoint","diffusion_models"],["clip","MiniMax text encoder","text_encoders"],["vae","Video VAE","vae"],["audio_vae","Audio VAE","vae"],["preview","taeh3 preview","vae_approx"]];
    const grid=el("div","z3h3-two");for(const [key,label,folder] of defs){const c=select([["","— choose local file —"],...(by[folder]||[]).map(x=>[x,x])],side()[key]||"");c.onchange=async()=>{const block=side();if(c.value)block[key]=c.value;else delete block[key];await liveSave()};grid.append(field(label,c,`models/${folder}`))}
    const dtype=select(m.dtypes||["default"],this.data.models.dtype||"default");dtype.onchange=async()=>{this.data.models.dtype=dtype.value;if(this.data.arch==="minimax")this.data.minimax.request.models.dtype=dtype.value;await liveSave()};body.append(el("div","z3h3-note good","Live model selection — choose it and it is immediately part of the next queue and local defaults."),grid,field("Weight dtype",dtype),el("div","z3h3-note",m.preview_override?"KJ Model Preview Override is available.":"KJ Model Preview Override is optional and not installed."),note,row(btn("Done",close,"z3h3-btn primary")));note.textContent="Selections save automatically.";note.className="z3h3-note good"}catch(e){note.textContent=e.message}})}
  openSampling(){modal("PreStage Sampling",(body,close)=>{const controls=[];for(const [key,label,type] of [["seed","Seed","number"],["steps","Steps","number"],["cfg","CFG","number"]]){const w=this.widgets[key],c=input(type,w?.value??0);c.onchange=()=>setWidget(w,Number(c.value),this.node);controls.push(field(label,c))}const sampler=select(this.widgets.sampler_name?.options?.values||["euler","res_multistep"],this.widgets.sampler_name?.value),scheduler=select(this.widgets.scheduler?.options?.values||["simple","beta","normal"],this.widgets.scheduler?.value);sampler.onchange=()=>setWidget(this.widgets.sampler_name,sampler.value,this.node);scheduler.onchange=()=>setWidget(this.widgets.scheduler,scheduler.value,this.node);body.append(el("div","z3h3-two"),row(btn("Done",close,"z3h3-btn primary")));const g=body.firstChild;g.append(...controls,field("Sampler",sampler),field("Scheduler",scheduler))})}
  handleExecution(out){
    const idle=(out?.mmc_prestage_idle||[])[0];if(idle){this._actionMessage=idle.message||"PreStage is idle.";this._actionKind="good";this.renderStatus();this.imageSidecar?.sync();return}
    const images=(out?.mmc_image?.length?out.mmc_image:(out?.images||[])).filter(x=>x?.filename);if(!images.length)return;
    this._batchCandidates ||= [];
    for(const image of images){const key=[image.type,image.subfolder,image.filename].join("|"),prior=this.history.find(row=>[row.type,row.subfolder,row.filename].join("|")===key);this.history=this.history.filter(row=>[row.type,row.subfolder,row.filename].join("|")!==key);this.history.push({...image,shortlisted:!!prior?.shortlisted,created_at:Date.now()});this._batchCandidates.push(image)}
    this.persistHistory();this.imageSidecar?.showResults(images);
    if(this._pendingImageBatch)this._pendingImageBatch.remaining=Math.max(0,this._pendingImageBatch.remaining-1);
    const complete=!this._pendingImageBatch||this._pendingImageBatch.remaining===0;
    if(complete){this._pendingImageBatch=null;this.data.handoff.phase="review";this.commit(false);const candidates=this._batchCandidates.length?this._batchCandidates:images;this._batchCandidates=[];if(this.data.handoff.mode==="auto"){const selected=pickPreStageCandidate(candidates,this.data.handoff.selection_policy,this.widgets.seed?.value);if(selected)this.scheduleAutoVideo(selected)}}
    this.renderHandoff();this.renderGallery();this.renderStatus();
  }
}
